/*
 * SemgrepWebAppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.semgrep;

import dev.semgrep.apis.DeploymentsServiceApi;
import dev.semgrep.apis.FindingsServiceApi;
import dev.semgrep.apis.MiscServiceApi;
import dev.semgrep.apis.PoliciesServiceApi;
import dev.semgrep.apis.ProjectsServiceApi;
import dev.semgrep.apis.ScansServiceApi;
import dev.semgrep.apis.SecretsServiceApi;
import dev.semgrep.apis.SupplyChainServiceApi;
import dev.semgrep.apis.TicketingServiceApi;
import dev.semgrep.apis.TriageServiceApi;
import dev.semgrep.authentication.SemgrepAdminJwtCredentials;
import dev.semgrep.authentication.SemgrepAdminJwtManager;
import dev.semgrep.authentication.SemgrepAdminJwtModel;
import dev.semgrep.authentication.SemgrepJwtCredentials;
import dev.semgrep.authentication.SemgrepJwtManager;
import dev.semgrep.authentication.SemgrepJwtModel;
import dev.semgrep.authentication.SemgrepWebTokenCredentials;
import dev.semgrep.authentication.SemgrepWebTokenManager;
import dev.semgrep.authentication.SemgrepWebTokenModel;
import dev.semgrep.http.client.HttpCallback;
import dev.semgrep.http.client.HttpClientConfiguration;
import dev.semgrep.http.client.ReadonlyHttpClientConfiguration;
import dev.semgrep.logging.configuration.ApiLoggingConfiguration;
import dev.semgrep.logging.configuration.ReadonlyLoggingConfiguration;
import io.apimatic.core.GlobalConfiguration;
import io.apimatic.coreinterfaces.authentication.Authentication;
import io.apimatic.coreinterfaces.compatibility.CompatibilityFactory;
import io.apimatic.coreinterfaces.http.HttpClient;
import io.apimatic.okhttpclient.adapter.OkClient;
import java.util.AbstractMap.SimpleEntry;
import java.util.HashMap;
import java.util.Map;
import java.util.function.Consumer;
import java.util.function.Supplier;

/**
 * Gateway class for the library.
 * This class acts as a factory for Apis.
 * It holds the state of the SDK.
 */
public final class SemgrepWebAppClient implements Configuration {

    /**
     * Private store for controllers.
     */
    private DeploymentsServiceApi deploymentsService;
    private FindingsServiceApi findingsService;
    private MiscServiceApi miscService;
    private PoliciesServiceApi policiesService;
    private ProjectsServiceApi projectsService;
    private ScansServiceApi scansService;
    private SecretsServiceApi secretsService;
    private SupplyChainServiceApi supplyChainService;
    private TicketingServiceApi ticketingService;
    private TriageServiceApi triageService;

    private static final CompatibilityFactory compatibilityFactory = new CompatibilityFactoryImpl();

    private static String userAgent = "Java-SDK/0.0.1 (OS: {os-info}, Engine: {engine}/{engine-version})";

    /**
     * Current API environment.
     */
    private final Environment environment;

    /**
     * The HTTP Client instance to use for making HTTP requests.
     */
    private final HttpClient httpClient;

    /**
     * Http Client Configuration instance.
     */
    private final ReadonlyHttpClientConfiguration httpClientConfig;

    /**
     * Logging Configuration instance.
     */
    private final ReadonlyLoggingConfiguration loggingConfig;

    /**
     * SemgrepAdminJwtManager.
     */
    private SemgrepAdminJwtManager semgrepAdminJwtManager;

    /**
     * The instance of SemgrepAdminJwtModel.
     */
    private SemgrepAdminJwtModel semgrepAdminJwtModel;

    /**
     * SemgrepJwtManager.
     */
    private SemgrepJwtManager semgrepJwtManager;

    /**
     * The instance of SemgrepJwtModel.
     */
    private SemgrepJwtModel semgrepJwtModel;

    /**
     * SemgrepWebTokenManager.
     */
    private SemgrepWebTokenManager semgrepWebTokenManager;

    /**
     * The instance of SemgrepWebTokenModel.
     */
    private SemgrepWebTokenModel semgrepWebTokenModel;

    /**
     * Map of authentication Managers.
     */
    private Map<String, Authentication> authentications = new HashMap<String, Authentication>();

    /**
     * Callback to be called before and after the HTTP call for an endpoint is made.
     */
    private final HttpCallback httpCallback;

    private SemgrepWebAppClient(Environment environment, HttpClient httpClient,
            ReadonlyHttpClientConfiguration httpClientConfig,
            ReadonlyLoggingConfiguration loggingConfig, SemgrepAdminJwtModel semgrepAdminJwtModel,
            SemgrepJwtModel semgrepJwtModel, SemgrepWebTokenModel semgrepWebTokenModel,
            HttpCallback httpCallback) {
        this.environment = environment;
        this.httpClient = httpClient;
        this.httpClientConfig = httpClientConfig;
        this.loggingConfig = loggingConfig;
        this.httpCallback = httpCallback;

        this.semgrepAdminJwtModel = semgrepAdminJwtModel;
        this.semgrepJwtModel = semgrepJwtModel;
        this.semgrepWebTokenModel = semgrepWebTokenModel;

        this.semgrepAdminJwtManager = new SemgrepAdminJwtManager(semgrepAdminJwtModel);
        this.authentications.put("SemgrepAdminJWT", semgrepAdminJwtManager);

        this.semgrepJwtManager = new SemgrepJwtManager(semgrepJwtModel);
        this.authentications.put("SemgrepJWT", semgrepJwtManager);

        this.semgrepWebTokenManager = new SemgrepWebTokenManager(semgrepWebTokenModel);
        this.authentications.put("SemgrepWebToken", semgrepWebTokenManager);

        GlobalConfiguration globalConfig = new GlobalConfiguration.Builder()
                .httpClient(httpClient).baseUri(server -> getBaseUri(server))
                .compatibilityFactory(compatibilityFactory)
                .authentication(this.authentications)
                .callback(httpCallback)
                .userAgent(userAgent)
                .loggingConfiguration(((ApiLoggingConfiguration) loggingConfig).getConfiguration())
                .build();
        deploymentsService = new DeploymentsServiceApi(globalConfig);
        findingsService = new FindingsServiceApi(globalConfig);
        miscService = new MiscServiceApi(globalConfig);
        policiesService = new PoliciesServiceApi(globalConfig);
        projectsService = new ProjectsServiceApi(globalConfig);
        scansService = new ScansServiceApi(globalConfig);
        secretsService = new SecretsServiceApi(globalConfig);
        supplyChainService = new SupplyChainServiceApi(globalConfig);
        ticketingService = new TicketingServiceApi(globalConfig);
        triageService = new TriageServiceApi(globalConfig);
    }

    /**
     * Shutdown the underlying HttpClient instance.
     */
    public static void shutdown() {
        OkClient.shutdown();
    }

    /**
     * Get the instance of DeploymentsServiceApi.
     * @return deploymentsService
     */
    public DeploymentsServiceApi getDeploymentsServiceApi() {
        return deploymentsService;
    }

    /**
     * Get the instance of FindingsServiceApi.
     * @return findingsService
     */
    public FindingsServiceApi getFindingsServiceApi() {
        return findingsService;
    }

    /**
     * Get the instance of MiscServiceApi.
     * @return miscService
     */
    public MiscServiceApi getMiscServiceApi() {
        return miscService;
    }

    /**
     * Get the instance of PoliciesServiceApi.
     * @return policiesService
     */
    public PoliciesServiceApi getPoliciesServiceApi() {
        return policiesService;
    }

    /**
     * Get the instance of ProjectsServiceApi.
     * @return projectsService
     */
    public ProjectsServiceApi getProjectsServiceApi() {
        return projectsService;
    }

    /**
     * Get the instance of ScansServiceApi.
     * @return scansService
     */
    public ScansServiceApi getScansServiceApi() {
        return scansService;
    }

    /**
     * Get the instance of SecretsServiceApi.
     * @return secretsService
     */
    public SecretsServiceApi getSecretsServiceApi() {
        return secretsService;
    }

    /**
     * Get the instance of SupplyChainServiceApi.
     * @return supplyChainService
     */
    public SupplyChainServiceApi getSupplyChainServiceApi() {
        return supplyChainService;
    }

    /**
     * Get the instance of TicketingServiceApi.
     * @return ticketingService
     */
    public TicketingServiceApi getTicketingServiceApi() {
        return ticketingService;
    }

    /**
     * Get the instance of TriageServiceApi.
     * @return triageService
     */
    public TriageServiceApi getTriageServiceApi() {
        return triageService;
    }

    /**
     * Current API environment.
     * @return environment
     */
    public Environment getEnvironment() {
        return environment;
    }

    /**
     * The HTTP Client instance to use for making HTTP requests.
     * @return httpClient
     */
    private HttpClient getHttpClient() {
        return httpClient;
    }

    /**
     * Http Client Configuration instance.
     * @return httpClientConfig
     */
    public ReadonlyHttpClientConfiguration getHttpClientConfig() {
        return httpClientConfig;
    }

    /**
     * Logging Configuration instance.
     * @return loggingConfig
     */
    public ReadonlyLoggingConfiguration getLoggingConfig() {
        return loggingConfig;
    }

    /**
     * The credentials to use with SemgrepAdminJwt.
     * @return semgrepAdminJwtCredentials
     */
    public SemgrepAdminJwtCredentials getSemgrepAdminJwtCredentials() {
        return semgrepAdminJwtManager;
    }

    /**
     * The auth credential model for SemgrepAdminJwt.
     * @return the instance of SemgrepAdminJwtModel
     */
    public SemgrepAdminJwtModel getSemgrepAdminJwtModel() {
        return semgrepAdminJwtModel;
    }

    /**
     * OAuth 2.0 Access Token.
     * @return accessToken
     */
    public String getAccessToken() {
        return getSemgrepAdminJwtCredentials().getAccessToken();
    }
    /**
     * The credentials to use with SemgrepJwt.
     * @return semgrepJwtCredentials
     */
    public SemgrepJwtCredentials getSemgrepJwtCredentials() {
        return semgrepJwtManager;
    }

    /**
     * The auth credential model for SemgrepJwt.
     * @return the instance of SemgrepJwtModel
     */
    public SemgrepJwtModel getSemgrepJwtModel() {
        return semgrepJwtModel;
    }

    /**
     * OAuth 2.0 Access Token.
     * @return accessToken2
     */
    public String getAccessToken2() {
        return getSemgrepJwtCredentials().getAccessToken();
    }
    /**
     * The credentials to use with SemgrepWebToken.
     * @return semgrepWebTokenCredentials
     */
    public SemgrepWebTokenCredentials getSemgrepWebTokenCredentials() {
        return semgrepWebTokenManager;
    }

    /**
     * The auth credential model for SemgrepWebToken.
     * @return the instance of SemgrepWebTokenModel
     */
    public SemgrepWebTokenModel getSemgrepWebTokenModel() {
        return semgrepWebTokenModel;
    }

    /**
     * OAuth 2.0 Access Token.
     * @return accessToken3
     */
    public String getAccessToken3() {
        return getSemgrepWebTokenCredentials().getAccessToken();
    }
    /**
     * The timeout to use for making HTTP requests.
     * @deprecated This method will be removed in a future version. Use
     *             {@link #getHttpClientConfig()} instead.
     *
     * @return timeout
     */
    @Deprecated
    public long timeout() {
        return httpClientConfig.getTimeout();
    }

    /**
     * Get base URI by current environment.
     * @param server Server for which to get the base URI
     * @return Processed base URI
     */
    public String getBaseUri(Server server) {
        Map<String, SimpleEntry<Object, Boolean>> parameters = new HashMap<>();
        StringBuilder baseUrl = new StringBuilder(environmentMapper(environment, server));
        ApiHelper.appendUrlWithTemplateParameters(baseUrl, parameters);
        return baseUrl.toString();
    }

    /**
     * Get base URI by current environment.
     * @return Processed base URI
     */
    public String getBaseUri() {
        return getBaseUri(Server.SEMGREP);
    }


    /**
     * Get base URI by current environment.
     * 
     * @param server string for which to get the base URI
     * @return Processed base URI
     */
    public String getBaseUri(String server) {
        return getBaseUri(Server.fromString(server));
    }


    /**
     * Base URLs by environment and server aliases.
     * @param environment Environment for which to get the base URI
     * @param server Server for which to get the base URI
     * @return base URL
     */
    private static String environmentMapper(Environment environment, Server server) {
        if (environment.equals(Environment.PRODUCTION)) {
            if (server.equals(Server.SEMGREP)) {
                return "https://semgrep.dev";
            }
        }
        return "https://semgrep.dev";
    }

    /**
     * Converts this SemgrepWebAppClient into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SemgrepWebAppClient [" + "environment=" + environment + ", httpClientConfig="
                + httpClientConfig + ", loggingConfig=" + loggingConfig + ", authentications="
                + authentications + "]";
    }

    /**
     * Builds a new {@link SemgrepWebAppClient.Builder} object.
     * Creates the instance with the state of the current client.
     * @return a new {@link SemgrepWebAppClient.Builder} object
     */
    public Builder newBuilder() {
        Builder builder = new Builder();
        builder.environment = getEnvironment();
        builder.httpClient = getHttpClient();
        builder.semgrepAdminJwtCredentials(getSemgrepAdminJwtModel()
                .toBuilder().build());
        builder.semgrepJwtCredentials(getSemgrepJwtModel()
                .toBuilder().build());
        builder.semgrepWebTokenCredentials(getSemgrepWebTokenModel()
                .toBuilder().build());
        builder.httpCallback = httpCallback;
        builder.httpClientConfig(() -> ((HttpClientConfiguration) httpClientConfig).newBuilder());
        builder.loggingConfig(() -> ((ApiLoggingConfiguration) loggingConfig).newBuilder());
        return builder;
    }

    /**
     * Class to build instances of {@link SemgrepWebAppClient}.
     */
    public static class Builder {

        private Environment environment = Environment.PRODUCTION;
        private HttpClient httpClient;
        private SemgrepAdminJwtModel semgrepAdminJwtModel =
                new SemgrepAdminJwtModel.Builder("").build();
        private SemgrepJwtModel semgrepJwtModel = new SemgrepJwtModel.Builder("").build();
        private SemgrepWebTokenModel semgrepWebTokenModel =
                new SemgrepWebTokenModel.Builder("").build();
        private HttpCallback httpCallback = null;
        private HttpClientConfiguration.Builder httpClientConfigBuilder =
                new HttpClientConfiguration.Builder();
        private ApiLoggingConfiguration.Builder loggingConfigBuilder = null;


        /**
         * Credentials setter for SemgrepAdminJwtCredentials.
         * @param semgrepAdminJwtModel The instance of SemgrepAdminJwtModel.
         * @return The current instance of builder.
         */
        public Builder semgrepAdminJwtCredentials(SemgrepAdminJwtModel semgrepAdminJwtModel) {
            this.semgrepAdminJwtModel = semgrepAdminJwtModel;
            return this;
        }

        /**
         * Credentials setter for SemgrepJwtCredentials.
         * @param semgrepJwtModel The instance of SemgrepJwtModel.
         * @return The current instance of builder.
         */
        public Builder semgrepJwtCredentials(SemgrepJwtModel semgrepJwtModel) {
            this.semgrepJwtModel = semgrepJwtModel;
            return this;
        }

        /**
         * Credentials setter for SemgrepWebTokenCredentials.
         * @param semgrepWebTokenModel The instance of SemgrepWebTokenModel.
         * @return The current instance of builder.
         */
        public Builder semgrepWebTokenCredentials(SemgrepWebTokenModel semgrepWebTokenModel) {
            this.semgrepWebTokenModel = semgrepWebTokenModel;
            return this;
        }

        /**
         * Current API environment.
         * @param environment The environment for client.
         * @return Builder
         */
        public Builder environment(Environment environment) {
            this.environment = environment;
            return this;
        }

        /**
         * The timeout to use for making HTTP requests.
         * @deprecated This method will be removed in a future version. Use
         *             {@link #httpClientConfig(Consumer) httpClientConfig} instead.
         * @param timeout must be greater then 0.
         * @return Builder
         */
        @Deprecated
        public Builder timeout(long timeout) {
            this.httpClientConfigBuilder.timeout(timeout);
            return this;
        }

        /**
         * Setter for the Builder of LoggingConfiguration, takes in an operation to be
         * performed on the builder instance of logging configuration.
         * @param action Consumer for the builder of LoggingConfiguration.
         * @return Builder
         */
        public Builder loggingConfig(Consumer<ApiLoggingConfiguration.Builder> action) {
            if (loggingConfigBuilder == null) {
                loggingConfigBuilder = new ApiLoggingConfiguration.Builder();
            }

            if (loggingConfigBuilder.build().getLogger() == null) {
                loggingConfigBuilder.useDefaultLogger();
            }

            action.accept(loggingConfigBuilder);
            return this;
        }

        /**
         * Setter for the Builder of LoggingConfiguration with Console Logging.
         *
         * @return Builder
         */
        public Builder loggingConfig() {
            loggingConfigBuilder = new ApiLoggingConfiguration.Builder();
            loggingConfigBuilder.useDefaultLogger();
            return this;
        }

		/**
		 * Private setter for the Builder of LoggingConfiguration, takes in an operation to be
		 * performed on the builder instance of logging configuration.
		 * 
		 * @param supplier Supplier for the builder of LoggingConfiguration.
		 * @return Builder
		 */
		private Builder loggingConfig(Supplier<ApiLoggingConfiguration.Builder> supplier) {
			loggingConfigBuilder = supplier.get();
			return this;
		}

        /**
         * HttpCallback.
         * @param httpCallback Callback to be called before and after the HTTP call.
         * @return Builder
         */
        public Builder httpCallback(HttpCallback httpCallback) {
            this.httpCallback = httpCallback;
            return this;
        }

        /**
         * Setter for the Builder of httpClientConfiguration, takes in an operation to be performed
         * on the builder instance of HTTP client configuration.
         * 
         * @param action Consumer for the builder of httpClientConfiguration.
         * @return Builder
         */
        public Builder httpClientConfig(Consumer<HttpClientConfiguration.Builder> action) {
            action.accept(httpClientConfigBuilder);
            return this;
        }

        /**
         * Private Setter for the Builder of httpClientConfiguration, takes in an operation to be performed
         * on the builder instance of HTTP client configuration.
         * 
         * @param supplier Supplier for the builder of httpClientConfiguration.
         * @return Builder
         */
        private Builder httpClientConfig(Supplier<HttpClientConfiguration.Builder> supplier) {
            httpClientConfigBuilder = supplier.get();
            return this;
        }

        /**
         * Builds a new SemgrepWebAppClient object using the set fields.
         * @return SemgrepWebAppClient
         */
        public SemgrepWebAppClient build() {
            HttpClientConfiguration httpClientConfig = httpClientConfigBuilder.build();
            ReadonlyLoggingConfiguration loggingConfig = loggingConfigBuilder != null ? loggingConfigBuilder.build() 
                    : new ApiLoggingConfiguration.Builder().build();
            httpClient = new OkClient(httpClientConfig.getConfiguration(), compatibilityFactory);

            return new SemgrepWebAppClient(environment, httpClient, httpClientConfig, loggingConfig,
                    semgrepAdminJwtModel, semgrepJwtModel, semgrepWebTokenModel, httpCallback);
        }
    }
}