/*
 * SemgrepWebAppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.semgrep.apis;

import dev.semgrep.ApiHelper;
import dev.semgrep.Server;
import dev.semgrep.exceptions.ApiException;
import dev.semgrep.http.request.HttpMethod;
import dev.semgrep.http.response.ApiResponse;
import dev.semgrep.models.ApiV1DeploymentsFindingsResponse;
import dev.semgrep.models.AutotriageVerdict2;
import dev.semgrep.models.ClickToFixPrState;
import dev.semgrep.models.Confidence8;
import dev.semgrep.models.Exposures2;
import dev.semgrep.models.IssueType2;
import dev.semgrep.models.Severities2;
import dev.semgrep.models.Status9;
import dev.semgrep.models.Transitivities2;
import dev.semgrep.models.TriageReasons2;
import io.apimatic.core.ApiCall;
import io.apimatic.core.GlobalConfiguration;
import io.apimatic.coreinterfaces.http.request.ResponseClassType;
import java.io.IOException;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionException;

/**
 * This class lists all the endpoints of the groups.
 */
public final class FindingsServiceApi extends BaseApi {

    /**
     * Initializes the controller.
     * @param globalConfig    Configurations added in client.
     */
    public FindingsServiceApi(GlobalConfiguration globalConfig) {
        super(globalConfig);
    }

    /**
     * Request the list of code, supply chain, or AI-powered scan findings in an organization,
     * paginated in pages of 100 entries and limited by the `since` timestamp. Findings are returned
     * by `relevant_since` descending (see `since` in the Query Parameters list). Examples: List
     * SAST findings with pagination, List SCA findings since timestamp, List AI-powered scan
     * findings, List findings with filters.
     * @param  deploymentSlug  Required parameter:
     * @param  issueType  Optional parameter: Example: sast
     * @param  since  Optional parameter:
     * @param  page  Optional parameter: Example: 0
     * @param  dedup  Optional parameter: Example: false
     * @param  pageSize  Optional parameter: Example: 100
     * @param  repos  Optional parameter:
     * @param  repositoryIds  Optional parameter:
     * @param  status  Optional parameter: Example:
     * @param  triageReasons  Optional parameter: Example:
     * @param  severities  Optional parameter: Example:
     * @param  ref  Optional parameter:
     * @param  policies  Optional parameter:
     * @param  rules  Optional parameter:
     * @param  categories  Optional parameter:
     * @param  confidence  Optional parameter: Example:
     * @param  autotriageVerdict  Optional parameter: Example:
     * @param  componentTags  Optional parameter:
     * @param  exposures  Optional parameter: Example:
     * @param  transitivities  Optional parameter: Example:
     * @param  isMalicious  Optional parameter:
     * @param  clickToFixPrState  Optional parameter: Example:
     * @return    Returns the ApiV1DeploymentsFindingsResponse wrapped in ApiResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public ApiResponse<ApiV1DeploymentsFindingsResponse> findingsServiceListFindings(
            final String deploymentSlug,
            final IssueType2 issueType,
            final Double since,
            final Long page,
            final Boolean dedup,
            final Long pageSize,
            final List<String> repos,
            final List<Long> repositoryIds,
            final Status9 status,
            final TriageReasons2 triageReasons,
            final Severities2 severities,
            final String ref,
            final List<String> policies,
            final List<String> rules,
            final List<String> categories,
            final Confidence8 confidence,
            final AutotriageVerdict2 autotriageVerdict,
            final List<String> componentTags,
            final Exposures2 exposures,
            final Transitivities2 transitivities,
            final Boolean isMalicious,
            final ClickToFixPrState clickToFixPrState) throws ApiException, IOException {
        return prepareFindingsServiceListFindingsRequest(deploymentSlug, issueType, since, page,
                dedup, pageSize, repos, repositoryIds, status, triageReasons, severities, ref,
                policies, rules, categories, confidence, autotriageVerdict, componentTags,
                exposures, transitivities, isMalicious, clickToFixPrState).execute();
    }

    /**
     * Request the list of code, supply chain, or AI-powered scan findings in an organization,
     * paginated in pages of 100 entries and limited by the `since` timestamp. Findings are returned
     * by `relevant_since` descending (see `since` in the Query Parameters list). Examples: List
     * SAST findings with pagination, List SCA findings since timestamp, List AI-powered scan
     * findings, List findings with filters.
     * @param  deploymentSlug  Required parameter:
     * @param  issueType  Optional parameter: Example: sast
     * @param  since  Optional parameter:
     * @param  page  Optional parameter: Example: 0
     * @param  dedup  Optional parameter: Example: false
     * @param  pageSize  Optional parameter: Example: 100
     * @param  repos  Optional parameter:
     * @param  repositoryIds  Optional parameter:
     * @param  status  Optional parameter: Example:
     * @param  triageReasons  Optional parameter: Example:
     * @param  severities  Optional parameter: Example:
     * @param  ref  Optional parameter:
     * @param  policies  Optional parameter:
     * @param  rules  Optional parameter:
     * @param  categories  Optional parameter:
     * @param  confidence  Optional parameter: Example:
     * @param  autotriageVerdict  Optional parameter: Example:
     * @param  componentTags  Optional parameter:
     * @param  exposures  Optional parameter: Example:
     * @param  transitivities  Optional parameter: Example:
     * @param  isMalicious  Optional parameter:
     * @param  clickToFixPrState  Optional parameter: Example:
     * @return    Returns the ApiV1DeploymentsFindingsResponse wrapped in ApiResponse response from the API call
     */
    public CompletableFuture<ApiResponse<ApiV1DeploymentsFindingsResponse>> findingsServiceListFindingsAsync(
            final String deploymentSlug,
            final IssueType2 issueType,
            final Double since,
            final Long page,
            final Boolean dedup,
            final Long pageSize,
            final List<String> repos,
            final List<Long> repositoryIds,
            final Status9 status,
            final TriageReasons2 triageReasons,
            final Severities2 severities,
            final String ref,
            final List<String> policies,
            final List<String> rules,
            final List<String> categories,
            final Confidence8 confidence,
            final AutotriageVerdict2 autotriageVerdict,
            final List<String> componentTags,
            final Exposures2 exposures,
            final Transitivities2 transitivities,
            final Boolean isMalicious,
            final ClickToFixPrState clickToFixPrState) {
        try {
            return prepareFindingsServiceListFindingsRequest(deploymentSlug, issueType, since, page, dedup,
            pageSize, repos, repositoryIds, status, triageReasons, severities, ref, policies, rules,
            categories, confidence, autotriageVerdict, componentTags, exposures, transitivities,
            isMalicious, clickToFixPrState).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for findingsServiceListFindings.
     */
    private ApiCall<ApiResponse<ApiV1DeploymentsFindingsResponse>, ApiException> prepareFindingsServiceListFindingsRequest(
            final String deploymentSlug,
            final IssueType2 issueType,
            final Double since,
            final Long page,
            final Boolean dedup,
            final Long pageSize,
            final List<String> repos,
            final List<Long> repositoryIds,
            final Status9 status,
            final TriageReasons2 triageReasons,
            final Severities2 severities,
            final String ref,
            final List<String> policies,
            final List<String> rules,
            final List<String> categories,
            final Confidence8 confidence,
            final AutotriageVerdict2 autotriageVerdict,
            final List<String> componentTags,
            final Exposures2 exposures,
            final Transitivities2 transitivities,
            final Boolean isMalicious,
            final ClickToFixPrState clickToFixPrState) {
        return new ApiCall.Builder<ApiResponse<ApiV1DeploymentsFindingsResponse>, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.SEMGREP.value())
                        .path("/api/v1/deployments/{deploymentSlug}/findings")
                        .queryParam(param -> param.key("issue_type")
                                .value((issueType != null) ? issueType.value() : "sast").isRequired(false))
                        .queryParam(param -> param.key("since")
                                .value(since).isRequired(false))
                        .queryParam(param -> param.key("page")
                                .value((page != null) ? page : 0L).isRequired(false))
                        .queryParam(param -> param.key("dedup")
                                .value((dedup != null) ? dedup : false).isRequired(false))
                        .queryParam(param -> param.key("page_size")
                                .value((pageSize != null) ? pageSize : 100L).isRequired(false))
                        .queryParam(param -> param.key("repos")
                                .value(repos).isRequired(false))
                        .queryParam(param -> param.key("repository_ids")
                                .value(repositoryIds).isRequired(false))
                        .queryParam(param -> param.key("status")
                                .value((status != null) ? status.value() : null).isRequired(false))
                        .queryParam(param -> param.key("triage_reasons")
                                .value((triageReasons != null) ? triageReasons.value() : null).isRequired(false))
                        .queryParam(param -> param.key("severities")
                                .value((severities != null) ? severities.value() : null).isRequired(false))
                        .queryParam(param -> param.key("ref")
                                .value(ref).isRequired(false))
                        .queryParam(param -> param.key("policies")
                                .value(policies).isRequired(false))
                        .queryParam(param -> param.key("rules")
                                .value(rules).isRequired(false))
                        .queryParam(param -> param.key("categories")
                                .value(categories).isRequired(false))
                        .queryParam(param -> param.key("confidence")
                                .value((confidence != null) ? confidence.value() : null).isRequired(false))
                        .queryParam(param -> param.key("autotriage_verdict")
                                .value((autotriageVerdict != null) ? autotriageVerdict.value() : null).isRequired(false))
                        .queryParam(param -> param.key("component_tags")
                                .value(componentTags).isRequired(false))
                        .queryParam(param -> param.key("exposures")
                                .value((exposures != null) ? exposures.value() : null).isRequired(false))
                        .queryParam(param -> param.key("transitivities")
                                .value((transitivities != null) ? transitivities.value() : null).isRequired(false))
                        .queryParam(param -> param.key("is_malicious")
                                .value(isMalicious).isRequired(false))
                        .queryParam(param -> param.key("click_to_fix_pr_state")
                                .value((clickToFixPrState != null) ? clickToFixPrState.value() : null).isRequired(false))
                        .templateParam(param -> param.key("deploymentSlug").value(deploymentSlug)
                                .shouldEncode(true))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .add("SemgrepWebToken"))
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .responseClassType(ResponseClassType.API_RESPONSE)
                        .apiResponseDeserializer(
                                response -> ApiHelper.deserialize(response, ApiV1DeploymentsFindingsResponse.class))
                        .nullify404(false)
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }
}