/*
 * SemgrepWebAppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.semgrep.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for Assistant type.
 */
public class Assistant {
    private Autofix autofix;
    private Autotriage autotriage;
    private Component component;
    private Guidance guidance;
    private RuleExplanation ruleExplanation;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public Assistant() {
    }

    /**
     * Initialization constructor.
     * @param  autofix  Autofix value for autofix.
     * @param  autotriage  Autotriage value for autotriage.
     * @param  component  Component value for component.
     * @param  guidance  Guidance value for guidance.
     * @param  ruleExplanation  RuleExplanation value for ruleExplanation.
     */
    public Assistant(
            Autofix autofix,
            Autotriage autotriage,
            Component component,
            Guidance guidance,
            RuleExplanation ruleExplanation) {
        this.autofix = autofix;
        this.autotriage = autotriage;
        this.component = component;
        this.guidance = guidance;
        this.ruleExplanation = ruleExplanation;
    }

    /**
     * Getter for Autofix.
     * Fix data generated by Semgrep Assistant
     * @return Returns the Autofix
     */
    @JsonGetter("autofix")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Autofix getAutofix() {
        return autofix;
    }

    /**
     * Setter for Autofix.
     * Fix data generated by Semgrep Assistant
     * @param autofix Value for Autofix
     */
    @JsonSetter("autofix")
    public void setAutofix(Autofix autofix) {
        this.autofix = autofix;
    }

    /**
     * Getter for Autotriage.
     * Triage recommendation generated by Semgrep Assistant
     * @return Returns the Autotriage
     */
    @JsonGetter("autotriage")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Autotriage getAutotriage() {
        return autotriage;
    }

    /**
     * Setter for Autotriage.
     * Triage recommendation generated by Semgrep Assistant
     * @param autotriage Value for Autotriage
     */
    @JsonSetter("autotriage")
    public void setAutotriage(Autotriage autotriage) {
        this.autotriage = autotriage;
    }

    /**
     * Getter for Component.
     * Semgrep Assistant's guess as for what the matched source code's purpose is
     * @return Returns the Component
     */
    @JsonGetter("component")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Component getComponent() {
        return component;
    }

    /**
     * Setter for Component.
     * Semgrep Assistant's guess as for what the matched source code's purpose is
     * @param component Value for Component
     */
    @JsonSetter("component")
    public void setComponent(Component component) {
        this.component = component;
    }

    /**
     * Getter for Guidance.
     * Remediation guidance generated by Semgrep Assistant
     * @return Returns the Guidance
     */
    @JsonGetter("guidance")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Guidance getGuidance() {
        return guidance;
    }

    /**
     * Setter for Guidance.
     * Remediation guidance generated by Semgrep Assistant
     * @param guidance Value for Guidance
     */
    @JsonSetter("guidance")
    public void setGuidance(Guidance guidance) {
        this.guidance = guidance;
    }

    /**
     * Getter for RuleExplanation.
     * AI-generated explanation of why a rule flagged this specific code
     * @return Returns the RuleExplanation
     */
    @JsonGetter("rule_explanation")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public RuleExplanation getRuleExplanation() {
        return ruleExplanation;
    }

    /**
     * Setter for RuleExplanation.
     * AI-generated explanation of why a rule flagged this specific code
     * @param ruleExplanation Value for RuleExplanation
     */
    @JsonSetter("rule_explanation")
    public void setRuleExplanation(RuleExplanation ruleExplanation) {
        this.ruleExplanation = ruleExplanation;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this Assistant into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Assistant [" + "autofix=" + autofix + ", autotriage=" + autotriage + ", component="
                + component + ", guidance=" + guidance + ", ruleExplanation=" + ruleExplanation
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link Assistant.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Assistant.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .autofix(getAutofix())
                .autotriage(getAutotriage())
                .component(getComponent())
                .guidance(getGuidance())
                .ruleExplanation(getRuleExplanation());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link Assistant}.
     */
    public static class Builder {
        private Autofix autofix;
        private Autotriage autotriage;
        private Component component;
        private Guidance guidance;
        private RuleExplanation ruleExplanation;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for autofix.
         * @param  autofix  Autofix value for autofix.
         * @return Builder
         */
        public Builder autofix(Autofix autofix) {
            this.autofix = autofix;
            return this;
        }

        /**
         * Setter for autotriage.
         * @param  autotriage  Autotriage value for autotriage.
         * @return Builder
         */
        public Builder autotriage(Autotriage autotriage) {
            this.autotriage = autotriage;
            return this;
        }

        /**
         * Setter for component.
         * @param  component  Component value for component.
         * @return Builder
         */
        public Builder component(Component component) {
            this.component = component;
            return this;
        }

        /**
         * Setter for guidance.
         * @param  guidance  Guidance value for guidance.
         * @return Builder
         */
        public Builder guidance(Guidance guidance) {
            this.guidance = guidance;
            return this;
        }

        /**
         * Setter for ruleExplanation.
         * @param  ruleExplanation  RuleExplanation value for ruleExplanation.
         * @return Builder
         */
        public Builder ruleExplanation(RuleExplanation ruleExplanation) {
            this.ruleExplanation = ruleExplanation;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link Assistant} object using the set fields.
         * @return {@link Assistant}
         */
        public Assistant build() {
            Assistant model =
                    new Assistant(autofix, autotriage, component, guidance, ruleExplanation);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
