/*
 * SemgrepWebAppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.semgrep.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for BulkTriageResponse type.
 */
public class BulkTriageResponse {
    private long numTriaged;
    private List<Long> triagedIssues;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public BulkTriageResponse() {
    }

    /**
     * Initialization constructor.
     * @param  numTriaged  long value for numTriaged.
     * @param  triagedIssues  List of Long value for triagedIssues.
     */
    public BulkTriageResponse(
            long numTriaged,
            List<Long> triagedIssues) {
        this.numTriaged = numTriaged;
        this.triagedIssues = triagedIssues;
    }

    /**
     * Getter for NumTriaged.
     * Number of items updated
     * @return Returns the long
     */
    @JsonGetter("num_triaged")
    public long getNumTriaged() {
        return numTriaged;
    }

    /**
     * Setter for NumTriaged.
     * Number of items updated
     * @param numTriaged Value for long
     */
    @JsonSetter("num_triaged")
    public void setNumTriaged(long numTriaged) {
        this.numTriaged = numTriaged;
    }

    /**
     * Getter for TriagedIssues.
     * List of triaged issue IDs
     * @return Returns the List of Long
     */
    @JsonGetter("triaged_issues")
    public List<Long> getTriagedIssues() {
        return triagedIssues;
    }

    /**
     * Setter for TriagedIssues.
     * List of triaged issue IDs
     * @param triagedIssues Value for List of Long
     */
    @JsonSetter("triaged_issues")
    public void setTriagedIssues(List<Long> triagedIssues) {
        this.triagedIssues = triagedIssues;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this BulkTriageResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "BulkTriageResponse [" + "numTriaged=" + numTriaged + ", triagedIssues="
                + triagedIssues + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link BulkTriageResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link BulkTriageResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(numTriaged, triagedIssues);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link BulkTriageResponse}.
     */
    public static class Builder {
        private long numTriaged;
        private List<Long> triagedIssues;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  numTriaged  long value for numTriaged.
         * @param  triagedIssues  List of Long value for triagedIssues.
         */
        public Builder(long numTriaged, List<Long> triagedIssues) {
            this.numTriaged = numTriaged;
            this.triagedIssues = triagedIssues;
        }

        /**
         * Setter for numTriaged.
         * @param  numTriaged  long value for numTriaged.
         * @return Builder
         */
        public Builder numTriaged(long numTriaged) {
            this.numTriaged = numTriaged;
            return this;
        }

        /**
         * Setter for triagedIssues.
         * @param  triagedIssues  List of Long value for triagedIssues.
         * @return Builder
         */
        public Builder triagedIssues(List<Long> triagedIssues) {
            this.triagedIssues = triagedIssues;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link BulkTriageResponse} object using the set fields.
         * @return {@link BulkTriageResponse}
         */
        public BulkTriageResponse build() {
            BulkTriageResponse model =
                    new BulkTriageResponse(numTriaged, triagedIssues);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
