/*
 * SemgrepWebAppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.semgrep.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * Confidence to be used.
 */
public enum Confidence {
    CONFIDENCE_HIGH,

    CONFIDENCE_MEDIUM,

    CONFIDENCE_LOW;

    private static TreeMap<String, Confidence> valueMap = new TreeMap<>();
    private String value;

    static {
        CONFIDENCE_HIGH.value = "CONFIDENCE_HIGH";
        CONFIDENCE_MEDIUM.value = "CONFIDENCE_MEDIUM";
        CONFIDENCE_LOW.value = "CONFIDENCE_LOW";

        valueMap.put("CONFIDENCE_HIGH", CONFIDENCE_HIGH);
        valueMap.put("CONFIDENCE_MEDIUM", CONFIDENCE_MEDIUM);
        valueMap.put("CONFIDENCE_LOW", CONFIDENCE_LOW);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static Confidence constructFromString(String toConvert) throws IOException {
        Confidence enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static Confidence fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of Confidence values to list of string values.
     * @param toConvert The list of Confidence values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<Confidence> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (Confidence enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 