/*
 * SemgrepWebAppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.semgrep.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for CreateTicketRequest type.
 */
public class CreateTicketRequest {
    private AutotriageVerdict autotriageVerdict;
    private List<String> categories;
    private List<String> componentTags;
    private Confidence3 confidence;
    private List<String> dependencies;
    private String deploymentSlug;
    private EpssProbability epssProbability;
    private Exposures exposures;
    private Boolean groupIssues;
    private Boolean includeHistorical;
    private List<String> issueIds;
    private IssueType1 issueType;
    private String jiraProjectId;
    private Long limit;
    private List<String> policies;
    private PolicyMode1 policyMode;
    private Boolean proOnly;
    private List<String> projectTags;
    private String ref;
    private List<String> repos;
    private RepositoryVisibility repositoryVisibility;
    private List<String> rules;
    private List<String> ruleset;
    private List<String> secretTypes;
    private Severities severities;
    private String since;
    private Status1 status;
    private Transitivities transitivities;
    private TriageReasons triageReasons;
    private ValidationState validationState;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public CreateTicketRequest() {
        groupIssues = true;
        limit = 20L;
    }

    /**
     * Initialization constructor.
     * @param  deploymentSlug  String value for deploymentSlug.
     * @param  issueType  IssueType1 value for issueType.
     * @param  autotriageVerdict  AutotriageVerdict value for autotriageVerdict.
     * @param  categories  List of String value for categories.
     * @param  componentTags  List of String value for componentTags.
     * @param  confidence  Confidence3 value for confidence.
     * @param  dependencies  List of String value for dependencies.
     * @param  epssProbability  EpssProbability value for epssProbability.
     * @param  exposures  Exposures value for exposures.
     * @param  groupIssues  Boolean value for groupIssues.
     * @param  includeHistorical  Boolean value for includeHistorical.
     * @param  issueIds  List of String value for issueIds.
     * @param  jiraProjectId  String value for jiraProjectId.
     * @param  limit  Long value for limit.
     * @param  policies  List of String value for policies.
     * @param  policyMode  PolicyMode1 value for policyMode.
     * @param  proOnly  Boolean value for proOnly.
     * @param  projectTags  List of String value for projectTags.
     * @param  ref  String value for ref.
     * @param  repos  List of String value for repos.
     * @param  repositoryVisibility  RepositoryVisibility value for repositoryVisibility.
     * @param  rules  List of String value for rules.
     * @param  ruleset  List of String value for ruleset.
     * @param  secretTypes  List of String value for secretTypes.
     * @param  severities  Severities value for severities.
     * @param  since  String value for since.
     * @param  status  Status1 value for status.
     * @param  transitivities  Transitivities value for transitivities.
     * @param  triageReasons  TriageReasons value for triageReasons.
     * @param  validationState  ValidationState value for validationState.
     */
    public CreateTicketRequest(
            String deploymentSlug,
            IssueType1 issueType,
            AutotriageVerdict autotriageVerdict,
            List<String> categories,
            List<String> componentTags,
            Confidence3 confidence,
            List<String> dependencies,
            EpssProbability epssProbability,
            Exposures exposures,
            Boolean groupIssues,
            Boolean includeHistorical,
            List<String> issueIds,
            String jiraProjectId,
            Long limit,
            List<String> policies,
            PolicyMode1 policyMode,
            Boolean proOnly,
            List<String> projectTags,
            String ref,
            List<String> repos,
            RepositoryVisibility repositoryVisibility,
            List<String> rules,
            List<String> ruleset,
            List<String> secretTypes,
            Severities severities,
            String since,
            Status1 status,
            Transitivities transitivities,
            TriageReasons triageReasons,
            ValidationState validationState) {
        this.autotriageVerdict = autotriageVerdict;
        this.categories = categories;
        this.componentTags = componentTags;
        this.confidence = confidence;
        this.dependencies = dependencies;
        this.deploymentSlug = deploymentSlug;
        this.epssProbability = epssProbability;
        this.exposures = exposures;
        this.groupIssues = groupIssues;
        this.includeHistorical = includeHistorical;
        this.issueIds = issueIds;
        this.issueType = issueType;
        this.jiraProjectId = jiraProjectId;
        this.limit = limit;
        this.policies = policies;
        this.policyMode = policyMode;
        this.proOnly = proOnly;
        this.projectTags = projectTags;
        this.ref = ref;
        this.repos = repos;
        this.repositoryVisibility = repositoryVisibility;
        this.rules = rules;
        this.ruleset = ruleset;
        this.secretTypes = secretTypes;
        this.severities = severities;
        this.since = since;
        this.status = status;
        this.transitivities = transitivities;
        this.triageReasons = triageReasons;
        this.validationState = validationState;
    }

    /**
     * Getter for AutotriageVerdict.
     * The autotriage verdict to filter by
     * @return Returns the AutotriageVerdict
     */
    @JsonGetter("autotriage_verdict")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public AutotriageVerdict getAutotriageVerdict() {
        return autotriageVerdict;
    }

    /**
     * Setter for AutotriageVerdict.
     * The autotriage verdict to filter by
     * @param autotriageVerdict Value for AutotriageVerdict
     */
    @JsonSetter("autotriage_verdict")
    public void setAutotriageVerdict(AutotriageVerdict autotriageVerdict) {
        this.autotriageVerdict = autotriageVerdict;
    }

    /**
     * Getter for Categories.
     * List of categories to filter by
     * @return Returns the List of String
     */
    @JsonGetter("categories")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getCategories() {
        return categories;
    }

    /**
     * Setter for Categories.
     * List of categories to filter by
     * @param categories Value for List of String
     */
    @JsonSetter("categories")
    public void setCategories(List<String> categories) {
        this.categories = categories;
    }

    /**
     * Getter for ComponentTags.
     * List of component tags to filter by
     * @return Returns the List of String
     */
    @JsonGetter("component_tags")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getComponentTags() {
        return componentTags;
    }

    /**
     * Setter for ComponentTags.
     * List of component tags to filter by
     * @param componentTags Value for List of String
     */
    @JsonSetter("component_tags")
    public void setComponentTags(List<String> componentTags) {
        this.componentTags = componentTags;
    }

    /**
     * Getter for Confidence.
     * List of confidence levels to filter by
     * @return Returns the Confidence3
     */
    @JsonGetter("confidence")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Confidence3 getConfidence() {
        return confidence;
    }

    /**
     * Setter for Confidence.
     * List of confidence levels to filter by
     * @param confidence Value for Confidence3
     */
    @JsonSetter("confidence")
    public void setConfidence(Confidence3 confidence) {
        this.confidence = confidence;
    }

    /**
     * Getter for Dependencies.
     * Filter by dependency name. Only applies for sca findings.
     * @return Returns the List of String
     */
    @JsonGetter("dependencies")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getDependencies() {
        return dependencies;
    }

    /**
     * Setter for Dependencies.
     * Filter by dependency name. Only applies for sca findings.
     * @param dependencies Value for List of String
     */
    @JsonSetter("dependencies")
    public void setDependencies(List<String> dependencies) {
        this.dependencies = dependencies;
    }

    /**
     * Getter for DeploymentSlug.
     * Deployment slug. Can be found at `/deployments`, or in your Settings in the web UI.
     * @return Returns the String
     */
    @JsonGetter("deploymentSlug")
    public String getDeploymentSlug() {
        return deploymentSlug;
    }

    /**
     * Setter for DeploymentSlug.
     * Deployment slug. Can be found at `/deployments`, or in your Settings in the web UI.
     * @param deploymentSlug Value for String
     */
    @JsonSetter("deploymentSlug")
    public void setDeploymentSlug(String deploymentSlug) {
        this.deploymentSlug = deploymentSlug;
    }

    /**
     * Getter for EpssProbability.
     * Filter by EPSS probability (likelihood of exploit). Only applies for sca findings.
     * @return Returns the EpssProbability
     */
    @JsonGetter("epss_probability")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public EpssProbability getEpssProbability() {
        return epssProbability;
    }

    /**
     * Setter for EpssProbability.
     * Filter by EPSS probability (likelihood of exploit). Only applies for sca findings.
     * @param epssProbability Value for EpssProbability
     */
    @JsonSetter("epss_probability")
    public void setEpssProbability(EpssProbability epssProbability) {
        this.epssProbability = epssProbability;
    }

    /**
     * Getter for Exposures.
     * Filter by exposure (reachability type). Only applies for sca findings. Reachability is the
     * ability of an attacker to access a vulnerability in a system.
     * @return Returns the Exposures
     */
    @JsonGetter("exposures")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Exposures getExposures() {
        return exposures;
    }

    /**
     * Setter for Exposures.
     * Filter by exposure (reachability type). Only applies for sca findings. Reachability is the
     * ability of an attacker to access a vulnerability in a system.
     * @param exposures Value for Exposures
     */
    @JsonSetter("exposures")
    public void setExposures(Exposures exposures) {
        this.exposures = exposures;
    }

    /**
     * Getter for GroupIssues.
     * Whether or not to group findings from the same rule and repository into a single ticket.
     * Defaults to true.
     * @return Returns the Boolean
     */
    @JsonGetter("group_issues")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getGroupIssues() {
        return groupIssues;
    }

    /**
     * Setter for GroupIssues.
     * Whether or not to group findings from the same rule and repository into a single ticket.
     * Defaults to true.
     * @param groupIssues Value for Boolean
     */
    @JsonSetter("group_issues")
    public void setGroupIssues(Boolean groupIssues) {
        this.groupIssues = groupIssues;
    }

    /**
     * Getter for IncludeHistorical.
     * Whether to include historical findings. Only applies for secrets findings. Defaults to true.
     * @return Returns the Boolean
     */
    @JsonGetter("include_historical")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getIncludeHistorical() {
        return includeHistorical;
    }

    /**
     * Setter for IncludeHistorical.
     * Whether to include historical findings. Only applies for secrets findings. Defaults to true.
     * @param includeHistorical Value for Boolean
     */
    @JsonSetter("include_historical")
    public void setIncludeHistorical(Boolean includeHistorical) {
        this.includeHistorical = includeHistorical;
    }

    /**
     * Getter for IssueIds.
     * An array of issue IDs to act on. If this is not provided, an issue filter should be provided.
     * @return Returns the List of String
     */
    @JsonGetter("issue_ids")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getIssueIds() {
        return issueIds;
    }

    /**
     * Setter for IssueIds.
     * An array of issue IDs to act on. If this is not provided, an issue filter should be provided.
     * @param issueIds Value for List of String
     */
    @JsonSetter("issue_ids")
    public void setIssueIds(List<String> issueIds) {
        this.issueIds = issueIds;
    }

    /**
     * Getter for IssueType.
     * Type of findings to create tickets for.
     * @return Returns the IssueType1
     */
    @JsonGetter("issue_type")
    public IssueType1 getIssueType() {
        return issueType;
    }

    /**
     * Setter for IssueType.
     * Type of findings to create tickets for.
     * @param issueType Value for IssueType1
     */
    @JsonSetter("issue_type")
    public void setIssueType(IssueType1 issueType) {
        this.issueType = issueType;
    }

    /**
     * Getter for JiraProjectId.
     * Optional numeric Jira project ID to associate with the created tickets. If not specified,
     * defaults to the project configured in your integration settings. You can fetch this ID using
     * the Jira API.
     * @return Returns the String
     */
    @JsonGetter("jira_project_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getJiraProjectId() {
        return jiraProjectId;
    }

    /**
     * Setter for JiraProjectId.
     * Optional numeric Jira project ID to associate with the created tickets. If not specified,
     * defaults to the project configured in your integration settings. You can fetch this ID using
     * the Jira API.
     * @param jiraProjectId Value for String
     */
    @JsonSetter("jira_project_id")
    public void setJiraProjectId(String jiraProjectId) {
        this.jiraProjectId = jiraProjectId;
    }

    /**
     * Getter for Limit.
     * Max number of tickets to create. Must be an integer between 1 and 20. Defaults to 20
     * @return Returns the Long
     */
    @JsonGetter("limit")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Long getLimit() {
        return limit;
    }

    /**
     * Setter for Limit.
     * Max number of tickets to create. Must be an integer between 1 and 20. Defaults to 20
     * @param limit Value for Long
     */
    @JsonSetter("limit")
    public void setLimit(Long limit) {
        this.limit = limit;
    }

    /**
     * Getter for Policies.
     * List of policy modes to filter by
     * @return Returns the List of String
     */
    @JsonGetter("policies")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getPolicies() {
        return policies;
    }

    /**
     * Setter for Policies.
     * List of policy modes to filter by
     * @param policies Value for List of String
     */
    @JsonSetter("policies")
    public void setPolicies(List<String> policies) {
        this.policies = policies;
    }

    /**
     * Getter for PolicyMode.
     * List of policy modes to filter by
     * @return Returns the PolicyMode1
     */
    @JsonGetter("policy_mode")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public PolicyMode1 getPolicyMode() {
        return policyMode;
    }

    /**
     * Setter for PolicyMode.
     * List of policy modes to filter by
     * @param policyMode Value for PolicyMode1
     */
    @JsonSetter("policy_mode")
    public void setPolicyMode(PolicyMode1 policyMode) {
        this.policyMode = policyMode;
    }

    /**
     * Getter for ProOnly.
     * Filter by whether a finding is only available with Semgrep Pro features. Only applies for
     * sast findings.
     * @return Returns the Boolean
     */
    @JsonGetter("pro_only")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getProOnly() {
        return proOnly;
    }

    /**
     * Setter for ProOnly.
     * Filter by whether a finding is only available with Semgrep Pro features. Only applies for
     * sast findings.
     * @param proOnly Value for Boolean
     */
    @JsonSetter("pro_only")
    public void setProOnly(Boolean proOnly) {
        this.proOnly = proOnly;
    }

    /**
     * Getter for ProjectTags.
     * List of project tags to filter by
     * @return Returns the List of String
     */
    @JsonGetter("project_tags")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getProjectTags() {
        return projectTags;
    }

    /**
     * Setter for ProjectTags.
     * List of project tags to filter by
     * @param projectTags Value for List of String
     */
    @JsonSetter("project_tags")
    public void setProjectTags(List<String> projectTags) {
        this.projectTags = projectTags;
    }

    /**
     * Getter for Ref.
     * Branch reference to filter by
     * @return Returns the String
     */
    @JsonGetter("ref")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getRef() {
        return ref;
    }

    /**
     * Setter for Ref.
     * Branch reference to filter by
     * @param ref Value for String
     */
    @JsonSetter("ref")
    public void setRef(String ref) {
        this.ref = ref;
    }

    /**
     * Getter for Repos.
     * List of repository names to filter by
     * @return Returns the List of String
     */
    @JsonGetter("repos")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getRepos() {
        return repos;
    }

    /**
     * Setter for Repos.
     * List of repository names to filter by
     * @param repos Value for List of String
     */
    @JsonSetter("repos")
    public void setRepos(List<String> repos) {
        this.repos = repos;
    }

    /**
     * Getter for RepositoryVisibility.
     * Filter by repository visibility. Only applies for secrets findings.
     * @return Returns the RepositoryVisibility
     */
    @JsonGetter("repository_visibility")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public RepositoryVisibility getRepositoryVisibility() {
        return repositoryVisibility;
    }

    /**
     * Setter for RepositoryVisibility.
     * Filter by repository visibility. Only applies for secrets findings.
     * @param repositoryVisibility Value for RepositoryVisibility
     */
    @JsonSetter("repository_visibility")
    public void setRepositoryVisibility(RepositoryVisibility repositoryVisibility) {
        this.repositoryVisibility = repositoryVisibility;
    }

    /**
     * Getter for Rules.
     * List of rule names to filter by
     * @return Returns the List of String
     */
    @JsonGetter("rules")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getRules() {
        return rules;
    }

    /**
     * Setter for Rules.
     * List of rule names to filter by
     * @param rules Value for List of String
     */
    @JsonSetter("rules")
    public void setRules(List<String> rules) {
        this.rules = rules;
    }

    /**
     * Getter for Ruleset.
     * List of Semgrep Registry rulesets to filter by
     * @return Returns the List of String
     */
    @JsonGetter("ruleset")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getRuleset() {
        return ruleset;
    }

    /**
     * Setter for Ruleset.
     * List of Semgrep Registry rulesets to filter by
     * @param ruleset Value for List of String
     */
    @JsonSetter("ruleset")
    public void setRuleset(List<String> ruleset) {
        this.ruleset = ruleset;
    }

    /**
     * Getter for SecretTypes.
     * Filter by type of secret (typically provider-related). Only applies for secrets findings.
     * @return Returns the List of String
     */
    @JsonGetter("secret_types")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getSecretTypes() {
        return secretTypes;
    }

    /**
     * Setter for SecretTypes.
     * Filter by type of secret (typically provider-related). Only applies for secrets findings.
     * @param secretTypes Value for List of String
     */
    @JsonSetter("secret_types")
    public void setSecretTypes(List<String> secretTypes) {
        this.secretTypes = secretTypes;
    }

    /**
     * Getter for Severities.
     * List of severities to filter by
     * @return Returns the Severities
     */
    @JsonGetter("severities")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Severities getSeverities() {
        return severities;
    }

    /**
     * Setter for Severities.
     * List of severities to filter by
     * @param severities Value for Severities
     */
    @JsonSetter("severities")
    public void setSeverities(Severities severities) {
        this.severities = severities;
    }

    /**
     * Getter for Since.
     * Epoch timestamp in seconds. Filters using the relevant_since field: the timestamp when this
     * finding was detected by Semgrep (the first time, or when reintroduced).
     * @return Returns the String
     */
    @JsonGetter("since")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getSince() {
        return since;
    }

    /**
     * Setter for Since.
     * Epoch timestamp in seconds. Filters using the relevant_since field: the timestamp when this
     * finding was detected by Semgrep (the first time, or when reintroduced).
     * @param since Value for String
     */
    @JsonSetter("since")
    public void setSince(String since) {
        this.since = since;
    }

    /**
     * Getter for Status.
     * The status to filter by
     * @return Returns the Status1
     */
    @JsonGetter("status")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Status1 getStatus() {
        return status;
    }

    /**
     * Setter for Status.
     * The status to filter by
     * @param status Value for Status1
     */
    @JsonSetter("status")
    public void setStatus(Status1 status) {
        this.status = status;
    }

    /**
     * Getter for Transitivities.
     * Filter by transitivity of a dependency. Only applies for sca findings.
     * @return Returns the Transitivities
     */
    @JsonGetter("transitivities")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Transitivities getTransitivities() {
        return transitivities;
    }

    /**
     * Setter for Transitivities.
     * Filter by transitivity of a dependency. Only applies for sca findings.
     * @param transitivities Value for Transitivities
     */
    @JsonSetter("transitivities")
    public void setTransitivities(Transitivities transitivities) {
        this.transitivities = transitivities;
    }

    /**
     * Getter for TriageReasons.
     * List of triage reasons to filter by
     * @return Returns the TriageReasons
     */
    @JsonGetter("triage_reasons")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public TriageReasons getTriageReasons() {
        return triageReasons;
    }

    /**
     * Setter for TriageReasons.
     * List of triage reasons to filter by
     * @param triageReasons Value for TriageReasons
     */
    @JsonSetter("triage_reasons")
    public void setTriageReasons(TriageReasons triageReasons) {
        this.triageReasons = triageReasons;
    }

    /**
     * Getter for ValidationState.
     * Filter by whether a secret could be validated. Only applies for secrets findings.
     * @return Returns the ValidationState
     */
    @JsonGetter("validation_state")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ValidationState getValidationState() {
        return validationState;
    }

    /**
     * Setter for ValidationState.
     * Filter by whether a secret could be validated. Only applies for secrets findings.
     * @param validationState Value for ValidationState
     */
    @JsonSetter("validation_state")
    public void setValidationState(ValidationState validationState) {
        this.validationState = validationState;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this CreateTicketRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "CreateTicketRequest [" + "deploymentSlug=" + deploymentSlug + ", issueType="
                + issueType + ", autotriageVerdict=" + autotriageVerdict + ", categories="
                + categories + ", componentTags=" + componentTags + ", confidence=" + confidence
                + ", dependencies=" + dependencies + ", epssProbability=" + epssProbability
                + ", exposures=" + exposures + ", groupIssues=" + groupIssues
                + ", includeHistorical=" + includeHistorical + ", issueIds=" + issueIds
                + ", jiraProjectId=" + jiraProjectId + ", limit=" + limit + ", policies=" + policies
                + ", policyMode=" + policyMode + ", proOnly=" + proOnly + ", projectTags="
                + projectTags + ", ref=" + ref + ", repos=" + repos + ", repositoryVisibility="
                + repositoryVisibility + ", rules=" + rules + ", ruleset=" + ruleset
                + ", secretTypes=" + secretTypes + ", severities=" + severities + ", since=" + since
                + ", status=" + status + ", transitivities=" + transitivities + ", triageReasons="
                + triageReasons + ", validationState=" + validationState + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link CreateTicketRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link CreateTicketRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(deploymentSlug, issueType)
                .autotriageVerdict(getAutotriageVerdict())
                .categories(getCategories())
                .componentTags(getComponentTags())
                .confidence(getConfidence())
                .dependencies(getDependencies())
                .epssProbability(getEpssProbability())
                .exposures(getExposures())
                .groupIssues(getGroupIssues())
                .includeHistorical(getIncludeHistorical())
                .issueIds(getIssueIds())
                .jiraProjectId(getJiraProjectId())
                .limit(getLimit())
                .policies(getPolicies())
                .policyMode(getPolicyMode())
                .proOnly(getProOnly())
                .projectTags(getProjectTags())
                .ref(getRef())
                .repos(getRepos())
                .repositoryVisibility(getRepositoryVisibility())
                .rules(getRules())
                .ruleset(getRuleset())
                .secretTypes(getSecretTypes())
                .severities(getSeverities())
                .since(getSince())
                .status(getStatus())
                .transitivities(getTransitivities())
                .triageReasons(getTriageReasons())
                .validationState(getValidationState());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link CreateTicketRequest}.
     */
    public static class Builder {
        private String deploymentSlug;
        private IssueType1 issueType;
        private AutotriageVerdict autotriageVerdict;
        private List<String> categories;
        private List<String> componentTags;
        private Confidence3 confidence;
        private List<String> dependencies;
        private EpssProbability epssProbability;
        private Exposures exposures;
        private Boolean groupIssues = true;
        private Boolean includeHistorical;
        private List<String> issueIds;
        private String jiraProjectId;
        private Long limit = 20L;
        private List<String> policies;
        private PolicyMode1 policyMode;
        private Boolean proOnly;
        private List<String> projectTags;
        private String ref;
        private List<String> repos;
        private RepositoryVisibility repositoryVisibility;
        private List<String> rules;
        private List<String> ruleset;
        private List<String> secretTypes;
        private Severities severities;
        private String since;
        private Status1 status;
        private Transitivities transitivities;
        private TriageReasons triageReasons;
        private ValidationState validationState;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  deploymentSlug  String value for deploymentSlug.
         * @param  issueType  IssueType1 value for issueType.
         */
        public Builder(String deploymentSlug, IssueType1 issueType) {
            this.deploymentSlug = deploymentSlug;
            this.issueType = issueType;
        }

        /**
         * Setter for deploymentSlug.
         * @param  deploymentSlug  String value for deploymentSlug.
         * @return Builder
         */
        public Builder deploymentSlug(String deploymentSlug) {
            this.deploymentSlug = deploymentSlug;
            return this;
        }

        /**
         * Setter for issueType.
         * @param  issueType  IssueType1 value for issueType.
         * @return Builder
         */
        public Builder issueType(IssueType1 issueType) {
            this.issueType = issueType;
            return this;
        }

        /**
         * Setter for autotriageVerdict.
         * @param  autotriageVerdict  AutotriageVerdict value for autotriageVerdict.
         * @return Builder
         */
        public Builder autotriageVerdict(AutotriageVerdict autotriageVerdict) {
            this.autotriageVerdict = autotriageVerdict;
            return this;
        }

        /**
         * Setter for categories.
         * @param  categories  List of String value for categories.
         * @return Builder
         */
        public Builder categories(List<String> categories) {
            this.categories = categories;
            return this;
        }

        /**
         * Setter for componentTags.
         * @param  componentTags  List of String value for componentTags.
         * @return Builder
         */
        public Builder componentTags(List<String> componentTags) {
            this.componentTags = componentTags;
            return this;
        }

        /**
         * Setter for confidence.
         * @param  confidence  Confidence3 value for confidence.
         * @return Builder
         */
        public Builder confidence(Confidence3 confidence) {
            this.confidence = confidence;
            return this;
        }

        /**
         * Setter for dependencies.
         * @param  dependencies  List of String value for dependencies.
         * @return Builder
         */
        public Builder dependencies(List<String> dependencies) {
            this.dependencies = dependencies;
            return this;
        }

        /**
         * Setter for epssProbability.
         * @param  epssProbability  EpssProbability value for epssProbability.
         * @return Builder
         */
        public Builder epssProbability(EpssProbability epssProbability) {
            this.epssProbability = epssProbability;
            return this;
        }

        /**
         * Setter for exposures.
         * @param  exposures  Exposures value for exposures.
         * @return Builder
         */
        public Builder exposures(Exposures exposures) {
            this.exposures = exposures;
            return this;
        }

        /**
         * Setter for groupIssues.
         * @param  groupIssues  Boolean value for groupIssues.
         * @return Builder
         */
        public Builder groupIssues(Boolean groupIssues) {
            this.groupIssues = groupIssues;
            return this;
        }

        /**
         * Setter for includeHistorical.
         * @param  includeHistorical  Boolean value for includeHistorical.
         * @return Builder
         */
        public Builder includeHistorical(Boolean includeHistorical) {
            this.includeHistorical = includeHistorical;
            return this;
        }

        /**
         * Setter for issueIds.
         * @param  issueIds  List of String value for issueIds.
         * @return Builder
         */
        public Builder issueIds(List<String> issueIds) {
            this.issueIds = issueIds;
            return this;
        }

        /**
         * Setter for jiraProjectId.
         * @param  jiraProjectId  String value for jiraProjectId.
         * @return Builder
         */
        public Builder jiraProjectId(String jiraProjectId) {
            this.jiraProjectId = jiraProjectId;
            return this;
        }

        /**
         * Setter for limit.
         * @param  limit  Long value for limit.
         * @return Builder
         */
        public Builder limit(Long limit) {
            this.limit = limit;
            return this;
        }

        /**
         * Setter for policies.
         * @param  policies  List of String value for policies.
         * @return Builder
         */
        public Builder policies(List<String> policies) {
            this.policies = policies;
            return this;
        }

        /**
         * Setter for policyMode.
         * @param  policyMode  PolicyMode1 value for policyMode.
         * @return Builder
         */
        public Builder policyMode(PolicyMode1 policyMode) {
            this.policyMode = policyMode;
            return this;
        }

        /**
         * Setter for proOnly.
         * @param  proOnly  Boolean value for proOnly.
         * @return Builder
         */
        public Builder proOnly(Boolean proOnly) {
            this.proOnly = proOnly;
            return this;
        }

        /**
         * Setter for projectTags.
         * @param  projectTags  List of String value for projectTags.
         * @return Builder
         */
        public Builder projectTags(List<String> projectTags) {
            this.projectTags = projectTags;
            return this;
        }

        /**
         * Setter for ref.
         * @param  ref  String value for ref.
         * @return Builder
         */
        public Builder ref(String ref) {
            this.ref = ref;
            return this;
        }

        /**
         * Setter for repos.
         * @param  repos  List of String value for repos.
         * @return Builder
         */
        public Builder repos(List<String> repos) {
            this.repos = repos;
            return this;
        }

        /**
         * Setter for repositoryVisibility.
         * @param  repositoryVisibility  RepositoryVisibility value for repositoryVisibility.
         * @return Builder
         */
        public Builder repositoryVisibility(RepositoryVisibility repositoryVisibility) {
            this.repositoryVisibility = repositoryVisibility;
            return this;
        }

        /**
         * Setter for rules.
         * @param  rules  List of String value for rules.
         * @return Builder
         */
        public Builder rules(List<String> rules) {
            this.rules = rules;
            return this;
        }

        /**
         * Setter for ruleset.
         * @param  ruleset  List of String value for ruleset.
         * @return Builder
         */
        public Builder ruleset(List<String> ruleset) {
            this.ruleset = ruleset;
            return this;
        }

        /**
         * Setter for secretTypes.
         * @param  secretTypes  List of String value for secretTypes.
         * @return Builder
         */
        public Builder secretTypes(List<String> secretTypes) {
            this.secretTypes = secretTypes;
            return this;
        }

        /**
         * Setter for severities.
         * @param  severities  Severities value for severities.
         * @return Builder
         */
        public Builder severities(Severities severities) {
            this.severities = severities;
            return this;
        }

        /**
         * Setter for since.
         * @param  since  String value for since.
         * @return Builder
         */
        public Builder since(String since) {
            this.since = since;
            return this;
        }

        /**
         * Setter for status.
         * @param  status  Status1 value for status.
         * @return Builder
         */
        public Builder status(Status1 status) {
            this.status = status;
            return this;
        }

        /**
         * Setter for transitivities.
         * @param  transitivities  Transitivities value for transitivities.
         * @return Builder
         */
        public Builder transitivities(Transitivities transitivities) {
            this.transitivities = transitivities;
            return this;
        }

        /**
         * Setter for triageReasons.
         * @param  triageReasons  TriageReasons value for triageReasons.
         * @return Builder
         */
        public Builder triageReasons(TriageReasons triageReasons) {
            this.triageReasons = triageReasons;
            return this;
        }

        /**
         * Setter for validationState.
         * @param  validationState  ValidationState value for validationState.
         * @return Builder
         */
        public Builder validationState(ValidationState validationState) {
            this.validationState = validationState;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link CreateTicketRequest} object using the set fields.
         * @return {@link CreateTicketRequest}
         */
        public CreateTicketRequest build() {
            CreateTicketRequest model =
                    new CreateTicketRequest(deploymentSlug, issueType, autotriageVerdict,
                            categories, componentTags, confidence, dependencies, epssProbability,
                            exposures, groupIssues, includeHistorical, issueIds, jiraProjectId,
                            limit, policies, policyMode, proOnly, projectTags, ref, repos,
                            repositoryVisibility, rules, ruleset, secretTypes, severities, since,
                            status, transitivities, triageReasons, validationState);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
