/*
 * SemgrepWebAppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.semgrep.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for Deployment type.
 */
public class Deployment {
    private EndpointReference findings;
    private long id;
    private String name;
    private String slug;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public Deployment() {
    }

    /**
     * Initialization constructor.
     * @param  id  long value for id.
     * @param  name  String value for name.
     * @param  slug  String value for slug.
     * @param  findings  EndpointReference value for findings.
     */
    public Deployment(
            long id,
            String name,
            String slug,
            EndpointReference findings) {
        this.findings = findings;
        this.id = id;
        this.name = name;
        this.slug = slug;
    }

    /**
     * Getter for Findings.
     * @return Returns the EndpointReference
     */
    @JsonGetter("findings")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public EndpointReference getFindings() {
        return findings;
    }

    /**
     * Setter for Findings.
     * @param findings Value for EndpointReference
     */
    @JsonSetter("findings")
    public void setFindings(EndpointReference findings) {
        this.findings = findings;
    }

    /**
     * Getter for Id.
     * Unique numerical identifier of the deployment.
     * @return Returns the long
     */
    @JsonGetter("id")
    public long getId() {
        return id;
    }

    /**
     * Setter for Id.
     * Unique numerical identifier of the deployment.
     * @param id Value for long
     */
    @JsonSetter("id")
    public void setId(long id) {
        this.id = id;
    }

    /**
     * Getter for Name.
     * Human readable name.
     * @return Returns the String
     */
    @JsonGetter("name")
    public String getName() {
        return name;
    }

    /**
     * Setter for Name.
     * Human readable name.
     * @param name Value for String
     */
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for Slug.
     * Sanitized machine-readable name. Used as primary identifier through the web API.
     * @return Returns the String
     */
    @JsonGetter("slug")
    public String getSlug() {
        return slug;
    }

    /**
     * Setter for Slug.
     * Sanitized machine-readable name. Used as primary identifier through the web API.
     * @param slug Value for String
     */
    @JsonSetter("slug")
    public void setSlug(String slug) {
        this.slug = slug;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this Deployment into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Deployment [" + "id=" + id + ", name=" + name + ", slug=" + slug + ", findings="
                + findings + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link Deployment.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Deployment.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(id, name, slug)
                .findings(getFindings());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link Deployment}.
     */
    public static class Builder {
        private long id;
        private String name;
        private String slug;
        private EndpointReference findings;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  id  long value for id.
         * @param  name  String value for name.
         * @param  slug  String value for slug.
         */
        public Builder(long id, String name, String slug) {
            this.id = id;
            this.name = name;
            this.slug = slug;
        }

        /**
         * Setter for id.
         * @param  id  long value for id.
         * @return Builder
         */
        public Builder id(long id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for name.
         * @param  name  String value for name.
         * @return Builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for slug.
         * @param  slug  String value for slug.
         * @return Builder
         */
        public Builder slug(String slug) {
            this.slug = slug;
            return this;
        }

        /**
         * Setter for findings.
         * @param  findings  EndpointReference value for findings.
         * @return Builder
         */
        public Builder findings(EndpointReference findings) {
            this.findings = findings;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link Deployment} object using the set fields.
         * @return {@link Deployment}
         */
        public Deployment build() {
            Deployment model =
                    new Deployment(id, name, slug, findings);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
