/*
 * SemgrepWebAppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.semgrep.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * Ecosystem to be used.
 */
public enum Ecosystem {
    NO_PACKAGE_MANAGER,

    NPM,

    PYPI,

    GOMOD,

    CARGO,

    MAVEN,

    GEM,

    COMPOSER,

    NUGET,

    PUB,

    SWIFTPM,

    HEX,

    COCOAPODS,

    MIX,

    OPAM;

    private static TreeMap<String, Ecosystem> valueMap = new TreeMap<>();
    private String value;

    static {
        NO_PACKAGE_MANAGER.value = "no_package_manager";
        NPM.value = "npm";
        PYPI.value = "pypi";
        GOMOD.value = "gomod";
        CARGO.value = "cargo";
        MAVEN.value = "maven";
        GEM.value = "gem";
        COMPOSER.value = "composer";
        NUGET.value = "nuget";
        PUB.value = "pub";
        SWIFTPM.value = "swiftpm";
        HEX.value = "hex";
        COCOAPODS.value = "cocoapods";
        MIX.value = "mix";
        OPAM.value = "opam";

        valueMap.put("no_package_manager", NO_PACKAGE_MANAGER);
        valueMap.put("npm", NPM);
        valueMap.put("pypi", PYPI);
        valueMap.put("gomod", GOMOD);
        valueMap.put("cargo", CARGO);
        valueMap.put("maven", MAVEN);
        valueMap.put("gem", GEM);
        valueMap.put("composer", COMPOSER);
        valueMap.put("nuget", NUGET);
        valueMap.put("pub", PUB);
        valueMap.put("swiftpm", SWIFTPM);
        valueMap.put("hex", HEX);
        valueMap.put("cocoapods", COCOAPODS);
        valueMap.put("mix", MIX);
        valueMap.put("opam", OPAM);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static Ecosystem constructFromString(String toConvert) throws IOException {
        Ecosystem enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static Ecosystem fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of Ecosystem values to list of string values.
     * @param toConvert The list of Ecosystem values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<Ecosystem> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (Ecosystem enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 