/*
 * SemgrepWebAppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.semgrep.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for FindingRule type.
 */
public class FindingRule {
    private String category;
    private Confidence2 confidence;
    private List<String> cweNames;
    private String message;
    private String name;
    private List<String> owaspNames;
    private List<String> subcategories;
    private List<String> vulnerabilityClasses;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public FindingRule() {
    }

    /**
     * Initialization constructor.
     * @param  category  String value for category.
     * @param  confidence  Confidence2 value for confidence.
     * @param  cweNames  List of String value for cweNames.
     * @param  message  String value for message.
     * @param  name  String value for name.
     * @param  owaspNames  List of String value for owaspNames.
     * @param  subcategories  List of String value for subcategories.
     * @param  vulnerabilityClasses  List of String value for vulnerabilityClasses.
     */
    public FindingRule(
            String category,
            Confidence2 confidence,
            List<String> cweNames,
            String message,
            String name,
            List<String> owaspNames,
            List<String> subcategories,
            List<String> vulnerabilityClasses) {
        this.category = category;
        this.confidence = confidence;
        this.cweNames = cweNames;
        this.message = message;
        this.name = name;
        this.owaspNames = owaspNames;
        this.subcategories = subcategories;
        this.vulnerabilityClasses = vulnerabilityClasses;
    }

    /**
     * Getter for Category.
     * Category the rule is associated with
     * @return Returns the String
     */
    @JsonGetter("category")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCategory() {
        return category;
    }

    /**
     * Setter for Category.
     * Category the rule is associated with
     * @param category Value for String
     */
    @JsonSetter("category")
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * Getter for Confidence.
     * Confidence level of the rule
     * @return Returns the Confidence2
     */
    @JsonGetter("confidence")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Confidence2 getConfidence() {
        return confidence;
    }

    /**
     * Setter for Confidence.
     * Confidence level of the rule
     * @param confidence Value for Confidence2
     */
    @JsonSetter("confidence")
    public void setConfidence(Confidence2 confidence) {
        this.confidence = confidence;
    }

    /**
     * Getter for CweNames.
     * CWE names associated with the rule
     * @return Returns the List of String
     */
    @JsonGetter("cwe_names")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getCweNames() {
        return cweNames;
    }

    /**
     * Setter for CweNames.
     * CWE names associated with the rule
     * @param cweNames Value for List of String
     */
    @JsonSetter("cwe_names")
    public void setCweNames(List<String> cweNames) {
        this.cweNames = cweNames;
    }

    /**
     * Getter for Message.
     * Rule message
     * @return Returns the String
     */
    @JsonGetter("message")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getMessage() {
        return message;
    }

    /**
     * Setter for Message.
     * Rule message
     * @param message Value for String
     */
    @JsonSetter("message")
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * Getter for Name.
     * Name of the rule
     * @return Returns the String
     */
    @JsonGetter("name")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getName() {
        return name;
    }

    /**
     * Setter for Name.
     * Name of the rule
     * @param name Value for String
     */
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for OwaspNames.
     * OWASP names associated with the rule
     * @return Returns the List of String
     */
    @JsonGetter("owasp_names")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getOwaspNames() {
        return owaspNames;
    }

    /**
     * Setter for OwaspNames.
     * OWASP names associated with the rule
     * @param owaspNames Value for List of String
     */
    @JsonSetter("owasp_names")
    public void setOwaspNames(List<String> owaspNames) {
        this.owaspNames = owaspNames;
    }

    /**
     * Getter for Subcategories.
     * Subcategories of the rule
     * @return Returns the List of String
     */
    @JsonGetter("subcategories")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getSubcategories() {
        return subcategories;
    }

    /**
     * Setter for Subcategories.
     * Subcategories of the rule
     * @param subcategories Value for List of String
     */
    @JsonSetter("subcategories")
    public void setSubcategories(List<String> subcategories) {
        this.subcategories = subcategories;
    }

    /**
     * Getter for VulnerabilityClasses.
     * Vulnerability classes the rule is associated with
     * @return Returns the List of String
     */
    @JsonGetter("vulnerability_classes")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getVulnerabilityClasses() {
        return vulnerabilityClasses;
    }

    /**
     * Setter for VulnerabilityClasses.
     * Vulnerability classes the rule is associated with
     * @param vulnerabilityClasses Value for List of String
     */
    @JsonSetter("vulnerability_classes")
    public void setVulnerabilityClasses(List<String> vulnerabilityClasses) {
        this.vulnerabilityClasses = vulnerabilityClasses;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this FindingRule into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "FindingRule [" + "category=" + category + ", confidence=" + confidence
                + ", cweNames=" + cweNames + ", message=" + message + ", name=" + name
                + ", owaspNames=" + owaspNames + ", subcategories=" + subcategories
                + ", vulnerabilityClasses=" + vulnerabilityClasses + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link FindingRule.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link FindingRule.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .category(getCategory())
                .confidence(getConfidence())
                .cweNames(getCweNames())
                .message(getMessage())
                .name(getName())
                .owaspNames(getOwaspNames())
                .subcategories(getSubcategories())
                .vulnerabilityClasses(getVulnerabilityClasses());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link FindingRule}.
     */
    public static class Builder {
        private String category;
        private Confidence2 confidence;
        private List<String> cweNames;
        private String message;
        private String name;
        private List<String> owaspNames;
        private List<String> subcategories;
        private List<String> vulnerabilityClasses;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for category.
         * @param  category  String value for category.
         * @return Builder
         */
        public Builder category(String category) {
            this.category = category;
            return this;
        }

        /**
         * Setter for confidence.
         * @param  confidence  Confidence2 value for confidence.
         * @return Builder
         */
        public Builder confidence(Confidence2 confidence) {
            this.confidence = confidence;
            return this;
        }

        /**
         * Setter for cweNames.
         * @param  cweNames  List of String value for cweNames.
         * @return Builder
         */
        public Builder cweNames(List<String> cweNames) {
            this.cweNames = cweNames;
            return this;
        }

        /**
         * Setter for message.
         * @param  message  String value for message.
         * @return Builder
         */
        public Builder message(String message) {
            this.message = message;
            return this;
        }

        /**
         * Setter for name.
         * @param  name  String value for name.
         * @return Builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for owaspNames.
         * @param  owaspNames  List of String value for owaspNames.
         * @return Builder
         */
        public Builder owaspNames(List<String> owaspNames) {
            this.owaspNames = owaspNames;
            return this;
        }

        /**
         * Setter for subcategories.
         * @param  subcategories  List of String value for subcategories.
         * @return Builder
         */
        public Builder subcategories(List<String> subcategories) {
            this.subcategories = subcategories;
            return this;
        }

        /**
         * Setter for vulnerabilityClasses.
         * @param  vulnerabilityClasses  List of String value for vulnerabilityClasses.
         * @return Builder
         */
        public Builder vulnerabilityClasses(List<String> vulnerabilityClasses) {
            this.vulnerabilityClasses = vulnerabilityClasses;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link FindingRule} object using the set fields.
         * @return {@link FindingRule}
         */
        public FindingRule build() {
            FindingRule model =
                    new FindingRule(category, confidence, cweNames, message, name, owaspNames,
                            subcategories, vulnerabilityClasses);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
