/*
 * SemgrepWebAppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.semgrep.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for Guidance type.
 */
public class Guidance {
    private String instructions;
    private String summary;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public Guidance() {
    }

    /**
     * Initialization constructor.
     * @param  instructions  String value for instructions.
     * @param  summary  String value for summary.
     */
    public Guidance(
            String instructions,
            String summary) {
        this.instructions = instructions;
        this.summary = summary;
    }

    /**
     * Getter for Instructions.
     * Step-by-step instructions explaining to a developer how to fix the finding. AI generated
     * content, review carefully
     * @return Returns the String
     */
    @JsonGetter("instructions")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getInstructions() {
        return instructions;
    }

    /**
     * Setter for Instructions.
     * Step-by-step instructions explaining to a developer how to fix the finding. AI generated
     * content, review carefully
     * @param instructions Value for String
     */
    @JsonSetter("instructions")
    public void setInstructions(String instructions) {
        this.instructions = instructions;
    }

    /**
     * Getter for Summary.
     * Short title explaining to a developer how to fix the finding. AI generated content, review
     * carefully
     * @return Returns the String
     */
    @JsonGetter("summary")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getSummary() {
        return summary;
    }

    /**
     * Setter for Summary.
     * Short title explaining to a developer how to fix the finding. AI generated content, review
     * carefully
     * @param summary Value for String
     */
    @JsonSetter("summary")
    public void setSummary(String summary) {
        this.summary = summary;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this Guidance into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Guidance [" + "instructions=" + instructions + ", summary=" + summary
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link Guidance.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Guidance.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .instructions(getInstructions())
                .summary(getSummary());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link Guidance}.
     */
    public static class Builder {
        private String instructions;
        private String summary;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for instructions.
         * @param  instructions  String value for instructions.
         * @return Builder
         */
        public Builder instructions(String instructions) {
            this.instructions = instructions;
            return this;
        }

        /**
         * Setter for summary.
         * @param  summary  String value for summary.
         * @return Builder
         */
        public Builder summary(String summary) {
            this.summary = summary;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link Guidance} object using the set fields.
         * @return {@link Guidance}
         */
        public Guidance build() {
            Guidance model =
                    new Guidance(instructions, summary);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
