/*
 * SemgrepWebAppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.semgrep.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for ListDependenciesResponse type.
 */
public class ListDependenciesResponse {
    private String cursor;
    private List<ProtosScaV1FoundDependency> dependencies;
    private boolean hasMore;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public ListDependenciesResponse() {
    }

    /**
     * Initialization constructor.
     * @param  dependencies  List of ProtosScaV1FoundDependency value for dependencies.
     * @param  hasMore  boolean value for hasMore.
     * @param  cursor  String value for cursor.
     */
    public ListDependenciesResponse(
            List<ProtosScaV1FoundDependency> dependencies,
            boolean hasMore,
            String cursor) {
        this.cursor = cursor;
        this.dependencies = dependencies;
        this.hasMore = hasMore;
    }

    /**
     * Getter for Cursor.
     * Pass to next request to get next page of results.
     * @return Returns the String
     */
    @JsonGetter("cursor")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCursor() {
        return cursor;
    }

    /**
     * Setter for Cursor.
     * Pass to next request to get next page of results.
     * @param cursor Value for String
     */
    @JsonSetter("cursor")
    public void setCursor(String cursor) {
        this.cursor = cursor;
    }

    /**
     * Getter for Dependencies.
     * List of dependencies.
     * @return Returns the List of ProtosScaV1FoundDependency
     */
    @JsonGetter("dependencies")
    public List<ProtosScaV1FoundDependency> getDependencies() {
        return dependencies;
    }

    /**
     * Setter for Dependencies.
     * List of dependencies.
     * @param dependencies Value for List of ProtosScaV1FoundDependency
     */
    @JsonSetter("dependencies")
    public void setDependencies(List<ProtosScaV1FoundDependency> dependencies) {
        this.dependencies = dependencies;
    }

    /**
     * Getter for HasMore.
     * True if there are more dependencies to get.
     * @return Returns the boolean
     */
    @JsonGetter("hasMore")
    public boolean getHasMore() {
        return hasMore;
    }

    /**
     * Setter for HasMore.
     * True if there are more dependencies to get.
     * @param hasMore Value for boolean
     */
    @JsonSetter("hasMore")
    public void setHasMore(boolean hasMore) {
        this.hasMore = hasMore;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this ListDependenciesResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ListDependenciesResponse [" + "dependencies=" + dependencies + ", hasMore="
                + hasMore + ", cursor=" + cursor + ", additionalProperties=" + additionalProperties
                + "]";
    }

    /**
     * Builds a new {@link ListDependenciesResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ListDependenciesResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(dependencies, hasMore)
                .cursor(getCursor());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link ListDependenciesResponse}.
     */
    public static class Builder {
        private List<ProtosScaV1FoundDependency> dependencies;
        private boolean hasMore;
        private String cursor;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  dependencies  List of ProtosScaV1FoundDependency value for dependencies.
         * @param  hasMore  boolean value for hasMore.
         */
        public Builder(List<ProtosScaV1FoundDependency> dependencies, boolean hasMore) {
            this.dependencies = dependencies;
            this.hasMore = hasMore;
        }

        /**
         * Setter for dependencies.
         * @param  dependencies  List of ProtosScaV1FoundDependency value for dependencies.
         * @return Builder
         */
        public Builder dependencies(List<ProtosScaV1FoundDependency> dependencies) {
            this.dependencies = dependencies;
            return this;
        }

        /**
         * Setter for hasMore.
         * @param  hasMore  boolean value for hasMore.
         * @return Builder
         */
        public Builder hasMore(boolean hasMore) {
            this.hasMore = hasMore;
            return this;
        }

        /**
         * Setter for cursor.
         * @param  cursor  String value for cursor.
         * @return Builder
         */
        public Builder cursor(String cursor) {
            this.cursor = cursor;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link ListDependenciesResponse} object using the set fields.
         * @return {@link ListDependenciesResponse}
         */
        public ListDependenciesResponse build() {
            ListDependenciesResponse model =
                    new ListDependenciesResponse(dependencies, hasMore, cursor);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
