/*
 * SemgrepWebAppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.semgrep.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * ProductType to be used.
 */
public enum ProductType {
    PRODUCT_TYPE_SAST,

    PRODUCT_TYPE_SECRETS;

    private static TreeMap<String, ProductType> valueMap = new TreeMap<>();
    private String value;

    static {
        PRODUCT_TYPE_SAST.value = "PRODUCT_TYPE_SAST";
        PRODUCT_TYPE_SECRETS.value = "PRODUCT_TYPE_SECRETS";

        valueMap.put("PRODUCT_TYPE_SAST", PRODUCT_TYPE_SAST);
        valueMap.put("PRODUCT_TYPE_SECRETS", PRODUCT_TYPE_SECRETS);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static ProductType constructFromString(String toConvert) throws IOException {
        ProductType enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static ProductType fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of ProductType values to list of string values.
     * @param toConvert The list of ProductType values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<ProductType> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (ProductType enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 