/*
 * SemgrepWebAppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.semgrep.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for ProtosOpenapiV1ListPolicyRulesResponse type.
 */
public class ProtosOpenapiV1ListPolicyRulesResponse {
    private String cursor;
    private Policy policy;
    private List<Rule> rules;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public ProtosOpenapiV1ListPolicyRulesResponse() {
    }

    /**
     * Initialization constructor.
     * @param  cursor  String value for cursor.
     * @param  policy  Policy value for policy.
     * @param  rules  List of Rule value for rules.
     */
    public ProtosOpenapiV1ListPolicyRulesResponse(
            String cursor,
            Policy policy,
            List<Rule> rules) {
        this.cursor = cursor;
        this.policy = policy;
        this.rules = rules;
    }

    /**
     * Getter for Cursor.
     * Cursor to paginate through the rules.
     * @return Returns the String
     */
    @JsonGetter("cursor")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCursor() {
        return cursor;
    }

    /**
     * Setter for Cursor.
     * Cursor to paginate through the rules.
     * @param cursor Value for String
     */
    @JsonSetter("cursor")
    public void setCursor(String cursor) {
        this.cursor = cursor;
    }

    /**
     * Getter for Policy.
     * @return Returns the Policy
     */
    @JsonGetter("policy")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Policy getPolicy() {
        return policy;
    }

    /**
     * Setter for Policy.
     * @param policy Value for Policy
     */
    @JsonSetter("policy")
    public void setPolicy(Policy policy) {
        this.policy = policy;
    }

    /**
     * Getter for Rules.
     * List of Rules for the given Policy.
     * @return Returns the List of Rule
     */
    @JsonGetter("rules")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<Rule> getRules() {
        return rules;
    }

    /**
     * Setter for Rules.
     * List of Rules for the given Policy.
     * @param rules Value for List of Rule
     */
    @JsonSetter("rules")
    public void setRules(List<Rule> rules) {
        this.rules = rules;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this ProtosOpenapiV1ListPolicyRulesResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ProtosOpenapiV1ListPolicyRulesResponse [" + "cursor=" + cursor + ", policy="
                + policy + ", rules=" + rules + ", additionalProperties=" + additionalProperties
                + "]";
    }

    /**
     * Builds a new {@link ProtosOpenapiV1ListPolicyRulesResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ProtosOpenapiV1ListPolicyRulesResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .cursor(getCursor())
                .policy(getPolicy())
                .rules(getRules());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link ProtosOpenapiV1ListPolicyRulesResponse}.
     */
    public static class Builder {
        private String cursor;
        private Policy policy;
        private List<Rule> rules;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for cursor.
         * @param  cursor  String value for cursor.
         * @return Builder
         */
        public Builder cursor(String cursor) {
            this.cursor = cursor;
            return this;
        }

        /**
         * Setter for policy.
         * @param  policy  Policy value for policy.
         * @return Builder
         */
        public Builder policy(Policy policy) {
            this.policy = policy;
            return this;
        }

        /**
         * Setter for rules.
         * @param  rules  List of Rule value for rules.
         * @return Builder
         */
        public Builder rules(List<Rule> rules) {
            this.rules = rules;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link ProtosOpenapiV1ListPolicyRulesResponse} object using the set fields.
         * @return {@link ProtosOpenapiV1ListPolicyRulesResponse}
         */
        public ProtosOpenapiV1ListPolicyRulesResponse build() {
            ProtosOpenapiV1ListPolicyRulesResponse model =
                    new ProtosOpenapiV1ListPolicyRulesResponse(cursor, policy, rules);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
