/*
 * SemgrepWebAppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.semgrep.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for ProtosOpenapiV1GetScanResponse type.
 */
public class ProtosOpenapiV1GetScanResponse {
    private String completedAt;
    private Long deploymentId;
    private List<String> enabledProducts;
    private Long exitCode;
    private Boolean hasLogs;
    private Long id;
    private ProtosOpenapiV1GetScanResponseScanMeta meta;
    private Long repositoryId;
    private String startedAt;
    private Object stats;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public ProtosOpenapiV1GetScanResponse() {
    }

    /**
     * Initialization constructor.
     * @param  completedAt  String value for completedAt.
     * @param  deploymentId  Long value for deploymentId.
     * @param  enabledProducts  List of String value for enabledProducts.
     * @param  exitCode  Long value for exitCode.
     * @param  hasLogs  Boolean value for hasLogs.
     * @param  id  Long value for id.
     * @param  meta  ProtosOpenapiV1GetScanResponseScanMeta value for meta.
     * @param  repositoryId  Long value for repositoryId.
     * @param  startedAt  String value for startedAt.
     * @param  stats  Object value for stats.
     */
    public ProtosOpenapiV1GetScanResponse(
            String completedAt,
            Long deploymentId,
            List<String> enabledProducts,
            Long exitCode,
            Boolean hasLogs,
            Long id,
            ProtosOpenapiV1GetScanResponseScanMeta meta,
            Long repositoryId,
            String startedAt,
            Object stats) {
        this.completedAt = completedAt;
        this.deploymentId = deploymentId;
        this.enabledProducts = enabledProducts;
        this.exitCode = exitCode;
        this.hasLogs = hasLogs;
        this.id = id;
        this.meta = meta;
        this.repositoryId = repositoryId;
        this.startedAt = startedAt;
        this.stats = stats;
    }

    /**
     * Getter for CompletedAt.
     * imestamp of when the scan started.
     * @return Returns the String
     */
    @JsonGetter("completed_at")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCompletedAt() {
        return completedAt;
    }

    /**
     * Setter for CompletedAt.
     * imestamp of when the scan started.
     * @param completedAt Value for String
     */
    @JsonSetter("completed_at")
    public void setCompletedAt(String completedAt) {
        this.completedAt = completedAt;
    }

    /**
     * Getter for DeploymentId.
     * The unique ID of the deployment associated with the scanned repository.
     * @return Returns the Long
     */
    @JsonGetter("deployment_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Long getDeploymentId() {
        return deploymentId;
    }

    /**
     * Setter for DeploymentId.
     * The unique ID of the deployment associated with the scanned repository.
     * @param deploymentId Value for Long
     */
    @JsonSetter("deployment_id")
    public void setDeploymentId(Long deploymentId) {
        this.deploymentId = deploymentId;
    }

    /**
     * Getter for EnabledProducts.
     * The products used when running the scan.
     * @return Returns the List of String
     */
    @JsonGetter("enabled_products")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getEnabledProducts() {
        return enabledProducts;
    }

    /**
     * Setter for EnabledProducts.
     * The products used when running the scan.
     * @param enabledProducts Value for List of String
     */
    @JsonSetter("enabled_products")
    public void setEnabledProducts(List<String> enabledProducts) {
        this.enabledProducts = enabledProducts;
    }

    /**
     * Getter for ExitCode.
     * @return Returns the Long
     */
    @JsonGetter("exit_code")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Long getExitCode() {
        return exitCode;
    }

    /**
     * Setter for ExitCode.
     * @param exitCode Value for Long
     */
    @JsonSetter("exit_code")
    public void setExitCode(Long exitCode) {
        this.exitCode = exitCode;
    }

    /**
     * Getter for HasLogs.
     * @return Returns the Boolean
     */
    @JsonGetter("has_logs")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getHasLogs() {
        return hasLogs;
    }

    /**
     * Setter for HasLogs.
     * @param hasLogs Value for Boolean
     */
    @JsonSetter("has_logs")
    public void setHasLogs(Boolean hasLogs) {
        this.hasLogs = hasLogs;
    }

    /**
     * Getter for Id.
     * The unique ID representing this scan.
     * @return Returns the Long
     */
    @JsonGetter("id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Long getId() {
        return id;
    }

    /**
     * Setter for Id.
     * The unique ID representing this scan.
     * @param id Value for Long
     */
    @JsonSetter("id")
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for Meta.
     * @return Returns the ProtosOpenapiV1GetScanResponseScanMeta
     */
    @JsonGetter("meta")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ProtosOpenapiV1GetScanResponseScanMeta getMeta() {
        return meta;
    }

    /**
     * Setter for Meta.
     * @param meta Value for ProtosOpenapiV1GetScanResponseScanMeta
     */
    @JsonSetter("meta")
    public void setMeta(ProtosOpenapiV1GetScanResponseScanMeta meta) {
        this.meta = meta;
    }

    /**
     * Getter for RepositoryId.
     * The unique ID of the repository that was scanned.
     * @return Returns the Long
     */
    @JsonGetter("repository_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Long getRepositoryId() {
        return repositoryId;
    }

    /**
     * Setter for RepositoryId.
     * The unique ID of the repository that was scanned.
     * @param repositoryId Value for Long
     */
    @JsonSetter("repository_id")
    public void setRepositoryId(Long repositoryId) {
        this.repositoryId = repositoryId;
    }

    /**
     * Getter for StartedAt.
     * when the scan was started
     * @return Returns the String
     */
    @JsonGetter("started_at")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getStartedAt() {
        return startedAt;
    }

    /**
     * Setter for StartedAt.
     * when the scan was started
     * @param startedAt Value for String
     */
    @JsonSetter("started_at")
    public void setStartedAt(String startedAt) {
        this.startedAt = startedAt;
    }

    /**
     * Getter for Stats.
     * Miscellaneous statistics about the scan, like number of findings found and scan duration.
     * @return Returns the Object
     */
    @JsonGetter("stats")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Object getStats() {
        return stats;
    }

    /**
     * Setter for Stats.
     * Miscellaneous statistics about the scan, like number of findings found and scan duration.
     * @param stats Value for Object
     */
    @JsonSetter("stats")
    public void setStats(Object stats) {
        this.stats = stats;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this ProtosOpenapiV1GetScanResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ProtosOpenapiV1GetScanResponse [" + "completedAt=" + completedAt + ", deploymentId="
                + deploymentId + ", enabledProducts=" + enabledProducts + ", exitCode=" + exitCode
                + ", hasLogs=" + hasLogs + ", id=" + id + ", meta=" + meta + ", repositoryId="
                + repositoryId + ", startedAt=" + startedAt + ", stats=" + stats
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link ProtosOpenapiV1GetScanResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ProtosOpenapiV1GetScanResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .completedAt(getCompletedAt())
                .deploymentId(getDeploymentId())
                .enabledProducts(getEnabledProducts())
                .exitCode(getExitCode())
                .hasLogs(getHasLogs())
                .id(getId())
                .meta(getMeta())
                .repositoryId(getRepositoryId())
                .startedAt(getStartedAt())
                .stats(getStats());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link ProtosOpenapiV1GetScanResponse}.
     */
    public static class Builder {
        private String completedAt;
        private Long deploymentId;
        private List<String> enabledProducts;
        private Long exitCode;
        private Boolean hasLogs;
        private Long id;
        private ProtosOpenapiV1GetScanResponseScanMeta meta;
        private Long repositoryId;
        private String startedAt;
        private Object stats;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for completedAt.
         * @param  completedAt  String value for completedAt.
         * @return Builder
         */
        public Builder completedAt(String completedAt) {
            this.completedAt = completedAt;
            return this;
        }

        /**
         * Setter for deploymentId.
         * @param  deploymentId  Long value for deploymentId.
         * @return Builder
         */
        public Builder deploymentId(Long deploymentId) {
            this.deploymentId = deploymentId;
            return this;
        }

        /**
         * Setter for enabledProducts.
         * @param  enabledProducts  List of String value for enabledProducts.
         * @return Builder
         */
        public Builder enabledProducts(List<String> enabledProducts) {
            this.enabledProducts = enabledProducts;
            return this;
        }

        /**
         * Setter for exitCode.
         * @param  exitCode  Long value for exitCode.
         * @return Builder
         */
        public Builder exitCode(Long exitCode) {
            this.exitCode = exitCode;
            return this;
        }

        /**
         * Setter for hasLogs.
         * @param  hasLogs  Boolean value for hasLogs.
         * @return Builder
         */
        public Builder hasLogs(Boolean hasLogs) {
            this.hasLogs = hasLogs;
            return this;
        }

        /**
         * Setter for id.
         * @param  id  Long value for id.
         * @return Builder
         */
        public Builder id(Long id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for meta.
         * @param  meta  ProtosOpenapiV1GetScanResponseScanMeta value for meta.
         * @return Builder
         */
        public Builder meta(ProtosOpenapiV1GetScanResponseScanMeta meta) {
            this.meta = meta;
            return this;
        }

        /**
         * Setter for repositoryId.
         * @param  repositoryId  Long value for repositoryId.
         * @return Builder
         */
        public Builder repositoryId(Long repositoryId) {
            this.repositoryId = repositoryId;
            return this;
        }

        /**
         * Setter for startedAt.
         * @param  startedAt  String value for startedAt.
         * @return Builder
         */
        public Builder startedAt(String startedAt) {
            this.startedAt = startedAt;
            return this;
        }

        /**
         * Setter for stats.
         * @param  stats  Object value for stats.
         * @return Builder
         */
        public Builder stats(Object stats) {
            this.stats = stats;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link ProtosOpenapiV1GetScanResponse} object using the set fields.
         * @return {@link ProtosOpenapiV1GetScanResponse}
         */
        public ProtosOpenapiV1GetScanResponse build() {
            ProtosOpenapiV1GetScanResponse model =
                    new ProtosOpenapiV1GetScanResponse(completedAt, deploymentId, enabledProducts,
                            exitCode, hasLogs, id, meta, repositoryId, startedAt, stats);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
