/*
 * SemgrepWebAppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.semgrep.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for ProtosScaV1SbomFormatVersion type.
 */
public class ProtosScaV1SbomFormatVersion {
    private CyclonedxVersion cyclonedxVersion;
    private Format format;
    private String version;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public ProtosScaV1SbomFormatVersion() {
        format = Format.SBOM_FORMAT_CYCLONEDX;
    }

    /**
     * Initialization constructor.
     * @param  cyclonedxVersion  CyclonedxVersion value for cyclonedxVersion.
     * @param  format  Format value for format.
     * @param  version  String value for version.
     */
    public ProtosScaV1SbomFormatVersion(
            CyclonedxVersion cyclonedxVersion,
            Format format,
            String version) {
        this.cyclonedxVersion = cyclonedxVersion;
        this.format = format;
        this.version = version;
    }

    /**
     * Getter for CyclonedxVersion.
     * CycloneDX schema version for the SBOM export. Supported: 1.4, 1.5, 1.6, 1.7. Defaults to 1.4
     * when unset. | value | description | |-------|---------------| | SBOM_CYCLONE_DX_VERSION_V1_4
     * | | | SBOM_CYCLONE_DX_VERSION_V1_5 | | | SBOM_CYCLONE_DX_VERSION_V1_6 | | |
     * SBOM_CYCLONE_DX_VERSION_V1_7 | |
     * @return Returns the CyclonedxVersion
     */
    @JsonGetter("cyclonedxVersion")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public CyclonedxVersion getCyclonedxVersion() {
        return cyclonedxVersion;
    }

    /**
     * Setter for CyclonedxVersion.
     * CycloneDX schema version for the SBOM export. Supported: 1.4, 1.5, 1.6, 1.7. Defaults to 1.4
     * when unset. | value | description | |-------|---------------| | SBOM_CYCLONE_DX_VERSION_V1_4
     * | | | SBOM_CYCLONE_DX_VERSION_V1_5 | | | SBOM_CYCLONE_DX_VERSION_V1_6 | | |
     * SBOM_CYCLONE_DX_VERSION_V1_7 | |
     * @param cyclonedxVersion Value for CyclonedxVersion
     */
    @JsonSetter("cyclonedxVersion")
    public void setCyclonedxVersion(CyclonedxVersion cyclonedxVersion) {
        this.cyclonedxVersion = cyclonedxVersion;
    }

    /**
     * Getter for Format.
     * Format for the SBOM export. | value | description | |-------|---------------| |
     * SBOM_FORMAT_CYCLONEDX | |
     * @return Returns the Format
     */
    @JsonGetter("format")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Format getFormat() {
        return format;
    }

    /**
     * Setter for Format.
     * Format for the SBOM export. | value | description | |-------|---------------| |
     * SBOM_FORMAT_CYCLONEDX | |
     * @param format Value for Format
     */
    @JsonSetter("format")
    public void setFormat(Format format) {
        this.format = format;
    }

    /**
     * Getter for Version.
     * Deprecated. Use `cyclonedx_version`. Free-text CycloneDX version, e.g. "1.7".
     * @return Returns the String
     */
    @JsonGetter("version")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getVersion() {
        return version;
    }

    /**
     * Setter for Version.
     * Deprecated. Use `cyclonedx_version`. Free-text CycloneDX version, e.g. "1.7".
     * @param version Value for String
     */
    @JsonSetter("version")
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this ProtosScaV1SbomFormatVersion into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ProtosScaV1SbomFormatVersion [" + "cyclonedxVersion=" + cyclonedxVersion
                + ", format=" + format + ", version=" + version + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link ProtosScaV1SbomFormatVersion.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ProtosScaV1SbomFormatVersion.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .cyclonedxVersion(getCyclonedxVersion())
                .format(getFormat())
                .version(getVersion());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link ProtosScaV1SbomFormatVersion}.
     */
    public static class Builder {
        private CyclonedxVersion cyclonedxVersion;
        private Format format = Format.SBOM_FORMAT_CYCLONEDX;
        private String version;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for cyclonedxVersion.
         * @param  cyclonedxVersion  CyclonedxVersion value for cyclonedxVersion.
         * @return Builder
         */
        public Builder cyclonedxVersion(CyclonedxVersion cyclonedxVersion) {
            this.cyclonedxVersion = cyclonedxVersion;
            return this;
        }

        /**
         * Setter for format.
         * @param  format  Format value for format.
         * @return Builder
         */
        public Builder format(Format format) {
            this.format = format;
            return this;
        }

        /**
         * Setter for version.
         * @param  version  String value for version.
         * @return Builder
         */
        public Builder version(String version) {
            this.version = version;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link ProtosScaV1SbomFormatVersion} object using the set fields.
         * @return {@link ProtosScaV1SbomFormatVersion}
         */
        public ProtosScaV1SbomFormatVersion build() {
            ProtosScaV1SbomFormatVersion model =
                    new ProtosScaV1SbomFormatVersion(cyclonedxVersion, format, version);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
