/*
 * SemgrepWebAppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.semgrep.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for ProtosScaV1DependencyFilter type.
 */
public class ProtosScaV1DependencyFilter {
    private Ecosystem ecosystem;
    private List<String> license;
    private LicensePolicySettings licensePolicySettings;
    private String lockfilePath;
    private String name;
    private List<ProtosScaV1PackageFilter> packageFilters;
    private List<Long> repositoryId;
    private Transitivity transitivity;
    private String version;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public ProtosScaV1DependencyFilter() {
    }

    /**
     * Initialization constructor.
     * @param  ecosystem  Ecosystem value for ecosystem.
     * @param  license  List of String value for license.
     * @param  licensePolicySettings  LicensePolicySettings value for licensePolicySettings.
     * @param  lockfilePath  String value for lockfilePath.
     * @param  name  String value for name.
     * @param  packageFilters  List of ProtosScaV1PackageFilter value for packageFilters.
     * @param  repositoryId  List of Long value for repositoryId.
     * @param  transitivity  Transitivity value for transitivity.
     * @param  version  String value for version.
     */
    public ProtosScaV1DependencyFilter(
            Ecosystem ecosystem,
            List<String> license,
            LicensePolicySettings licensePolicySettings,
            String lockfilePath,
            String name,
            List<ProtosScaV1PackageFilter> packageFilters,
            List<Long> repositoryId,
            Transitivity transitivity,
            String version) {
        this.ecosystem = ecosystem;
        this.license = license;
        this.licensePolicySettings = licensePolicySettings;
        this.lockfilePath = lockfilePath;
        this.name = name;
        this.packageFilters = packageFilters;
        this.repositoryId = repositoryId;
        this.transitivity = transitivity;
        this.version = version;
    }

    /**
     * Getter for Ecosystem.
     * Filter by ecosystem (e.g. npm, pypi, etc). | value | description | |-------|---------------|
     * | no_package_manager | | | npm | | | pypi | | | gomod | | | cargo | | | maven | | | gem | | |
     * composer | | | nuget | | | pub | | | swiftpm | | | hex | | | cocoapods | | | mix | | | opam |
     * |
     * @return Returns the Ecosystem
     */
    @JsonGetter("ecosystem")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Ecosystem getEcosystem() {
        return ecosystem;
    }

    /**
     * Setter for Ecosystem.
     * Filter by ecosystem (e.g. npm, pypi, etc). | value | description | |-------|---------------|
     * | no_package_manager | | | npm | | | pypi | | | gomod | | | cargo | | | maven | | | gem | | |
     * composer | | | nuget | | | pub | | | swiftpm | | | hex | | | cocoapods | | | mix | | | opam |
     * |
     * @param ecosystem Value for Ecosystem
     */
    @JsonSetter("ecosystem")
    public void setEcosystem(Ecosystem ecosystem) {
        this.ecosystem = ecosystem;
    }

    /**
     * Getter for License.
     * Filter by license (e.g. MIT).
     * @return Returns the List of String
     */
    @JsonGetter("license")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getLicense() {
        return license;
    }

    /**
     * Setter for License.
     * Filter by license (e.g. MIT).
     * @param license Value for List of String
     */
    @JsonSetter("license")
    public void setLicense(List<String> license) {
        this.license = license;
    }

    /**
     * Getter for LicensePolicySettings.
     * Filter by license policy setting outcome. | value | description | |-------|---------------| |
     * LICENSE_POLICY_SETTING_ALLOW | | | LICENSE_POLICY_SETTING_COMMENT | | |
     * LICENSE_POLICY_SETTING_BLOCK | |
     * @return Returns the LicensePolicySettings
     */
    @JsonGetter("licensePolicySettings")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public LicensePolicySettings getLicensePolicySettings() {
        return licensePolicySettings;
    }

    /**
     * Setter for LicensePolicySettings.
     * Filter by license policy setting outcome. | value | description | |-------|---------------| |
     * LICENSE_POLICY_SETTING_ALLOW | | | LICENSE_POLICY_SETTING_COMMENT | | |
     * LICENSE_POLICY_SETTING_BLOCK | |
     * @param licensePolicySettings Value for LicensePolicySettings
     */
    @JsonSetter("licensePolicySettings")
    public void setLicensePolicySettings(LicensePolicySettings licensePolicySettings) {
        this.licensePolicySettings = licensePolicySettings;
    }

    /**
     * Getter for LockfilePath.
     * Filter by path to the lockfile (e.g. `foo/bar/package-lock.json`).
     * @return Returns the String
     */
    @JsonGetter("lockfilePath")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getLockfilePath() {
        return lockfilePath;
    }

    /**
     * Setter for LockfilePath.
     * Filter by path to the lockfile (e.g. `foo/bar/package-lock.json`).
     * @param lockfilePath Value for String
     */
    @JsonSetter("lockfilePath")
    public void setLockfilePath(String lockfilePath) {
        this.lockfilePath = lockfilePath;
    }

    /**
     * Getter for Name.
     * Deprecated - use package_filters instead. Filter by dependency name (e.g. lodash).
     * @return Returns the String
     */
    @JsonGetter("name")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getName() {
        return name;
    }

    /**
     * Setter for Name.
     * Deprecated - use package_filters instead. Filter by dependency name (e.g. lodash).
     * @param name Value for String
     */
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for PackageFilters.
     * Multiple package filters with exact name matching and version bounds.
     * @return Returns the List of ProtosScaV1PackageFilter
     */
    @JsonGetter("packageFilters")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<ProtosScaV1PackageFilter> getPackageFilters() {
        return packageFilters;
    }

    /**
     * Setter for PackageFilters.
     * Multiple package filters with exact name matching and version bounds.
     * @param packageFilters Value for List of ProtosScaV1PackageFilter
     */
    @JsonSetter("packageFilters")
    public void setPackageFilters(List<ProtosScaV1PackageFilter> packageFilters) {
        this.packageFilters = packageFilters;
    }

    /**
     * Getter for RepositoryId.
     * Repository IDs (numeric) to filter by. Omit if the endpoint has Repository ID as a path
     * parameter. Use Projects endpoints to retrieve Repository IDs.
     * @return Returns the List of Long
     */
    @JsonGetter("repositoryId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<Long> getRepositoryId() {
        return repositoryId;
    }

    /**
     * Setter for RepositoryId.
     * Repository IDs (numeric) to filter by. Omit if the endpoint has Repository ID as a path
     * parameter. Use Projects endpoints to retrieve Repository IDs.
     * @param repositoryId Value for List of Long
     */
    @JsonSetter("repositoryId")
    public void setRepositoryId(List<Long> repositoryId) {
        this.repositoryId = repositoryId;
    }

    /**
     * Getter for Transitivity.
     * Filter by transitivity. | value | description | |-------|---------------| |
     * UNKNOWN_TRANSITIVITY | | | TRANSITIVE | | | DIRECT | |
     * @return Returns the Transitivity
     */
    @JsonGetter("transitivity")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Transitivity getTransitivity() {
        return transitivity;
    }

    /**
     * Setter for Transitivity.
     * Filter by transitivity. | value | description | |-------|---------------| |
     * UNKNOWN_TRANSITIVITY | | | TRANSITIVE | | | DIRECT | |
     * @param transitivity Value for Transitivity
     */
    @JsonSetter("transitivity")
    public void setTransitivity(Transitivity transitivity) {
        this.transitivity = transitivity;
    }

    /**
     * Getter for Version.
     * Deprecated - use package_filters instead. Filter by dependency version (e.g. 1.0.1).
     * @return Returns the String
     */
    @JsonGetter("version")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getVersion() {
        return version;
    }

    /**
     * Setter for Version.
     * Deprecated - use package_filters instead. Filter by dependency version (e.g. 1.0.1).
     * @param version Value for String
     */
    @JsonSetter("version")
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this ProtosScaV1DependencyFilter into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ProtosScaV1DependencyFilter [" + "ecosystem=" + ecosystem + ", license=" + license
                + ", licensePolicySettings=" + licensePolicySettings + ", lockfilePath="
                + lockfilePath + ", name=" + name + ", packageFilters=" + packageFilters
                + ", repositoryId=" + repositoryId + ", transitivity=" + transitivity + ", version="
                + version + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link ProtosScaV1DependencyFilter.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ProtosScaV1DependencyFilter.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .ecosystem(getEcosystem())
                .license(getLicense())
                .licensePolicySettings(getLicensePolicySettings())
                .lockfilePath(getLockfilePath())
                .name(getName())
                .packageFilters(getPackageFilters())
                .repositoryId(getRepositoryId())
                .transitivity(getTransitivity())
                .version(getVersion());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link ProtosScaV1DependencyFilter}.
     */
    public static class Builder {
        private Ecosystem ecosystem;
        private List<String> license;
        private LicensePolicySettings licensePolicySettings;
        private String lockfilePath;
        private String name;
        private List<ProtosScaV1PackageFilter> packageFilters;
        private List<Long> repositoryId;
        private Transitivity transitivity;
        private String version;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for ecosystem.
         * @param  ecosystem  Ecosystem value for ecosystem.
         * @return Builder
         */
        public Builder ecosystem(Ecosystem ecosystem) {
            this.ecosystem = ecosystem;
            return this;
        }

        /**
         * Setter for license.
         * @param  license  List of String value for license.
         * @return Builder
         */
        public Builder license(List<String> license) {
            this.license = license;
            return this;
        }

        /**
         * Setter for licensePolicySettings.
         * @param  licensePolicySettings  LicensePolicySettings value for licensePolicySettings.
         * @return Builder
         */
        public Builder licensePolicySettings(LicensePolicySettings licensePolicySettings) {
            this.licensePolicySettings = licensePolicySettings;
            return this;
        }

        /**
         * Setter for lockfilePath.
         * @param  lockfilePath  String value for lockfilePath.
         * @return Builder
         */
        public Builder lockfilePath(String lockfilePath) {
            this.lockfilePath = lockfilePath;
            return this;
        }

        /**
         * Setter for name.
         * @param  name  String value for name.
         * @return Builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for packageFilters.
         * @param  packageFilters  List of ProtosScaV1PackageFilter value for packageFilters.
         * @return Builder
         */
        public Builder packageFilters(List<ProtosScaV1PackageFilter> packageFilters) {
            this.packageFilters = packageFilters;
            return this;
        }

        /**
         * Setter for repositoryId.
         * @param  repositoryId  List of Long value for repositoryId.
         * @return Builder
         */
        public Builder repositoryId(List<Long> repositoryId) {
            this.repositoryId = repositoryId;
            return this;
        }

        /**
         * Setter for transitivity.
         * @param  transitivity  Transitivity value for transitivity.
         * @return Builder
         */
        public Builder transitivity(Transitivity transitivity) {
            this.transitivity = transitivity;
            return this;
        }

        /**
         * Setter for version.
         * @param  version  String value for version.
         * @return Builder
         */
        public Builder version(String version) {
            this.version = version;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link ProtosScaV1DependencyFilter} object using the set fields.
         * @return {@link ProtosScaV1DependencyFilter}
         */
        public ProtosScaV1DependencyFilter build() {
            ProtosScaV1DependencyFilter model =
                    new ProtosScaV1DependencyFilter(ecosystem, license, licensePolicySettings,
                            lockfilePath, name, packageFilters, repositoryId, transitivity,
                            version);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
