/*
 * SemgrepWebAppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.semgrep.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for ProtosOpenapiV1CreateTicketResponseTicketCreationSuccess type.
 */
public class ProtosOpenapiV1CreateTicketResponseTicketCreationSuccess {
    private String externalSlug;
    private List<Long> issueIds;
    private Long ticketId;
    private String ticketUrl;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public ProtosOpenapiV1CreateTicketResponseTicketCreationSuccess() {
    }

    /**
     * Initialization constructor.
     * @param  externalSlug  String value for externalSlug.
     * @param  issueIds  List of Long value for issueIds.
     * @param  ticketId  Long value for ticketId.
     * @param  ticketUrl  String value for ticketUrl.
     */
    public ProtosOpenapiV1CreateTicketResponseTicketCreationSuccess(
            String externalSlug,
            List<Long> issueIds,
            Long ticketId,
            String ticketUrl) {
        this.externalSlug = externalSlug;
        this.issueIds = issueIds;
        this.ticketId = ticketId;
        this.ticketUrl = ticketUrl;
    }

    /**
     * Getter for ExternalSlug.
     * The external slug identifier for the ticket
     * @return Returns the String
     */
    @JsonGetter("external_slug")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getExternalSlug() {
        return externalSlug;
    }

    /**
     * Setter for ExternalSlug.
     * The external slug identifier for the ticket
     * @param externalSlug Value for String
     */
    @JsonSetter("external_slug")
    public void setExternalSlug(String externalSlug) {
        this.externalSlug = externalSlug;
    }

    /**
     * Getter for IssueIds.
     * List of issue IDs
     * @return Returns the List of Long
     */
    @JsonGetter("issue_ids")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<Long> getIssueIds() {
        return issueIds;
    }

    /**
     * Setter for IssueIds.
     * List of issue IDs
     * @param issueIds Value for List of Long
     */
    @JsonSetter("issue_ids")
    public void setIssueIds(List<Long> issueIds) {
        this.issueIds = issueIds;
    }

    /**
     * Getter for TicketId.
     * The ID of the created ticket
     * @return Returns the Long
     */
    @JsonGetter("ticket_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Long getTicketId() {
        return ticketId;
    }

    /**
     * Setter for TicketId.
     * The ID of the created ticket
     * @param ticketId Value for Long
     */
    @JsonSetter("ticket_id")
    public void setTicketId(Long ticketId) {
        this.ticketId = ticketId;
    }

    /**
     * Getter for TicketUrl.
     * The URL of the created ticket
     * @return Returns the String
     */
    @JsonGetter("ticket_url")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getTicketUrl() {
        return ticketUrl;
    }

    /**
     * Setter for TicketUrl.
     * The URL of the created ticket
     * @param ticketUrl Value for String
     */
    @JsonSetter("ticket_url")
    public void setTicketUrl(String ticketUrl) {
        this.ticketUrl = ticketUrl;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this ProtosOpenapiV1CreateTicketResponseTicketCreationSuccess into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ProtosOpenapiV1CreateTicketResponseTicketCreationSuccess [" + "externalSlug="
                + externalSlug + ", issueIds=" + issueIds + ", ticketId=" + ticketId
                + ", ticketUrl=" + ticketUrl + ", additionalProperties=" + additionalProperties
                + "]";
    }

    /**
     * Builds a new {@link ProtosOpenapiV1CreateTicketResponseTicketCreationSuccess.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ProtosOpenapiV1CreateTicketResponseTicketCreationSuccess.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .externalSlug(getExternalSlug())
                .issueIds(getIssueIds())
                .ticketId(getTicketId())
                .ticketUrl(getTicketUrl());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link ProtosOpenapiV1CreateTicketResponseTicketCreationSuccess}.
     */
    public static class Builder {
        private String externalSlug;
        private List<Long> issueIds;
        private Long ticketId;
        private String ticketUrl;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for externalSlug.
         * @param  externalSlug  String value for externalSlug.
         * @return Builder
         */
        public Builder externalSlug(String externalSlug) {
            this.externalSlug = externalSlug;
            return this;
        }

        /**
         * Setter for issueIds.
         * @param  issueIds  List of Long value for issueIds.
         * @return Builder
         */
        public Builder issueIds(List<Long> issueIds) {
            this.issueIds = issueIds;
            return this;
        }

        /**
         * Setter for ticketId.
         * @param  ticketId  Long value for ticketId.
         * @return Builder
         */
        public Builder ticketId(Long ticketId) {
            this.ticketId = ticketId;
            return this;
        }

        /**
         * Setter for ticketUrl.
         * @param  ticketUrl  String value for ticketUrl.
         * @return Builder
         */
        public Builder ticketUrl(String ticketUrl) {
            this.ticketUrl = ticketUrl;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link ProtosOpenapiV1CreateTicketResponseTicketCreationSuccess} object
         * using the set fields.
         * @return {@link ProtosOpenapiV1CreateTicketResponseTicketCreationSuccess}
         */
        public ProtosOpenapiV1CreateTicketResponseTicketCreationSuccess build() {
            ProtosOpenapiV1CreateTicketResponseTicketCreationSuccess model =
                    new ProtosOpenapiV1CreateTicketResponseTicketCreationSuccess(externalSlug,
                            issueIds, ticketId, ticketUrl);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
