/*
 * SemgrepWebAppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.semgrep.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for ProtosTicketingV1ExternalTicket type.
 */
public class ProtosTicketingV1ExternalTicket {
    private String externalSlug;
    private String id;
    private List<String> linkedIssueIds;
    private String url;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public ProtosTicketingV1ExternalTicket() {
    }

    /**
     * Initialization constructor.
     * @param  externalSlug  String value for externalSlug.
     * @param  id  String value for id.
     * @param  linkedIssueIds  List of String value for linkedIssueIds.
     * @param  url  String value for url.
     */
    public ProtosTicketingV1ExternalTicket(
            String externalSlug,
            String id,
            List<String> linkedIssueIds,
            String url) {
        this.externalSlug = externalSlug;
        this.id = id;
        this.linkedIssueIds = linkedIssueIds;
        this.url = url;
    }

    /**
     * Getter for ExternalSlug.
     * Identifier of the external ticket (e.g. for Jira, something like OPS-158).
     * @return Returns the String
     */
    @JsonGetter("externalSlug")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getExternalSlug() {
        return externalSlug;
    }

    /**
     * Setter for ExternalSlug.
     * Identifier of the external ticket (e.g. for Jira, something like OPS-158).
     * @param externalSlug Value for String
     */
    @JsonSetter("externalSlug")
    public void setExternalSlug(String externalSlug) {
        this.externalSlug = externalSlug;
    }

    /**
     * Getter for Id.
     * Nango ticket id
     * @return Returns the String
     */
    @JsonGetter("id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * Nango ticket id
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for LinkedIssueIds.
     * Semgrep issue ids that are linked to this external ticket
     * @return Returns the List of String
     */
    @JsonGetter("linkedIssueIds")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getLinkedIssueIds() {
        return linkedIssueIds;
    }

    /**
     * Setter for LinkedIssueIds.
     * Semgrep issue ids that are linked to this external ticket
     * @param linkedIssueIds Value for List of String
     */
    @JsonSetter("linkedIssueIds")
    public void setLinkedIssueIds(List<String> linkedIssueIds) {
        this.linkedIssueIds = linkedIssueIds;
    }

    /**
     * Getter for Url.
     * URL of the external ticket.
     * @return Returns the String
     */
    @JsonGetter("url")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getUrl() {
        return url;
    }

    /**
     * Setter for Url.
     * URL of the external ticket.
     * @param url Value for String
     */
    @JsonSetter("url")
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this ProtosTicketingV1ExternalTicket into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ProtosTicketingV1ExternalTicket [" + "externalSlug=" + externalSlug + ", id=" + id
                + ", linkedIssueIds=" + linkedIssueIds + ", url=" + url + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link ProtosTicketingV1ExternalTicket.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ProtosTicketingV1ExternalTicket.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .externalSlug(getExternalSlug())
                .id(getId())
                .linkedIssueIds(getLinkedIssueIds())
                .url(getUrl());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link ProtosTicketingV1ExternalTicket}.
     */
    public static class Builder {
        private String externalSlug;
        private String id;
        private List<String> linkedIssueIds;
        private String url;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for externalSlug.
         * @param  externalSlug  String value for externalSlug.
         * @return Builder
         */
        public Builder externalSlug(String externalSlug) {
            this.externalSlug = externalSlug;
            return this;
        }

        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for linkedIssueIds.
         * @param  linkedIssueIds  List of String value for linkedIssueIds.
         * @return Builder
         */
        public Builder linkedIssueIds(List<String> linkedIssueIds) {
            this.linkedIssueIds = linkedIssueIds;
            return this;
        }

        /**
         * Setter for url.
         * @param  url  String value for url.
         * @return Builder
         */
        public Builder url(String url) {
            this.url = url;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link ProtosTicketingV1ExternalTicket} object using the set fields.
         * @return {@link ProtosTicketingV1ExternalTicket}
         */
        public ProtosTicketingV1ExternalTicket build() {
            ProtosTicketingV1ExternalTicket model =
                    new ProtosTicketingV1ExternalTicket(externalSlug, id, linkedIssueIds, url);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
