/*
 * SemgrepWebAppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.semgrep.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import dev.semgrep.DateTimeHelper;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.time.LocalDateTime;
import java.util.Map;

/**
 * This is a model class for ProtosSecretsV1HistoricalInfo type.
 */
public class ProtosSecretsV1HistoricalInfo {
    private String gitBlob;
    private String gitCommit;
    private LocalDateTime gitCommitTimestamp;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public ProtosSecretsV1HistoricalInfo() {
    }

    /**
     * Initialization constructor.
     * @param  gitBlob  String value for gitBlob.
     * @param  gitCommit  String value for gitCommit.
     * @param  gitCommitTimestamp  LocalDateTime value for gitCommitTimestamp.
     */
    public ProtosSecretsV1HistoricalInfo(
            String gitBlob,
            String gitCommit,
            LocalDateTime gitCommitTimestamp) {
        this.gitBlob = gitBlob;
        this.gitCommit = gitCommit;
        this.gitCommitTimestamp = gitCommitTimestamp;
    }

    /**
     * Getter for GitBlob.
     * Git blob at which the finding is present. Sent in addition to the commit since some SCMs have
     * permalinks which use the blob sha, so this information is useful when generating links back
     * to the SCM.
     * @return Returns the String
     */
    @JsonGetter("gitBlob")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getGitBlob() {
        return gitBlob;
    }

    /**
     * Setter for GitBlob.
     * Git blob at which the finding is present. Sent in addition to the commit since some SCMs have
     * permalinks which use the blob sha, so this information is useful when generating links back
     * to the SCM.
     * @param gitBlob Value for String
     */
    @JsonSetter("gitBlob")
    public void setGitBlob(String gitBlob) {
        this.gitBlob = gitBlob;
    }

    /**
     * Getter for GitCommit.
     * Git commit at which the finding is present. Used by "historical" scans, which scan non-HEAD
     * commits in the git history. Relevant for finding, e.g., secrets which are buried in the git
     * history which we wouldn't find at HEAD
     * @return Returns the String
     */
    @JsonGetter("gitCommit")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getGitCommit() {
        return gitCommit;
    }

    /**
     * Setter for GitCommit.
     * Git commit at which the finding is present. Used by "historical" scans, which scan non-HEAD
     * commits in the git history. Relevant for finding, e.g., secrets which are buried in the git
     * history which we wouldn't find at HEAD
     * @param gitCommit Value for String
     */
    @JsonSetter("gitCommit")
    public void setGitCommit(String gitCommit) {
        this.gitCommit = gitCommit;
    }

    /**
     * Getter for GitCommitTimestamp.
     * @return Returns the LocalDateTime
     */
    @JsonGetter("gitCommitTimestamp")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getGitCommitTimestamp() {
        return gitCommitTimestamp;
    }

    /**
     * Setter for GitCommitTimestamp.
     * @param gitCommitTimestamp Value for LocalDateTime
     */
    @JsonSetter("gitCommitTimestamp")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setGitCommitTimestamp(LocalDateTime gitCommitTimestamp) {
        this.gitCommitTimestamp = gitCommitTimestamp;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this ProtosSecretsV1HistoricalInfo into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ProtosSecretsV1HistoricalInfo [" + "gitBlob=" + gitBlob + ", gitCommit=" + gitCommit
                + ", gitCommitTimestamp=" + gitCommitTimestamp + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link ProtosSecretsV1HistoricalInfo.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ProtosSecretsV1HistoricalInfo.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .gitBlob(getGitBlob())
                .gitCommit(getGitCommit())
                .gitCommitTimestamp(getGitCommitTimestamp());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link ProtosSecretsV1HistoricalInfo}.
     */
    public static class Builder {
        private String gitBlob;
        private String gitCommit;
        private LocalDateTime gitCommitTimestamp;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for gitBlob.
         * @param  gitBlob  String value for gitBlob.
         * @return Builder
         */
        public Builder gitBlob(String gitBlob) {
            this.gitBlob = gitBlob;
            return this;
        }

        /**
         * Setter for gitCommit.
         * @param  gitCommit  String value for gitCommit.
         * @return Builder
         */
        public Builder gitCommit(String gitCommit) {
            this.gitCommit = gitCommit;
            return this;
        }

        /**
         * Setter for gitCommitTimestamp.
         * @param  gitCommitTimestamp  LocalDateTime value for gitCommitTimestamp.
         * @return Builder
         */
        public Builder gitCommitTimestamp(LocalDateTime gitCommitTimestamp) {
            this.gitCommitTimestamp = gitCommitTimestamp;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link ProtosSecretsV1HistoricalInfo} object using the set fields.
         * @return {@link ProtosSecretsV1HistoricalInfo}
         */
        public ProtosSecretsV1HistoricalInfo build() {
            ProtosSecretsV1HistoricalInfo model =
                    new ProtosSecretsV1HistoricalInfo(gitBlob, gitCommit, gitCommitTimestamp);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
