/*
 * SemgrepWebAppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.semgrep.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for ProtosOpenapiV1GetBootstrapSmsVpcResponse type.
 */
public class ProtosOpenapiV1GetBootstrapSmsVpcResponse {
    private String awsTemplateFormatVersion;
    private String description;
    private Object metadata;
    private Object outputs;
    private Object parameters;
    private Object resources;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public ProtosOpenapiV1GetBootstrapSmsVpcResponse() {
    }

    /**
     * Initialization constructor.
     * @param  awsTemplateFormatVersion  String value for awsTemplateFormatVersion.
     * @param  description  String value for description.
     * @param  metadata  Object value for metadata.
     * @param  outputs  Object value for outputs.
     * @param  parameters  Object value for parameters.
     * @param  resources  Object value for resources.
     */
    public ProtosOpenapiV1GetBootstrapSmsVpcResponse(
            String awsTemplateFormatVersion,
            String description,
            Object metadata,
            Object outputs,
            Object parameters,
            Object resources) {
        this.awsTemplateFormatVersion = awsTemplateFormatVersion;
        this.description = description;
        this.metadata = metadata;
        this.outputs = outputs;
        this.parameters = parameters;
        this.resources = resources;
    }

    /**
     * Getter for AwsTemplateFormatVersion.
     * The AWSTemplateFormatVersion that the template conforms to
     * @return Returns the String
     */
    @JsonGetter("AWSTemplateFormatVersion")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAwsTemplateFormatVersion() {
        return awsTemplateFormatVersion;
    }

    /**
     * Setter for AwsTemplateFormatVersion.
     * The AWSTemplateFormatVersion that the template conforms to
     * @param awsTemplateFormatVersion Value for String
     */
    @JsonSetter("AWSTemplateFormatVersion")
    public void setAwsTemplateFormatVersion(String awsTemplateFormatVersion) {
        this.awsTemplateFormatVersion = awsTemplateFormatVersion;
    }

    /**
     * Getter for Description.
     * Template description
     * @return Returns the String
     */
    @JsonGetter("Description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * Template description
     * @param description Value for String
     */
    @JsonSetter("Description")
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for Metadata.
     * Template metadata including version and last updated date
     * @return Returns the Object
     */
    @JsonGetter("Metadata")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Object getMetadata() {
        return metadata;
    }

    /**
     * Setter for Metadata.
     * Template metadata including version and last updated date
     * @param metadata Value for Object
     */
    @JsonSetter("Metadata")
    public void setMetadata(Object metadata) {
        this.metadata = metadata;
    }

    /**
     * Getter for Outputs.
     * Output values of the stack
     * @return Returns the Object
     */
    @JsonGetter("Outputs")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Object getOutputs() {
        return outputs;
    }

    /**
     * Setter for Outputs.
     * Output values of the stack
     * @param outputs Value for Object
     */
    @JsonSetter("Outputs")
    public void setOutputs(Object outputs) {
        this.outputs = outputs;
    }

    /**
     * Getter for Parameters.
     * Template parameters
     * @return Returns the Object
     */
    @JsonGetter("Parameters")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Object getParameters() {
        return parameters;
    }

    /**
     * Setter for Parameters.
     * Template parameters
     * @param parameters Value for Object
     */
    @JsonSetter("Parameters")
    public void setParameters(Object parameters) {
        this.parameters = parameters;
    }

    /**
     * Getter for Resources.
     * Declaration of AWS resources
     * @return Returns the Object
     */
    @JsonGetter("Resources")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Object getResources() {
        return resources;
    }

    /**
     * Setter for Resources.
     * Declaration of AWS resources
     * @param resources Value for Object
     */
    @JsonSetter("Resources")
    public void setResources(Object resources) {
        this.resources = resources;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this ProtosOpenapiV1GetBootstrapSmsVpcResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ProtosOpenapiV1GetBootstrapSmsVpcResponse [" + "awsTemplateFormatVersion="
                + awsTemplateFormatVersion + ", description=" + description + ", metadata="
                + metadata + ", outputs=" + outputs + ", parameters=" + parameters + ", resources="
                + resources + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link ProtosOpenapiV1GetBootstrapSmsVpcResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ProtosOpenapiV1GetBootstrapSmsVpcResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .awsTemplateFormatVersion(getAwsTemplateFormatVersion())
                .description(getDescription())
                .metadata(getMetadata())
                .outputs(getOutputs())
                .parameters(getParameters())
                .resources(getResources());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link ProtosOpenapiV1GetBootstrapSmsVpcResponse}.
     */
    public static class Builder {
        private String awsTemplateFormatVersion;
        private String description;
        private Object metadata;
        private Object outputs;
        private Object parameters;
        private Object resources;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for awsTemplateFormatVersion.
         * @param  awsTemplateFormatVersion  String value for awsTemplateFormatVersion.
         * @return Builder
         */
        public Builder awsTemplateFormatVersion(String awsTemplateFormatVersion) {
            this.awsTemplateFormatVersion = awsTemplateFormatVersion;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  String value for description.
         * @return Builder
         */
        public Builder description(String description) {
            this.description = description;
            return this;
        }

        /**
         * Setter for metadata.
         * @param  metadata  Object value for metadata.
         * @return Builder
         */
        public Builder metadata(Object metadata) {
            this.metadata = metadata;
            return this;
        }

        /**
         * Setter for outputs.
         * @param  outputs  Object value for outputs.
         * @return Builder
         */
        public Builder outputs(Object outputs) {
            this.outputs = outputs;
            return this;
        }

        /**
         * Setter for parameters.
         * @param  parameters  Object value for parameters.
         * @return Builder
         */
        public Builder parameters(Object parameters) {
            this.parameters = parameters;
            return this;
        }

        /**
         * Setter for resources.
         * @param  resources  Object value for resources.
         * @return Builder
         */
        public Builder resources(Object resources) {
            this.resources = resources;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link ProtosOpenapiV1GetBootstrapSmsVpcResponse} object using the set
         * fields.
         * @return {@link ProtosOpenapiV1GetBootstrapSmsVpcResponse}
         */
        public ProtosOpenapiV1GetBootstrapSmsVpcResponse build() {
            ProtosOpenapiV1GetBootstrapSmsVpcResponse model =
                    new ProtosOpenapiV1GetBootstrapSmsVpcResponse(awsTemplateFormatVersion,
                            description, metadata, outputs, parameters, resources);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
