/*
 * SemgrepWebAppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.semgrep.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for ProtosScaV1PackageFilter type.
 */
public class ProtosScaV1PackageFilter {
    private Boolean exactNameMatch;
    private String exactVersion;
    private String name;
    private String versionLowerBound;
    private String versionUpperBound;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public ProtosScaV1PackageFilter() {
    }

    /**
     * Initialization constructor.
     * @param  exactNameMatch  Boolean value for exactNameMatch.
     * @param  exactVersion  String value for exactVersion.
     * @param  name  String value for name.
     * @param  versionLowerBound  String value for versionLowerBound.
     * @param  versionUpperBound  String value for versionUpperBound.
     */
    public ProtosScaV1PackageFilter(
            Boolean exactNameMatch,
            String exactVersion,
            String name,
            String versionLowerBound,
            String versionUpperBound) {
        this.exactNameMatch = exactNameMatch;
        this.exactVersion = exactVersion;
        this.name = name;
        this.versionLowerBound = versionLowerBound;
        this.versionUpperBound = versionUpperBound;
    }

    /**
     * Getter for ExactNameMatch.
     * When true, name must match exactly. When false (default), name is fuzzy-matched (contains).
     * @return Returns the Boolean
     */
    @JsonGetter("exactNameMatch")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getExactNameMatch() {
        return exactNameMatch;
    }

    /**
     * Setter for ExactNameMatch.
     * When true, name must match exactly. When false (default), name is fuzzy-matched (contains).
     * @param exactNameMatch Value for Boolean
     */
    @JsonSetter("exactNameMatch")
    public void setExactNameMatch(Boolean exactNameMatch) {
        this.exactNameMatch = exactNameMatch;
    }

    /**
     * Getter for ExactVersion.
     * Exact version match (e.g. "1.0.0"). Takes precedence over version bounds if set.
     * @return Returns the String
     */
    @JsonGetter("exactVersion")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getExactVersion() {
        return exactVersion;
    }

    /**
     * Setter for ExactVersion.
     * Exact version match (e.g. "1.0.0"). Takes precedence over version bounds if set.
     * @param exactVersion Value for String
     */
    @JsonSetter("exactVersion")
    public void setExactVersion(String exactVersion) {
        this.exactVersion = exactVersion;
    }

    /**
     * Getter for Name.
     * Exact package name (e.g. lodash).
     * @return Returns the String
     */
    @JsonGetter("name")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getName() {
        return name;
    }

    /**
     * Setter for Name.
     * Exact package name (e.g. lodash).
     * @param name Value for String
     */
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for VersionLowerBound.
     * Lower bound version constraint (e.g. "&gt;=1.0.0"). Ignored if exact_version is set.
     * @return Returns the String
     */
    @JsonGetter("versionLowerBound")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getVersionLowerBound() {
        return versionLowerBound;
    }

    /**
     * Setter for VersionLowerBound.
     * Lower bound version constraint (e.g. "&gt;=1.0.0"). Ignored if exact_version is set.
     * @param versionLowerBound Value for String
     */
    @JsonSetter("versionLowerBound")
    public void setVersionLowerBound(String versionLowerBound) {
        this.versionLowerBound = versionLowerBound;
    }

    /**
     * Getter for VersionUpperBound.
     * Upper bound version constraint (e.g. "&lt;2.0.0"). Ignored if exact_version is set.
     * @return Returns the String
     */
    @JsonGetter("versionUpperBound")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getVersionUpperBound() {
        return versionUpperBound;
    }

    /**
     * Setter for VersionUpperBound.
     * Upper bound version constraint (e.g. "&lt;2.0.0"). Ignored if exact_version is set.
     * @param versionUpperBound Value for String
     */
    @JsonSetter("versionUpperBound")
    public void setVersionUpperBound(String versionUpperBound) {
        this.versionUpperBound = versionUpperBound;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this ProtosScaV1PackageFilter into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ProtosScaV1PackageFilter [" + "exactNameMatch=" + exactNameMatch + ", exactVersion="
                + exactVersion + ", name=" + name + ", versionLowerBound=" + versionLowerBound
                + ", versionUpperBound=" + versionUpperBound + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link ProtosScaV1PackageFilter.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ProtosScaV1PackageFilter.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .exactNameMatch(getExactNameMatch())
                .exactVersion(getExactVersion())
                .name(getName())
                .versionLowerBound(getVersionLowerBound())
                .versionUpperBound(getVersionUpperBound());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link ProtosScaV1PackageFilter}.
     */
    public static class Builder {
        private Boolean exactNameMatch;
        private String exactVersion;
        private String name;
        private String versionLowerBound;
        private String versionUpperBound;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for exactNameMatch.
         * @param  exactNameMatch  Boolean value for exactNameMatch.
         * @return Builder
         */
        public Builder exactNameMatch(Boolean exactNameMatch) {
            this.exactNameMatch = exactNameMatch;
            return this;
        }

        /**
         * Setter for exactVersion.
         * @param  exactVersion  String value for exactVersion.
         * @return Builder
         */
        public Builder exactVersion(String exactVersion) {
            this.exactVersion = exactVersion;
            return this;
        }

        /**
         * Setter for name.
         * @param  name  String value for name.
         * @return Builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for versionLowerBound.
         * @param  versionLowerBound  String value for versionLowerBound.
         * @return Builder
         */
        public Builder versionLowerBound(String versionLowerBound) {
            this.versionLowerBound = versionLowerBound;
            return this;
        }

        /**
         * Setter for versionUpperBound.
         * @param  versionUpperBound  String value for versionUpperBound.
         * @return Builder
         */
        public Builder versionUpperBound(String versionUpperBound) {
            this.versionUpperBound = versionUpperBound;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link ProtosScaV1PackageFilter} object using the set fields.
         * @return {@link ProtosScaV1PackageFilter}
         */
        public ProtosScaV1PackageFilter build() {
            ProtosScaV1PackageFilter model =
                    new ProtosScaV1PackageFilter(exactNameMatch, exactVersion, name,
                            versionLowerBound, versionUpperBound);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
