/*
 * SemgrepWebAppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.semgrep.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for ProtosOpenapiV1CreateTicketResponseTicketCreationFailed type.
 */
public class ProtosOpenapiV1CreateTicketResponseTicketCreationFailed {
    private String error;
    private List<Long> issueIds;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public ProtosOpenapiV1CreateTicketResponseTicketCreationFailed() {
    }

    /**
     * Initialization constructor.
     * @param  error  String value for error.
     * @param  issueIds  List of Long value for issueIds.
     */
    public ProtosOpenapiV1CreateTicketResponseTicketCreationFailed(
            String error,
            List<Long> issueIds) {
        this.error = error;
        this.issueIds = issueIds;
    }

    /**
     * Getter for Error.
     * The error message for the failure
     * @return Returns the String
     */
    @JsonGetter("error")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getError() {
        return error;
    }

    /**
     * Setter for Error.
     * The error message for the failure
     * @param error Value for String
     */
    @JsonSetter("error")
    public void setError(String error) {
        this.error = error;
    }

    /**
     * Getter for IssueIds.
     * List of issue IDs
     * @return Returns the List of Long
     */
    @JsonGetter("issue_ids")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<Long> getIssueIds() {
        return issueIds;
    }

    /**
     * Setter for IssueIds.
     * List of issue IDs
     * @param issueIds Value for List of Long
     */
    @JsonSetter("issue_ids")
    public void setIssueIds(List<Long> issueIds) {
        this.issueIds = issueIds;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this ProtosOpenapiV1CreateTicketResponseTicketCreationFailed into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ProtosOpenapiV1CreateTicketResponseTicketCreationFailed [" + "error=" + error
                + ", issueIds=" + issueIds + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link ProtosOpenapiV1CreateTicketResponseTicketCreationFailed.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ProtosOpenapiV1CreateTicketResponseTicketCreationFailed.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .error(getError())
                .issueIds(getIssueIds());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link ProtosOpenapiV1CreateTicketResponseTicketCreationFailed}.
     */
    public static class Builder {
        private String error;
        private List<Long> issueIds;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for error.
         * @param  error  String value for error.
         * @return Builder
         */
        public Builder error(String error) {
            this.error = error;
            return this;
        }

        /**
         * Setter for issueIds.
         * @param  issueIds  List of Long value for issueIds.
         * @return Builder
         */
        public Builder issueIds(List<Long> issueIds) {
            this.issueIds = issueIds;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link ProtosOpenapiV1CreateTicketResponseTicketCreationFailed} object using
         * the set fields.
         * @return {@link ProtosOpenapiV1CreateTicketResponseTicketCreationFailed}
         */
        public ProtosOpenapiV1CreateTicketResponseTicketCreationFailed build() {
            ProtosOpenapiV1CreateTicketResponseTicketCreationFailed model =
                    new ProtosOpenapiV1CreateTicketResponseTicketCreationFailed(error, issueIds);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
