/*
 * SemgrepWebAppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.semgrep.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for ProtosAiV1Autotriage type.
 */
public class ProtosAiV1Autotriage {
    private ProtosAiV1AutotriageFeedback feedback;
    private String id;
    private String issueId;
    private String matchBasedId;
    private List<String> memoryIdsReferenced;
    private List<String> memoryIdsRendered;
    private String reason;
    private Verdict verdict;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public ProtosAiV1Autotriage() {
    }

    /**
     * Initialization constructor.
     * @param  feedback  ProtosAiV1AutotriageFeedback value for feedback.
     * @param  id  String value for id.
     * @param  issueId  String value for issueId.
     * @param  matchBasedId  String value for matchBasedId.
     * @param  memoryIdsReferenced  List of String value for memoryIdsReferenced.
     * @param  memoryIdsRendered  List of String value for memoryIdsRendered.
     * @param  reason  String value for reason.
     * @param  verdict  Verdict value for verdict.
     */
    public ProtosAiV1Autotriage(
            ProtosAiV1AutotriageFeedback feedback,
            String id,
            String issueId,
            String matchBasedId,
            List<String> memoryIdsReferenced,
            List<String> memoryIdsRendered,
            String reason,
            Verdict verdict) {
        this.feedback = feedback;
        this.id = id;
        this.issueId = issueId;
        this.matchBasedId = matchBasedId;
        this.memoryIdsReferenced = memoryIdsReferenced;
        this.memoryIdsRendered = memoryIdsRendered;
        this.reason = reason;
        this.verdict = verdict;
    }

    /**
     * Getter for Feedback.
     * @return Returns the ProtosAiV1AutotriageFeedback
     */
    @JsonGetter("feedback")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ProtosAiV1AutotriageFeedback getFeedback() {
        return feedback;
    }

    /**
     * Setter for Feedback.
     * @param feedback Value for ProtosAiV1AutotriageFeedback
     */
    @JsonSetter("feedback")
    public void setFeedback(ProtosAiV1AutotriageFeedback feedback) {
        this.feedback = feedback;
    }

    /**
     * Getter for Id.
     * @return Returns the String
     */
    @JsonGetter("id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for IssueId.
     * @return Returns the String
     */
    @JsonGetter("issueId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getIssueId() {
        return issueId;
    }

    /**
     * Setter for IssueId.
     * @param issueId Value for String
     */
    @JsonSetter("issueId")
    public void setIssueId(String issueId) {
        this.issueId = issueId;
    }

    /**
     * Getter for MatchBasedId.
     * @return Returns the String
     */
    @JsonGetter("matchBasedId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getMatchBasedId() {
        return matchBasedId;
    }

    /**
     * Setter for MatchBasedId.
     * @param matchBasedId Value for String
     */
    @JsonSetter("matchBasedId")
    public void setMatchBasedId(String matchBasedId) {
        this.matchBasedId = matchBasedId;
    }

    /**
     * Getter for MemoryIdsReferenced.
     * @return Returns the List of String
     */
    @JsonGetter("memoryIdsReferenced")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getMemoryIdsReferenced() {
        return memoryIdsReferenced;
    }

    /**
     * Setter for MemoryIdsReferenced.
     * @param memoryIdsReferenced Value for List of String
     */
    @JsonSetter("memoryIdsReferenced")
    public void setMemoryIdsReferenced(List<String> memoryIdsReferenced) {
        this.memoryIdsReferenced = memoryIdsReferenced;
    }

    /**
     * Getter for MemoryIdsRendered.
     * @return Returns the List of String
     */
    @JsonGetter("memoryIdsRendered")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getMemoryIdsRendered() {
        return memoryIdsRendered;
    }

    /**
     * Setter for MemoryIdsRendered.
     * @param memoryIdsRendered Value for List of String
     */
    @JsonSetter("memoryIdsRendered")
    public void setMemoryIdsRendered(List<String> memoryIdsRendered) {
        this.memoryIdsRendered = memoryIdsRendered;
    }

    /**
     * Getter for Reason.
     * The reasoning for a false positive verdict, explaining why you might want to ignore the
     * finding. Empty string if verdict is true positive.
     * @return Returns the String
     */
    @JsonGetter("reason")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getReason() {
        return reason;
    }

    /**
     * Setter for Reason.
     * The reasoning for a false positive verdict, explaining why you might want to ignore the
     * finding. Empty string if verdict is true positive.
     * @param reason Value for String
     */
    @JsonSetter("reason")
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * Getter for Verdict.
     * | value | description | |-------|---------------| | VERDICT_TRUE_POSITIVE | | |
     * VERDICT_FALSE_POSITIVE | | | VERDICT_NO_VERDICT | |
     * @return Returns the Verdict
     */
    @JsonGetter("verdict")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Verdict getVerdict() {
        return verdict;
    }

    /**
     * Setter for Verdict.
     * | value | description | |-------|---------------| | VERDICT_TRUE_POSITIVE | | |
     * VERDICT_FALSE_POSITIVE | | | VERDICT_NO_VERDICT | |
     * @param verdict Value for Verdict
     */
    @JsonSetter("verdict")
    public void setVerdict(Verdict verdict) {
        this.verdict = verdict;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this ProtosAiV1Autotriage into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ProtosAiV1Autotriage [" + "feedback=" + feedback + ", id=" + id + ", issueId="
                + issueId + ", matchBasedId=" + matchBasedId + ", memoryIdsReferenced="
                + memoryIdsReferenced + ", memoryIdsRendered=" + memoryIdsRendered + ", reason="
                + reason + ", verdict=" + verdict + ", additionalProperties=" + additionalProperties
                + "]";
    }

    /**
     * Builds a new {@link ProtosAiV1Autotriage.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ProtosAiV1Autotriage.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .feedback(getFeedback())
                .id(getId())
                .issueId(getIssueId())
                .matchBasedId(getMatchBasedId())
                .memoryIdsReferenced(getMemoryIdsReferenced())
                .memoryIdsRendered(getMemoryIdsRendered())
                .reason(getReason())
                .verdict(getVerdict());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link ProtosAiV1Autotriage}.
     */
    public static class Builder {
        private ProtosAiV1AutotriageFeedback feedback;
        private String id;
        private String issueId;
        private String matchBasedId;
        private List<String> memoryIdsReferenced;
        private List<String> memoryIdsRendered;
        private String reason;
        private Verdict verdict;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for feedback.
         * @param  feedback  ProtosAiV1AutotriageFeedback value for feedback.
         * @return Builder
         */
        public Builder feedback(ProtosAiV1AutotriageFeedback feedback) {
            this.feedback = feedback;
            return this;
        }

        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for issueId.
         * @param  issueId  String value for issueId.
         * @return Builder
         */
        public Builder issueId(String issueId) {
            this.issueId = issueId;
            return this;
        }

        /**
         * Setter for matchBasedId.
         * @param  matchBasedId  String value for matchBasedId.
         * @return Builder
         */
        public Builder matchBasedId(String matchBasedId) {
            this.matchBasedId = matchBasedId;
            return this;
        }

        /**
         * Setter for memoryIdsReferenced.
         * @param  memoryIdsReferenced  List of String value for memoryIdsReferenced.
         * @return Builder
         */
        public Builder memoryIdsReferenced(List<String> memoryIdsReferenced) {
            this.memoryIdsReferenced = memoryIdsReferenced;
            return this;
        }

        /**
         * Setter for memoryIdsRendered.
         * @param  memoryIdsRendered  List of String value for memoryIdsRendered.
         * @return Builder
         */
        public Builder memoryIdsRendered(List<String> memoryIdsRendered) {
            this.memoryIdsRendered = memoryIdsRendered;
            return this;
        }

        /**
         * Setter for reason.
         * @param  reason  String value for reason.
         * @return Builder
         */
        public Builder reason(String reason) {
            this.reason = reason;
            return this;
        }

        /**
         * Setter for verdict.
         * @param  verdict  Verdict value for verdict.
         * @return Builder
         */
        public Builder verdict(Verdict verdict) {
            this.verdict = verdict;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link ProtosAiV1Autotriage} object using the set fields.
         * @return {@link ProtosAiV1Autotriage}
         */
        public ProtosAiV1Autotriage build() {
            ProtosAiV1Autotriage model =
                    new ProtosAiV1Autotriage(feedback, id, issueId, matchBasedId,
                            memoryIdsReferenced, memoryIdsRendered, reason, verdict);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
