/*
 * SemgrepWebAppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.semgrep.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for ProtosScaV1SbomMetadataSupplier type.
 */
public class ProtosScaV1SbomMetadataSupplier {
    private ProtosScaV1SbomMetadataContact contact;
    private String name;
    private String url;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public ProtosScaV1SbomMetadataSupplier() {
    }

    /**
     * Initialization constructor.
     * @param  contact  ProtosScaV1SbomMetadataContact value for contact.
     * @param  name  String value for name.
     * @param  url  String value for url.
     */
    public ProtosScaV1SbomMetadataSupplier(
            ProtosScaV1SbomMetadataContact contact,
            String name,
            String url) {
        this.contact = contact;
        this.name = name;
        this.url = url;
    }

    /**
     * Getter for Contact.
     * @return Returns the ProtosScaV1SbomMetadataContact
     */
    @JsonGetter("contact")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ProtosScaV1SbomMetadataContact getContact() {
        return contact;
    }

    /**
     * Setter for Contact.
     * @param contact Value for ProtosScaV1SbomMetadataContact
     */
    @JsonSetter("contact")
    public void setContact(ProtosScaV1SbomMetadataContact contact) {
        this.contact = contact;
    }

    /**
     * Getter for Name.
     * @return Returns the String
     */
    @JsonGetter("name")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getName() {
        return name;
    }

    /**
     * Setter for Name.
     * @param name Value for String
     */
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for Url.
     * @return Returns the String
     */
    @JsonGetter("url")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getUrl() {
        return url;
    }

    /**
     * Setter for Url.
     * @param url Value for String
     */
    @JsonSetter("url")
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this ProtosScaV1SbomMetadataSupplier into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ProtosScaV1SbomMetadataSupplier [" + "contact=" + contact + ", name=" + name
                + ", url=" + url + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link ProtosScaV1SbomMetadataSupplier.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ProtosScaV1SbomMetadataSupplier.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .contact(getContact())
                .name(getName())
                .url(getUrl());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link ProtosScaV1SbomMetadataSupplier}.
     */
    public static class Builder {
        private ProtosScaV1SbomMetadataContact contact;
        private String name;
        private String url;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for contact.
         * @param  contact  ProtosScaV1SbomMetadataContact value for contact.
         * @return Builder
         */
        public Builder contact(ProtosScaV1SbomMetadataContact contact) {
            this.contact = contact;
            return this;
        }

        /**
         * Setter for name.
         * @param  name  String value for name.
         * @return Builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for url.
         * @param  url  String value for url.
         * @return Builder
         */
        public Builder url(String url) {
            this.url = url;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link ProtosScaV1SbomMetadataSupplier} object using the set fields.
         * @return {@link ProtosScaV1SbomMetadataSupplier}
         */
        public ProtosScaV1SbomMetadataSupplier build() {
            ProtosScaV1SbomMetadataSupplier model =
                    new ProtosScaV1SbomMetadataSupplier(contact, name, url);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
