/*
 * SemgrepWebAppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.semgrep.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for ProtosOpenapiV1CreateTicketResponseTicketCreationSkipped type.
 */
public class ProtosOpenapiV1CreateTicketResponseTicketCreationSkipped {
    private List<Long> issueIds;
    private String reason;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public ProtosOpenapiV1CreateTicketResponseTicketCreationSkipped() {
    }

    /**
     * Initialization constructor.
     * @param  issueIds  List of Long value for issueIds.
     * @param  reason  String value for reason.
     */
    public ProtosOpenapiV1CreateTicketResponseTicketCreationSkipped(
            List<Long> issueIds,
            String reason) {
        this.issueIds = issueIds;
        this.reason = reason;
    }

    /**
     * Getter for IssueIds.
     * List of issue IDs
     * @return Returns the List of Long
     */
    @JsonGetter("issue_ids")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<Long> getIssueIds() {
        return issueIds;
    }

    /**
     * Setter for IssueIds.
     * List of issue IDs
     * @param issueIds Value for List of Long
     */
    @JsonSetter("issue_ids")
    public void setIssueIds(List<Long> issueIds) {
        this.issueIds = issueIds;
    }

    /**
     * Getter for Reason.
     * The reason why the issue was skipped
     * @return Returns the String
     */
    @JsonGetter("reason")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getReason() {
        return reason;
    }

    /**
     * Setter for Reason.
     * The reason why the issue was skipped
     * @param reason Value for String
     */
    @JsonSetter("reason")
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this ProtosOpenapiV1CreateTicketResponseTicketCreationSkipped into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ProtosOpenapiV1CreateTicketResponseTicketCreationSkipped [" + "issueIds=" + issueIds
                + ", reason=" + reason + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link ProtosOpenapiV1CreateTicketResponseTicketCreationSkipped.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ProtosOpenapiV1CreateTicketResponseTicketCreationSkipped.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .issueIds(getIssueIds())
                .reason(getReason());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link ProtosOpenapiV1CreateTicketResponseTicketCreationSkipped}.
     */
    public static class Builder {
        private List<Long> issueIds;
        private String reason;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for issueIds.
         * @param  issueIds  List of Long value for issueIds.
         * @return Builder
         */
        public Builder issueIds(List<Long> issueIds) {
            this.issueIds = issueIds;
            return this;
        }

        /**
         * Setter for reason.
         * @param  reason  String value for reason.
         * @return Builder
         */
        public Builder reason(String reason) {
            this.reason = reason;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link ProtosOpenapiV1CreateTicketResponseTicketCreationSkipped} object
         * using the set fields.
         * @return {@link ProtosOpenapiV1CreateTicketResponseTicketCreationSkipped}
         */
        public ProtosOpenapiV1CreateTicketResponseTicketCreationSkipped build() {
            ProtosOpenapiV1CreateTicketResponseTicketCreationSkipped model =
                    new ProtosOpenapiV1CreateTicketResponseTicketCreationSkipped(issueIds, reason);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
