/*
 * SemgrepWebAppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.semgrep.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for ProtosOpenapiV1ListPoliciesResponse type.
 */
public class ProtosOpenapiV1ListPoliciesResponse {
    private List<Policy> policies;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public ProtosOpenapiV1ListPoliciesResponse() {
    }

    /**
     * Initialization constructor.
     * @param  policies  List of Policy value for policies.
     */
    public ProtosOpenapiV1ListPoliciesResponse(
            List<Policy> policies) {
        this.policies = policies;
    }

    /**
     * Getter for Policies.
     * List of Policies associated with the given Deployment.
     * @return Returns the List of Policy
     */
    @JsonGetter("policies")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<Policy> getPolicies() {
        return policies;
    }

    /**
     * Setter for Policies.
     * List of Policies associated with the given Deployment.
     * @param policies Value for List of Policy
     */
    @JsonSetter("policies")
    public void setPolicies(List<Policy> policies) {
        this.policies = policies;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this ProtosOpenapiV1ListPoliciesResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ProtosOpenapiV1ListPoliciesResponse [" + "policies=" + policies
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link ProtosOpenapiV1ListPoliciesResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ProtosOpenapiV1ListPoliciesResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .policies(getPolicies());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link ProtosOpenapiV1ListPoliciesResponse}.
     */
    public static class Builder {
        private List<Policy> policies;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for policies.
         * @param  policies  List of Policy value for policies.
         * @return Builder
         */
        public Builder policies(List<Policy> policies) {
            this.policies = policies;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link ProtosOpenapiV1ListPoliciesResponse} object using the set fields.
         * @return {@link ProtosOpenapiV1ListPoliciesResponse}
         */
        public ProtosOpenapiV1ListPoliciesResponse build() {
            ProtosOpenapiV1ListPoliciesResponse model =
                    new ProtosOpenapiV1ListPoliciesResponse(policies);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
