/*
 * SemgrepWebAppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.semgrep.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import dev.semgrep.DateTimeHelper;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for ProtosSecretsV1SecretsFinding type.
 */
public class ProtosSecretsV1SecretsFinding {
    private ProtosAiV1Autotriage autotriage;
    private Confidence7 confidence;
    private LocalDateTime createdAt;
    private ProtosTicketingV1ExternalTicket externalTicket;
    private String findingPath;
    private String findingPathUrl;
    private ProtosSecretsV1HistoricalInfo historicalInfo;
    private String id;
    private Mode mode;
    private String ref;
    private String refUrl;
    private ProtosSecretsV1SecretsFindingRepository repository;
    private List<ProtosCommonV1ReviewComment> reviewComments;
    private String ruleHashId;
    private Severity4 severity;
    private Status6 status;
    private String type;
    private LocalDateTime updatedAt;
    private ValidationState2 validationState;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public ProtosSecretsV1SecretsFinding() {
    }

    /**
     * Initialization constructor.
     * @param  autotriage  ProtosAiV1Autotriage value for autotriage.
     * @param  confidence  Confidence7 value for confidence.
     * @param  createdAt  LocalDateTime value for createdAt.
     * @param  externalTicket  ProtosTicketingV1ExternalTicket value for externalTicket.
     * @param  findingPath  String value for findingPath.
     * @param  findingPathUrl  String value for findingPathUrl.
     * @param  historicalInfo  ProtosSecretsV1HistoricalInfo value for historicalInfo.
     * @param  id  String value for id.
     * @param  mode  Mode value for mode.
     * @param  ref  String value for ref.
     * @param  refUrl  String value for refUrl.
     * @param  repository  ProtosSecretsV1SecretsFindingRepository value for repository.
     * @param  reviewComments  List of ProtosCommonV1ReviewComment value for reviewComments.
     * @param  ruleHashId  String value for ruleHashId.
     * @param  severity  Severity4 value for severity.
     * @param  status  Status6 value for status.
     * @param  type  String value for type.
     * @param  updatedAt  LocalDateTime value for updatedAt.
     * @param  validationState  ValidationState2 value for validationState.
     */
    public ProtosSecretsV1SecretsFinding(
            ProtosAiV1Autotriage autotriage,
            Confidence7 confidence,
            LocalDateTime createdAt,
            ProtosTicketingV1ExternalTicket externalTicket,
            String findingPath,
            String findingPathUrl,
            ProtosSecretsV1HistoricalInfo historicalInfo,
            String id,
            Mode mode,
            String ref,
            String refUrl,
            ProtosSecretsV1SecretsFindingRepository repository,
            List<ProtosCommonV1ReviewComment> reviewComments,
            String ruleHashId,
            Severity4 severity,
            Status6 status,
            String type,
            LocalDateTime updatedAt,
            ValidationState2 validationState) {
        this.autotriage = autotriage;
        this.confidence = confidence;
        this.createdAt = createdAt;
        this.externalTicket = externalTicket;
        this.findingPath = findingPath;
        this.findingPathUrl = findingPathUrl;
        this.historicalInfo = historicalInfo;
        this.id = id;
        this.mode = mode;
        this.ref = ref;
        this.refUrl = refUrl;
        this.repository = repository;
        this.reviewComments = reviewComments;
        this.ruleHashId = ruleHashId;
        this.severity = severity;
        this.status = status;
        this.type = type;
        this.updatedAt = updatedAt;
        this.validationState = validationState;
    }

    /**
     * Getter for Autotriage.
     * * Autotriage info for the finding. This is used for the Generic Secrets Detection project,
     * for autotriaging secrets findings with LLMs
     * @return Returns the ProtosAiV1Autotriage
     */
    @JsonGetter("autotriage")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ProtosAiV1Autotriage getAutotriage() {
        return autotriage;
    }

    /**
     * Setter for Autotriage.
     * * Autotriage info for the finding. This is used for the Generic Secrets Detection project,
     * for autotriaging secrets findings with LLMs
     * @param autotriage Value for ProtosAiV1Autotriage
     */
    @JsonSetter("autotriage")
    public void setAutotriage(ProtosAiV1Autotriage autotriage) {
        this.autotriage = autotriage;
    }

    /**
     * Getter for Confidence.
     * Confidence of the finding. | value | description | |-------|---------------| |
     * CONFIDENCE_HIGH | | | CONFIDENCE_MEDIUM | | | CONFIDENCE_LOW | |
     * @return Returns the Confidence7
     */
    @JsonGetter("confidence")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Confidence7 getConfidence() {
        return confidence;
    }

    /**
     * Setter for Confidence.
     * Confidence of the finding. | value | description | |-------|---------------| |
     * CONFIDENCE_HIGH | | | CONFIDENCE_MEDIUM | | | CONFIDENCE_LOW | |
     * @param confidence Value for Confidence7
     */
    @JsonSetter("confidence")
    public void setConfidence(Confidence7 confidence) {
        this.confidence = confidence;
    }

    /**
     * Getter for CreatedAt.
     * Creation timestamp.
     * @return Returns the LocalDateTime
     */
    @JsonGetter("createdAt")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * Setter for CreatedAt.
     * Creation timestamp.
     * @param createdAt Value for LocalDateTime
     */
    @JsonSetter("createdAt")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for ExternalTicket.
     * The external ticket reference
     * @return Returns the ProtosTicketingV1ExternalTicket
     */
    @JsonGetter("externalTicket")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ProtosTicketingV1ExternalTicket getExternalTicket() {
        return externalTicket;
    }

    /**
     * Setter for ExternalTicket.
     * The external ticket reference
     * @param externalTicket Value for ProtosTicketingV1ExternalTicket
     */
    @JsonSetter("externalTicket")
    public void setExternalTicket(ProtosTicketingV1ExternalTicket externalTicket) {
        this.externalTicket = externalTicket;
    }

    /**
     * Getter for FindingPath.
     * File path where the finding was detected.
     * @return Returns the String
     */
    @JsonGetter("findingPath")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getFindingPath() {
        return findingPath;
    }

    /**
     * Setter for FindingPath.
     * File path where the finding was detected.
     * @param findingPath Value for String
     */
    @JsonSetter("findingPath")
    public void setFindingPath(String findingPath) {
        this.findingPath = findingPath;
    }

    /**
     * Getter for FindingPathUrl.
     * URL to the file where the finding was detected.
     * @return Returns the String
     */
    @JsonGetter("findingPathUrl")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getFindingPathUrl() {
        return findingPathUrl;
    }

    /**
     * Setter for FindingPathUrl.
     * URL to the file where the finding was detected.
     * @param findingPathUrl Value for String
     */
    @JsonSetter("findingPathUrl")
    public void setFindingPathUrl(String findingPathUrl) {
        this.findingPathUrl = findingPathUrl;
    }

    /**
     * Getter for HistoricalInfo.
     * Historical scanning info for the finding.
     * @return Returns the ProtosSecretsV1HistoricalInfo
     */
    @JsonGetter("historicalInfo")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ProtosSecretsV1HistoricalInfo getHistoricalInfo() {
        return historicalInfo;
    }

    /**
     * Setter for HistoricalInfo.
     * Historical scanning info for the finding.
     * @param historicalInfo Value for ProtosSecretsV1HistoricalInfo
     */
    @JsonSetter("historicalInfo")
    public void setHistoricalInfo(ProtosSecretsV1HistoricalInfo historicalInfo) {
        this.historicalInfo = historicalInfo;
    }

    /**
     * Getter for Id.
     * ID of the finding.
     * @return Returns the String
     */
    @JsonGetter("id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * ID of the finding.
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for Mode.
     * The behavior of the finding reporting: Monitor / Comment / Block. | value | description |
     * |-------|---------------| | MODE_MONITOR | Monitor mode, silently report findings | |
     * MODE_COMMENT | Comment mode, leaves PR comments but does not block | | MODE_BLOCK | Block
     * mode, leaves PR comments and blocks PR | | MODE_DISABLED | Disabled mode, not active |
     * @return Returns the Mode
     */
    @JsonGetter("mode")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Mode getMode() {
        return mode;
    }

    /**
     * Setter for Mode.
     * The behavior of the finding reporting: Monitor / Comment / Block. | value | description |
     * |-------|---------------| | MODE_MONITOR | Monitor mode, silently report findings | |
     * MODE_COMMENT | Comment mode, leaves PR comments but does not block | | MODE_BLOCK | Block
     * mode, leaves PR comments and blocks PR | | MODE_DISABLED | Disabled mode, not active |
     * @param mode Value for Mode
     */
    @JsonSetter("mode")
    public void setMode(Mode mode) {
        this.mode = mode;
    }

    /**
     * Getter for Ref.
     * Branch where the finding was detected.
     * @return Returns the String
     */
    @JsonGetter("ref")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getRef() {
        return ref;
    }

    /**
     * Setter for Ref.
     * Branch where the finding was detected.
     * @param ref Value for String
     */
    @JsonSetter("ref")
    public void setRef(String ref) {
        this.ref = ref;
    }

    /**
     * Getter for RefUrl.
     * URL to the branch where the finding was detected.
     * @return Returns the String
     */
    @JsonGetter("refUrl")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getRefUrl() {
        return refUrl;
    }

    /**
     * Setter for RefUrl.
     * URL to the branch where the finding was detected.
     * @param refUrl Value for String
     */
    @JsonSetter("refUrl")
    public void setRefUrl(String refUrl) {
        this.refUrl = refUrl;
    }

    /**
     * Getter for Repository.
     * Repository where the finding was detected.
     * @return Returns the ProtosSecretsV1SecretsFindingRepository
     */
    @JsonGetter("repository")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ProtosSecretsV1SecretsFindingRepository getRepository() {
        return repository;
    }

    /**
     * Setter for Repository.
     * Repository where the finding was detected.
     * @param repository Value for ProtosSecretsV1SecretsFindingRepository
     */
    @JsonSetter("repository")
    public void setRepository(ProtosSecretsV1SecretsFindingRepository repository) {
        this.repository = repository;
    }

    /**
     * Getter for ReviewComments.
     * List of external review comment information associated with a finding
     * @return Returns the List of ProtosCommonV1ReviewComment
     */
    @JsonGetter("reviewComments")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<ProtosCommonV1ReviewComment> getReviewComments() {
        return reviewComments;
    }

    /**
     * Setter for ReviewComments.
     * List of external review comment information associated with a finding
     * @param reviewComments Value for List of ProtosCommonV1ReviewComment
     */
    @JsonSetter("reviewComments")
    public void setReviewComments(List<ProtosCommonV1ReviewComment> reviewComments) {
        this.reviewComments = reviewComments;
    }

    /**
     * Getter for RuleHashId.
     * ID of the rule that triggered the finding.
     * @return Returns the String
     */
    @JsonGetter("ruleHashId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getRuleHashId() {
        return ruleHashId;
    }

    /**
     * Setter for RuleHashId.
     * ID of the rule that triggered the finding.
     * @param ruleHashId Value for String
     */
    @JsonSetter("ruleHashId")
    public void setRuleHashId(String ruleHashId) {
        this.ruleHashId = ruleHashId;
    }

    /**
     * Getter for Severity.
     * Severity of the finding. | value | description | |-------|---------------| | SEVERITY_HIGH |
     * | | SEVERITY_MEDIUM | | | SEVERITY_LOW | | | SEVERITY_CRITICAL | |
     * @return Returns the Severity4
     */
    @JsonGetter("severity")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Severity4 getSeverity() {
        return severity;
    }

    /**
     * Setter for Severity.
     * Severity of the finding. | value | description | |-------|---------------| | SEVERITY_HIGH |
     * | | SEVERITY_MEDIUM | | | SEVERITY_LOW | | | SEVERITY_CRITICAL | |
     * @param severity Value for Severity4
     */
    @JsonSetter("severity")
    public void setSeverity(Severity4 severity) {
        this.severity = severity;
    }

    /**
     * Getter for Status.
     * Status of the finding. | value | description | |-------|---------------| |
     * FINDING_STATUS_OPEN | | | FINDING_STATUS_IGNORED | | | FINDING_STATUS_FIXED | | |
     * FINDING_STATUS_REMOVED | | | FINDING_STATUS_UNKNOWN | | |
     * FINDING_STATUS_PROVISIONALLY_IGNORED | |
     * @return Returns the Status6
     */
    @JsonGetter("status")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Status6 getStatus() {
        return status;
    }

    /**
     * Setter for Status.
     * Status of the finding. | value | description | |-------|---------------| |
     * FINDING_STATUS_OPEN | | | FINDING_STATUS_IGNORED | | | FINDING_STATUS_FIXED | | |
     * FINDING_STATUS_REMOVED | | | FINDING_STATUS_UNKNOWN | | |
     * FINDING_STATUS_PROVISIONALLY_IGNORED | |
     * @param status Value for Status6
     */
    @JsonSetter("status")
    public void setStatus(Status6 status) {
        this.status = status;
    }

    /**
     * Getter for Type.
     * Service type for the secrets finding (e.g. AWS, GitHub, GitLab, etc).
     * @return Returns the String
     */
    @JsonGetter("type")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getType() {
        return type;
    }

    /**
     * Setter for Type.
     * Service type for the secrets finding (e.g. AWS, GitHub, GitLab, etc).
     * @param type Value for String
     */
    @JsonSetter("type")
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Getter for UpdatedAt.
     * Update timestamp.
     * @return Returns the LocalDateTime
     */
    @JsonGetter("updatedAt")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * Setter for UpdatedAt.
     * Update timestamp.
     * @param updatedAt Value for LocalDateTime
     */
    @JsonSetter("updatedAt")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for ValidationState.
     * Whether the finding was validated or not. | value | description | |-------|---------------| |
     * VALIDATION_STATE_CONFIRMED_VALID | | | VALIDATION_STATE_CONFIRMED_INVALID | | |
     * VALIDATION_STATE_VALIDATION_ERROR | | | VALIDATION_STATE_NO_VALIDATOR | |
     * @return Returns the ValidationState2
     */
    @JsonGetter("validationState")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ValidationState2 getValidationState() {
        return validationState;
    }

    /**
     * Setter for ValidationState.
     * Whether the finding was validated or not. | value | description | |-------|---------------| |
     * VALIDATION_STATE_CONFIRMED_VALID | | | VALIDATION_STATE_CONFIRMED_INVALID | | |
     * VALIDATION_STATE_VALIDATION_ERROR | | | VALIDATION_STATE_NO_VALIDATOR | |
     * @param validationState Value for ValidationState2
     */
    @JsonSetter("validationState")
    public void setValidationState(ValidationState2 validationState) {
        this.validationState = validationState;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this ProtosSecretsV1SecretsFinding into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ProtosSecretsV1SecretsFinding [" + "autotriage=" + autotriage + ", confidence="
                + confidence + ", createdAt=" + createdAt + ", externalTicket=" + externalTicket
                + ", findingPath=" + findingPath + ", findingPathUrl=" + findingPathUrl
                + ", historicalInfo=" + historicalInfo + ", id=" + id + ", mode=" + mode + ", ref="
                + ref + ", refUrl=" + refUrl + ", repository=" + repository + ", reviewComments="
                + reviewComments + ", ruleHashId=" + ruleHashId + ", severity=" + severity
                + ", status=" + status + ", type=" + type + ", updatedAt=" + updatedAt
                + ", validationState=" + validationState + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link ProtosSecretsV1SecretsFinding.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ProtosSecretsV1SecretsFinding.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .autotriage(getAutotriage())
                .confidence(getConfidence())
                .createdAt(getCreatedAt())
                .externalTicket(getExternalTicket())
                .findingPath(getFindingPath())
                .findingPathUrl(getFindingPathUrl())
                .historicalInfo(getHistoricalInfo())
                .id(getId())
                .mode(getMode())
                .ref(getRef())
                .refUrl(getRefUrl())
                .repository(getRepository())
                .reviewComments(getReviewComments())
                .ruleHashId(getRuleHashId())
                .severity(getSeverity())
                .status(getStatus())
                .type(getType())
                .updatedAt(getUpdatedAt())
                .validationState(getValidationState());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link ProtosSecretsV1SecretsFinding}.
     */
    public static class Builder {
        private ProtosAiV1Autotriage autotriage;
        private Confidence7 confidence;
        private LocalDateTime createdAt;
        private ProtosTicketingV1ExternalTicket externalTicket;
        private String findingPath;
        private String findingPathUrl;
        private ProtosSecretsV1HistoricalInfo historicalInfo;
        private String id;
        private Mode mode;
        private String ref;
        private String refUrl;
        private ProtosSecretsV1SecretsFindingRepository repository;
        private List<ProtosCommonV1ReviewComment> reviewComments;
        private String ruleHashId;
        private Severity4 severity;
        private Status6 status;
        private String type;
        private LocalDateTime updatedAt;
        private ValidationState2 validationState;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for autotriage.
         * @param  autotriage  ProtosAiV1Autotriage value for autotriage.
         * @return Builder
         */
        public Builder autotriage(ProtosAiV1Autotriage autotriage) {
            this.autotriage = autotriage;
            return this;
        }

        /**
         * Setter for confidence.
         * @param  confidence  Confidence7 value for confidence.
         * @return Builder
         */
        public Builder confidence(Confidence7 confidence) {
            this.confidence = confidence;
            return this;
        }

        /**
         * Setter for createdAt.
         * @param  createdAt  LocalDateTime value for createdAt.
         * @return Builder
         */
        public Builder createdAt(LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * Setter for externalTicket.
         * @param  externalTicket  ProtosTicketingV1ExternalTicket value for externalTicket.
         * @return Builder
         */
        public Builder externalTicket(ProtosTicketingV1ExternalTicket externalTicket) {
            this.externalTicket = externalTicket;
            return this;
        }

        /**
         * Setter for findingPath.
         * @param  findingPath  String value for findingPath.
         * @return Builder
         */
        public Builder findingPath(String findingPath) {
            this.findingPath = findingPath;
            return this;
        }

        /**
         * Setter for findingPathUrl.
         * @param  findingPathUrl  String value for findingPathUrl.
         * @return Builder
         */
        public Builder findingPathUrl(String findingPathUrl) {
            this.findingPathUrl = findingPathUrl;
            return this;
        }

        /**
         * Setter for historicalInfo.
         * @param  historicalInfo  ProtosSecretsV1HistoricalInfo value for historicalInfo.
         * @return Builder
         */
        public Builder historicalInfo(ProtosSecretsV1HistoricalInfo historicalInfo) {
            this.historicalInfo = historicalInfo;
            return this;
        }

        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for mode.
         * @param  mode  Mode value for mode.
         * @return Builder
         */
        public Builder mode(Mode mode) {
            this.mode = mode;
            return this;
        }

        /**
         * Setter for ref.
         * @param  ref  String value for ref.
         * @return Builder
         */
        public Builder ref(String ref) {
            this.ref = ref;
            return this;
        }

        /**
         * Setter for refUrl.
         * @param  refUrl  String value for refUrl.
         * @return Builder
         */
        public Builder refUrl(String refUrl) {
            this.refUrl = refUrl;
            return this;
        }

        /**
         * Setter for repository.
         * @param  repository  ProtosSecretsV1SecretsFindingRepository value for repository.
         * @return Builder
         */
        public Builder repository(ProtosSecretsV1SecretsFindingRepository repository) {
            this.repository = repository;
            return this;
        }

        /**
         * Setter for reviewComments.
         * @param  reviewComments  List of ProtosCommonV1ReviewComment value for reviewComments.
         * @return Builder
         */
        public Builder reviewComments(List<ProtosCommonV1ReviewComment> reviewComments) {
            this.reviewComments = reviewComments;
            return this;
        }

        /**
         * Setter for ruleHashId.
         * @param  ruleHashId  String value for ruleHashId.
         * @return Builder
         */
        public Builder ruleHashId(String ruleHashId) {
            this.ruleHashId = ruleHashId;
            return this;
        }

        /**
         * Setter for severity.
         * @param  severity  Severity4 value for severity.
         * @return Builder
         */
        public Builder severity(Severity4 severity) {
            this.severity = severity;
            return this;
        }

        /**
         * Setter for status.
         * @param  status  Status6 value for status.
         * @return Builder
         */
        public Builder status(Status6 status) {
            this.status = status;
            return this;
        }

        /**
         * Setter for type.
         * @param  type  String value for type.
         * @return Builder
         */
        public Builder type(String type) {
            this.type = type;
            return this;
        }

        /**
         * Setter for updatedAt.
         * @param  updatedAt  LocalDateTime value for updatedAt.
         * @return Builder
         */
        public Builder updatedAt(LocalDateTime updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        /**
         * Setter for validationState.
         * @param  validationState  ValidationState2 value for validationState.
         * @return Builder
         */
        public Builder validationState(ValidationState2 validationState) {
            this.validationState = validationState;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link ProtosSecretsV1SecretsFinding} object using the set fields.
         * @return {@link ProtosSecretsV1SecretsFinding}
         */
        public ProtosSecretsV1SecretsFinding build() {
            ProtosSecretsV1SecretsFinding model =
                    new ProtosSecretsV1SecretsFinding(autotriage, confidence, createdAt,
                            externalTicket, findingPath, findingPathUrl, historicalInfo, id, mode,
                            ref, refUrl, repository, reviewComments, ruleHashId, severity, status,
                            type, updatedAt, validationState);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
