/*
 * SemgrepWebAppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.semgrep.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import dev.semgrep.DateTimeHelper;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for Rule type.
 */
public class Rule {
    private String category;
    private Confidence confidence;
    private List<String> cweCategories;
    private Boolean hasValidators;
    private String id;
    private List<String> languages;
    private LocalDateTime lastChangeAt;
    private String lastChangeBy;
    private List<String> owaspCategories;
    private String path;
    private PolicyMode policyMode;
    private String registryMaintainer;
    private List<String> rulesets;
    private String secretType;
    private Severity severity;
    private Source source;
    private List<String> technologies;
    private String url;
    private List<String> vulnerabilityClass;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public Rule() {
    }

    /**
     * Initialization constructor.
     * @param  category  String value for category.
     * @param  confidence  Confidence value for confidence.
     * @param  cweCategories  List of String value for cweCategories.
     * @param  hasValidators  Boolean value for hasValidators.
     * @param  id  String value for id.
     * @param  languages  List of String value for languages.
     * @param  lastChangeAt  LocalDateTime value for lastChangeAt.
     * @param  lastChangeBy  String value for lastChangeBy.
     * @param  owaspCategories  List of String value for owaspCategories.
     * @param  path  String value for path.
     * @param  policyMode  PolicyMode value for policyMode.
     * @param  registryMaintainer  String value for registryMaintainer.
     * @param  rulesets  List of String value for rulesets.
     * @param  secretType  String value for secretType.
     * @param  severity  Severity value for severity.
     * @param  source  Source value for source.
     * @param  technologies  List of String value for technologies.
     * @param  url  String value for url.
     * @param  vulnerabilityClass  List of String value for vulnerabilityClass.
     */
    public Rule(
            String category,
            Confidence confidence,
            List<String> cweCategories,
            Boolean hasValidators,
            String id,
            List<String> languages,
            LocalDateTime lastChangeAt,
            String lastChangeBy,
            List<String> owaspCategories,
            String path,
            PolicyMode policyMode,
            String registryMaintainer,
            List<String> rulesets,
            String secretType,
            Severity severity,
            Source source,
            List<String> technologies,
            String url,
            List<String> vulnerabilityClass) {
        this.category = category;
        this.confidence = confidence;
        this.cweCategories = cweCategories;
        this.hasValidators = hasValidators;
        this.id = id;
        this.languages = languages;
        this.lastChangeAt = lastChangeAt;
        this.lastChangeBy = lastChangeBy;
        this.owaspCategories = owaspCategories;
        this.path = path;
        this.policyMode = policyMode;
        this.registryMaintainer = registryMaintainer;
        this.rulesets = rulesets;
        this.secretType = secretType;
        this.severity = severity;
        this.source = source;
        this.technologies = technologies;
        this.url = url;
        this.vulnerabilityClass = vulnerabilityClass;
    }

    /**
     * Getter for Category.
     * Category the Rule is associated with.
     * @return Returns the String
     */
    @JsonGetter("category")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCategory() {
        return category;
    }

    /**
     * Setter for Category.
     * Category the Rule is associated with.
     * @param category Value for String
     */
    @JsonSetter("category")
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * Getter for Confidence.
     * Confidence based on the Rule's false-positive rate. | value | description |
     * |-------|---------------| | CONFIDENCE_HIGH | | | CONFIDENCE_MEDIUM | | | CONFIDENCE_LOW | |
     * @return Returns the Confidence
     */
    @JsonGetter("confidence")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Confidence getConfidence() {
        return confidence;
    }

    /**
     * Setter for Confidence.
     * Confidence based on the Rule's false-positive rate. | value | description |
     * |-------|---------------| | CONFIDENCE_HIGH | | | CONFIDENCE_MEDIUM | | | CONFIDENCE_LOW | |
     * @param confidence Value for Confidence
     */
    @JsonSetter("confidence")
    public void setConfidence(Confidence confidence) {
        this.confidence = confidence;
    }

    /**
     * Getter for CweCategories.
     * The CWE associated with the Rule.
     * @return Returns the List of String
     */
    @JsonGetter("cweCategories")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getCweCategories() {
        return cweCategories;
    }

    /**
     * Setter for CweCategories.
     * The CWE associated with the Rule.
     * @param cweCategories Value for List of String
     */
    @JsonSetter("cweCategories")
    public void setCweCategories(List<String> cweCategories) {
        this.cweCategories = cweCategories;
    }

    /**
     * Getter for HasValidators.
     * When True, the secrets rule has validators.
     * @return Returns the Boolean
     */
    @JsonGetter("hasValidators")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getHasValidators() {
        return hasValidators;
    }

    /**
     * Setter for HasValidators.
     * When True, the secrets rule has validators.
     * @param hasValidators Value for Boolean
     */
    @JsonSetter("hasValidators")
    public void setHasValidators(Boolean hasValidators) {
        this.hasValidators = hasValidators;
    }

    /**
     * Getter for Id.
     * ID of the Rule.
     * @return Returns the String
     */
    @JsonGetter("id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * ID of the Rule.
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for Languages.
     * Languages the Rule applies to.
     * @return Returns the List of String
     */
    @JsonGetter("languages")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getLanguages() {
        return languages;
    }

    /**
     * Setter for Languages.
     * Languages the Rule applies to.
     * @param languages Value for List of String
     */
    @JsonSetter("languages")
    public void setLanguages(List<String> languages) {
        this.languages = languages;
    }

    /**
     * Getter for LastChangeAt.
     * Timestamp of when the Rule was last changed.
     * @return Returns the LocalDateTime
     */
    @JsonGetter("lastChangeAt")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getLastChangeAt() {
        return lastChangeAt;
    }

    /**
     * Setter for LastChangeAt.
     * Timestamp of when the Rule was last changed.
     * @param lastChangeAt Value for LocalDateTime
     */
    @JsonSetter("lastChangeAt")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setLastChangeAt(LocalDateTime lastChangeAt) {
        this.lastChangeAt = lastChangeAt;
    }

    /**
     * Getter for LastChangeBy.
     * Username of who last changed the Rule.
     * @return Returns the String
     */
    @JsonGetter("lastChangeBy")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getLastChangeBy() {
        return lastChangeBy;
    }

    /**
     * Setter for LastChangeBy.
     * Username of who last changed the Rule.
     * @param lastChangeBy Value for String
     */
    @JsonSetter("lastChangeBy")
    public void setLastChangeBy(String lastChangeBy) {
        this.lastChangeBy = lastChangeBy;
    }

    /**
     * Getter for OwaspCategories.
     * Owasp categories the Rule is associated with.
     * @return Returns the List of String
     */
    @JsonGetter("owaspCategories")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getOwaspCategories() {
        return owaspCategories;
    }

    /**
     * Setter for OwaspCategories.
     * Owasp categories the Rule is associated with.
     * @param owaspCategories Value for List of String
     */
    @JsonSetter("owaspCategories")
    public void setOwaspCategories(List<String> owaspCategories) {
        this.owaspCategories = owaspCategories;
    }

    /**
     * Getter for Path.
     * Full path of the Rule.
     * @return Returns the String
     */
    @JsonGetter("path")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getPath() {
        return path;
    }

    /**
     * Setter for Path.
     * Full path of the Rule.
     * @param path Value for String
     */
    @JsonSetter("path")
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * Getter for PolicyMode.
     * Mode behavior: Monitor / Comment / Block / Disabled | value | description |
     * |-------|---------------| | MODE_MONITOR | Monitor mode, silently report findings | |
     * MODE_COMMENT | Comment mode, leaves PR comments but does not block | | MODE_BLOCK | Block
     * mode, leaves PR comments and blocks PR | | MODE_DISABLED | Disabled mode, not active |
     * @return Returns the PolicyMode
     */
    @JsonGetter("policyMode")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public PolicyMode getPolicyMode() {
        return policyMode;
    }

    /**
     * Setter for PolicyMode.
     * Mode behavior: Monitor / Comment / Block / Disabled | value | description |
     * |-------|---------------| | MODE_MONITOR | Monitor mode, silently report findings | |
     * MODE_COMMENT | Comment mode, leaves PR comments but does not block | | MODE_BLOCK | Block
     * mode, leaves PR comments and blocks PR | | MODE_DISABLED | Disabled mode, not active |
     * @param policyMode Value for PolicyMode
     */
    @JsonSetter("policyMode")
    public void setPolicyMode(PolicyMode policyMode) {
        this.policyMode = policyMode;
    }

    /**
     * Getter for RegistryMaintainer.
     * The Registry maintainer associated with the Rule (if applicable).
     * @return Returns the String
     */
    @JsonGetter("registryMaintainer")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getRegistryMaintainer() {
        return registryMaintainer;
    }

    /**
     * Setter for RegistryMaintainer.
     * The Registry maintainer associated with the Rule (if applicable).
     * @param registryMaintainer Value for String
     */
    @JsonSetter("registryMaintainer")
    public void setRegistryMaintainer(String registryMaintainer) {
        this.registryMaintainer = registryMaintainer;
    }

    /**
     * Getter for Rulesets.
     * Rulesets to which the Rule belongs (if applicable).
     * @return Returns the List of String
     */
    @JsonGetter("rulesets")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getRulesets() {
        return rulesets;
    }

    /**
     * Setter for Rulesets.
     * Rulesets to which the Rule belongs (if applicable).
     * @param rulesets Value for List of String
     */
    @JsonSetter("rulesets")
    public void setRulesets(List<String> rulesets) {
        this.rulesets = rulesets;
    }

    /**
     * Getter for SecretType.
     * The secret type (if applicable).
     * @return Returns the String
     */
    @JsonGetter("secretType")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getSecretType() {
        return secretType;
    }

    /**
     * Setter for SecretType.
     * The secret type (if applicable).
     * @param secretType Value for String
     */
    @JsonSetter("secretType")
    public void setSecretType(String secretType) {
        this.secretType = secretType;
    }

    /**
     * Getter for Severity.
     * Severity level ("seriousness" of the finding) | value | description |
     * |-------|---------------| | SEVERITY_HIGH | | | SEVERITY_MEDIUM | | | SEVERITY_LOW | | |
     * SEVERITY_CRITICAL | |
     * @return Returns the Severity
     */
    @JsonGetter("severity")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Severity getSeverity() {
        return severity;
    }

    /**
     * Setter for Severity.
     * Severity level ("seriousness" of the finding) | value | description |
     * |-------|---------------| | SEVERITY_HIGH | | | SEVERITY_MEDIUM | | | SEVERITY_LOW | | |
     * SEVERITY_CRITICAL | |
     * @param severity Value for Severity
     */
    @JsonSetter("severity")
    public void setSeverity(Severity severity) {
        this.severity = severity;
    }

    /**
     * Getter for Source.
     * Source of the Rule | value | description | |-------|---------------| | SOURCE_PRO | From Pro
     * rules | | SOURCE_COMMUNITY | From Semgrep Community rules | | SOURCE_CUSTOM | From Custom
     * rules |
     * @return Returns the Source
     */
    @JsonGetter("source")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Source getSource() {
        return source;
    }

    /**
     * Setter for Source.
     * Source of the Rule | value | description | |-------|---------------| | SOURCE_PRO | From Pro
     * rules | | SOURCE_COMMUNITY | From Semgrep Community rules | | SOURCE_CUSTOM | From Custom
     * rules |
     * @param source Value for Source
     */
    @JsonSetter("source")
    public void setSource(Source source) {
        this.source = source;
    }

    /**
     * Getter for Technologies.
     * Technologies the Rule is associated with.
     * @return Returns the List of String
     */
    @JsonGetter("technologies")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getTechnologies() {
        return technologies;
    }

    /**
     * Setter for Technologies.
     * Technologies the Rule is associated with.
     * @param technologies Value for List of String
     */
    @JsonSetter("technologies")
    public void setTechnologies(List<String> technologies) {
        this.technologies = technologies;
    }

    /**
     * Getter for Url.
     * The URL of the Rule.
     * @return Returns the String
     */
    @JsonGetter("url")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getUrl() {
        return url;
    }

    /**
     * Setter for Url.
     * The URL of the Rule.
     * @param url Value for String
     */
    @JsonSetter("url")
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * Getter for VulnerabilityClass.
     * Vulnerability classes the Rule is associated with.
     * @return Returns the List of String
     */
    @JsonGetter("vulnerabilityClass")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getVulnerabilityClass() {
        return vulnerabilityClass;
    }

    /**
     * Setter for VulnerabilityClass.
     * Vulnerability classes the Rule is associated with.
     * @param vulnerabilityClass Value for List of String
     */
    @JsonSetter("vulnerabilityClass")
    public void setVulnerabilityClass(List<String> vulnerabilityClass) {
        this.vulnerabilityClass = vulnerabilityClass;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this Rule into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Rule [" + "category=" + category + ", confidence=" + confidence + ", cweCategories="
                + cweCategories + ", hasValidators=" + hasValidators + ", id=" + id + ", languages="
                + languages + ", lastChangeAt=" + lastChangeAt + ", lastChangeBy=" + lastChangeBy
                + ", owaspCategories=" + owaspCategories + ", path=" + path + ", policyMode="
                + policyMode + ", registryMaintainer=" + registryMaintainer + ", rulesets="
                + rulesets + ", secretType=" + secretType + ", severity=" + severity + ", source="
                + source + ", technologies=" + technologies + ", url=" + url
                + ", vulnerabilityClass=" + vulnerabilityClass + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link Rule.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Rule.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .category(getCategory())
                .confidence(getConfidence())
                .cweCategories(getCweCategories())
                .hasValidators(getHasValidators())
                .id(getId())
                .languages(getLanguages())
                .lastChangeAt(getLastChangeAt())
                .lastChangeBy(getLastChangeBy())
                .owaspCategories(getOwaspCategories())
                .path(getPath())
                .policyMode(getPolicyMode())
                .registryMaintainer(getRegistryMaintainer())
                .rulesets(getRulesets())
                .secretType(getSecretType())
                .severity(getSeverity())
                .source(getSource())
                .technologies(getTechnologies())
                .url(getUrl())
                .vulnerabilityClass(getVulnerabilityClass());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link Rule}.
     */
    public static class Builder {
        private String category;
        private Confidence confidence;
        private List<String> cweCategories;
        private Boolean hasValidators;
        private String id;
        private List<String> languages;
        private LocalDateTime lastChangeAt;
        private String lastChangeBy;
        private List<String> owaspCategories;
        private String path;
        private PolicyMode policyMode;
        private String registryMaintainer;
        private List<String> rulesets;
        private String secretType;
        private Severity severity;
        private Source source;
        private List<String> technologies;
        private String url;
        private List<String> vulnerabilityClass;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for category.
         * @param  category  String value for category.
         * @return Builder
         */
        public Builder category(String category) {
            this.category = category;
            return this;
        }

        /**
         * Setter for confidence.
         * @param  confidence  Confidence value for confidence.
         * @return Builder
         */
        public Builder confidence(Confidence confidence) {
            this.confidence = confidence;
            return this;
        }

        /**
         * Setter for cweCategories.
         * @param  cweCategories  List of String value for cweCategories.
         * @return Builder
         */
        public Builder cweCategories(List<String> cweCategories) {
            this.cweCategories = cweCategories;
            return this;
        }

        /**
         * Setter for hasValidators.
         * @param  hasValidators  Boolean value for hasValidators.
         * @return Builder
         */
        public Builder hasValidators(Boolean hasValidators) {
            this.hasValidators = hasValidators;
            return this;
        }

        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for languages.
         * @param  languages  List of String value for languages.
         * @return Builder
         */
        public Builder languages(List<String> languages) {
            this.languages = languages;
            return this;
        }

        /**
         * Setter for lastChangeAt.
         * @param  lastChangeAt  LocalDateTime value for lastChangeAt.
         * @return Builder
         */
        public Builder lastChangeAt(LocalDateTime lastChangeAt) {
            this.lastChangeAt = lastChangeAt;
            return this;
        }

        /**
         * Setter for lastChangeBy.
         * @param  lastChangeBy  String value for lastChangeBy.
         * @return Builder
         */
        public Builder lastChangeBy(String lastChangeBy) {
            this.lastChangeBy = lastChangeBy;
            return this;
        }

        /**
         * Setter for owaspCategories.
         * @param  owaspCategories  List of String value for owaspCategories.
         * @return Builder
         */
        public Builder owaspCategories(List<String> owaspCategories) {
            this.owaspCategories = owaspCategories;
            return this;
        }

        /**
         * Setter for path.
         * @param  path  String value for path.
         * @return Builder
         */
        public Builder path(String path) {
            this.path = path;
            return this;
        }

        /**
         * Setter for policyMode.
         * @param  policyMode  PolicyMode value for policyMode.
         * @return Builder
         */
        public Builder policyMode(PolicyMode policyMode) {
            this.policyMode = policyMode;
            return this;
        }

        /**
         * Setter for registryMaintainer.
         * @param  registryMaintainer  String value for registryMaintainer.
         * @return Builder
         */
        public Builder registryMaintainer(String registryMaintainer) {
            this.registryMaintainer = registryMaintainer;
            return this;
        }

        /**
         * Setter for rulesets.
         * @param  rulesets  List of String value for rulesets.
         * @return Builder
         */
        public Builder rulesets(List<String> rulesets) {
            this.rulesets = rulesets;
            return this;
        }

        /**
         * Setter for secretType.
         * @param  secretType  String value for secretType.
         * @return Builder
         */
        public Builder secretType(String secretType) {
            this.secretType = secretType;
            return this;
        }

        /**
         * Setter for severity.
         * @param  severity  Severity value for severity.
         * @return Builder
         */
        public Builder severity(Severity severity) {
            this.severity = severity;
            return this;
        }

        /**
         * Setter for source.
         * @param  source  Source value for source.
         * @return Builder
         */
        public Builder source(Source source) {
            this.source = source;
            return this;
        }

        /**
         * Setter for technologies.
         * @param  technologies  List of String value for technologies.
         * @return Builder
         */
        public Builder technologies(List<String> technologies) {
            this.technologies = technologies;
            return this;
        }

        /**
         * Setter for url.
         * @param  url  String value for url.
         * @return Builder
         */
        public Builder url(String url) {
            this.url = url;
            return this;
        }

        /**
         * Setter for vulnerabilityClass.
         * @param  vulnerabilityClass  List of String value for vulnerabilityClass.
         * @return Builder
         */
        public Builder vulnerabilityClass(List<String> vulnerabilityClass) {
            this.vulnerabilityClass = vulnerabilityClass;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link Rule} object using the set fields.
         * @return {@link Rule}
         */
        public Rule build() {
            Rule model =
                    new Rule(category, confidence, cweCategories, hasValidators, id, languages,
                            lastChangeAt, lastChangeBy, owaspCategories, path, policyMode,
                            registryMaintainer, rulesets, secretType, severity, source,
                            technologies, url, vulnerabilityClass);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
