/*
 * SemgrepWebAppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.semgrep.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for SastFindings type.
 */
public class SastFindings {
    private List<SastFinding> findings;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public SastFindings() {
    }

    /**
     * Initialization constructor.
     * @param  findings  List of SastFinding value for findings.
     */
    public SastFindings(
            List<SastFinding> findings) {
        this.findings = findings;
    }

    /**
     * Getter for Findings.
     * A list of Code findings.
     * @return Returns the List of SastFinding
     */
    @JsonGetter("findings")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<SastFinding> getFindings() {
        return findings;
    }

    /**
     * Setter for Findings.
     * A list of Code findings.
     * @param findings Value for List of SastFinding
     */
    @JsonSetter("findings")
    public void setFindings(List<SastFinding> findings) {
        this.findings = findings;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this SastFindings into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SastFindings [" + "findings=" + findings + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link SastFindings.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link SastFindings.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .findings(getFindings());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link SastFindings}.
     */
    public static class Builder {
        private List<SastFinding> findings;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for findings.
         * @param  findings  List of SastFinding value for findings.
         * @return Builder
         */
        public Builder findings(List<SastFinding> findings) {
            this.findings = findings;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link SastFindings} object using the set fields.
         * @return {@link SastFindings}
         */
        public SastFindings build() {
            SastFindings model =
                    new SastFindings(findings);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
