/*
 * SemgrepWebAppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.semgrep.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * SbomOutputFormat to be used.
 */
public enum SbomOutputFormat {
    SBOM_OUTPUT_FORMAT_JSON,

    SBOM_OUTPUT_FORMAT_CYCLONEDX;

    private static TreeMap<String, SbomOutputFormat> valueMap = new TreeMap<>();
    private String value;

    static {
        SBOM_OUTPUT_FORMAT_JSON.value = "SBOM_OUTPUT_FORMAT_JSON";
        SBOM_OUTPUT_FORMAT_CYCLONEDX.value = "SBOM_OUTPUT_FORMAT_CYCLONEDX";

        valueMap.put("SBOM_OUTPUT_FORMAT_JSON", SBOM_OUTPUT_FORMAT_JSON);
        valueMap.put("SBOM_OUTPUT_FORMAT_CYCLONEDX", SBOM_OUTPUT_FORMAT_CYCLONEDX);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static SbomOutputFormat constructFromString(String toConvert) throws IOException {
        SbomOutputFormat enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static SbomOutputFormat fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of SbomOutputFormat values to list of string values.
     * @param toConvert The list of SbomOutputFormat values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<SbomOutputFormat> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (SbomOutputFormat enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 