/*
 * SemgrepWebAppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.semgrep.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * Severity4 to be used.
 */
public enum Severity4 {
    SEVERITY_HIGH,

    SEVERITY_MEDIUM,

    SEVERITY_LOW,

    SEVERITY_CRITICAL;

    private static TreeMap<String, Severity4> valueMap = new TreeMap<>();
    private String value;

    static {
        SEVERITY_HIGH.value = "SEVERITY_HIGH";
        SEVERITY_MEDIUM.value = "SEVERITY_MEDIUM";
        SEVERITY_LOW.value = "SEVERITY_LOW";
        SEVERITY_CRITICAL.value = "SEVERITY_CRITICAL";

        valueMap.put("SEVERITY_HIGH", SEVERITY_HIGH);
        valueMap.put("SEVERITY_MEDIUM", SEVERITY_MEDIUM);
        valueMap.put("SEVERITY_LOW", SEVERITY_LOW);
        valueMap.put("SEVERITY_CRITICAL", SEVERITY_CRITICAL);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static Severity4 constructFromString(String toConvert) throws IOException {
        Severity4 enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static Severity4 fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of Severity4 values to list of string values.
     * @param toConvert The list of Severity4 values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<Severity4> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (Severity4 enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 