/*
 * SemgrepWebAppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.semgrep.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * Status8 to be used.
 */
public enum Status8 {
    FINDING_STATUS_UNSPECIFIED,

    FINDING_STATUS_OPEN,

    FINDING_STATUS_IGNORED,

    FINDING_STATUS_FIXED,

    FINDING_STATUS_REMOVED,

    FINDING_STATUS_UNKNOWN,

    FINDING_STATUS_PROVISIONALLY_IGNORED;

    private static TreeMap<String, Status8> valueMap = new TreeMap<>();
    private String value;

    static {
        FINDING_STATUS_UNSPECIFIED.value = "FINDING_STATUS_UNSPECIFIED";
        FINDING_STATUS_OPEN.value = "FINDING_STATUS_OPEN";
        FINDING_STATUS_IGNORED.value = "FINDING_STATUS_IGNORED";
        FINDING_STATUS_FIXED.value = "FINDING_STATUS_FIXED";
        FINDING_STATUS_REMOVED.value = "FINDING_STATUS_REMOVED";
        FINDING_STATUS_UNKNOWN.value = "FINDING_STATUS_UNKNOWN";
        FINDING_STATUS_PROVISIONALLY_IGNORED.value = "FINDING_STATUS_PROVISIONALLY_IGNORED";

        valueMap.put("FINDING_STATUS_UNSPECIFIED", FINDING_STATUS_UNSPECIFIED);
        valueMap.put("FINDING_STATUS_OPEN", FINDING_STATUS_OPEN);
        valueMap.put("FINDING_STATUS_IGNORED", FINDING_STATUS_IGNORED);
        valueMap.put("FINDING_STATUS_FIXED", FINDING_STATUS_FIXED);
        valueMap.put("FINDING_STATUS_REMOVED", FINDING_STATUS_REMOVED);
        valueMap.put("FINDING_STATUS_UNKNOWN", FINDING_STATUS_UNKNOWN);
        valueMap.put("FINDING_STATUS_PROVISIONALLY_IGNORED", FINDING_STATUS_PROVISIONALLY_IGNORED);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static Status8 constructFromString(String toConvert) throws IOException {
        Status8 enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static Status8 fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of Status8 values to list of string values.
     * @param toConvert The list of Status8 values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<Status8> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (Status8 enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 