/*
 * SemgrepWebAppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.semgrep.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for ToggleProjectManagedScanRequest type.
 */
public class ToggleProjectManagedScanRequest {
    private String deploymentSlug;
    private ProtosOpenapiV1DiffScan diffScan;
    private ProtosOpenapiV1FullScan fullScan;
    private String projectName;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public ToggleProjectManagedScanRequest() {
    }

    /**
     * Initialization constructor.
     * @param  deploymentSlug  String value for deploymentSlug.
     * @param  projectName  String value for projectName.
     * @param  diffScan  ProtosOpenapiV1DiffScan value for diffScan.
     * @param  fullScan  ProtosOpenapiV1FullScan value for fullScan.
     */
    public ToggleProjectManagedScanRequest(
            String deploymentSlug,
            String projectName,
            ProtosOpenapiV1DiffScan diffScan,
            ProtosOpenapiV1FullScan fullScan) {
        this.deploymentSlug = deploymentSlug;
        this.diffScan = diffScan;
        this.fullScan = fullScan;
        this.projectName = projectName;
    }

    /**
     * Getter for DeploymentSlug.
     * Slug of the deployment name. Can be found at `/deployments`, or in your Settings in the web
     * UI.
     * @return Returns the String
     */
    @JsonGetter("deploymentSlug")
    public String getDeploymentSlug() {
        return deploymentSlug;
    }

    /**
     * Setter for DeploymentSlug.
     * Slug of the deployment name. Can be found at `/deployments`, or in your Settings in the web
     * UI.
     * @param deploymentSlug Value for String
     */
    @JsonSetter("deploymentSlug")
    public void setDeploymentSlug(String deploymentSlug) {
        this.deploymentSlug = deploymentSlug;
    }

    /**
     * Getter for DiffScan.
     * @return Returns the ProtosOpenapiV1DiffScan
     */
    @JsonGetter("diff_scan")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ProtosOpenapiV1DiffScan getDiffScan() {
        return diffScan;
    }

    /**
     * Setter for DiffScan.
     * @param diffScan Value for ProtosOpenapiV1DiffScan
     */
    @JsonSetter("diff_scan")
    public void setDiffScan(ProtosOpenapiV1DiffScan diffScan) {
        this.diffScan = diffScan;
    }

    /**
     * Getter for FullScan.
     * @return Returns the ProtosOpenapiV1FullScan
     */
    @JsonGetter("full_scan")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ProtosOpenapiV1FullScan getFullScan() {
        return fullScan;
    }

    /**
     * Setter for FullScan.
     * @param fullScan Value for ProtosOpenapiV1FullScan
     */
    @JsonSetter("full_scan")
    public void setFullScan(ProtosOpenapiV1FullScan fullScan) {
        this.fullScan = fullScan;
    }

    /**
     * Getter for ProjectName.
     * Name of the project, typically the repository formatted as a path.
     * @return Returns the String
     */
    @JsonGetter("projectName")
    public String getProjectName() {
        return projectName;
    }

    /**
     * Setter for ProjectName.
     * Name of the project, typically the repository formatted as a path.
     * @param projectName Value for String
     */
    @JsonSetter("projectName")
    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this ToggleProjectManagedScanRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ToggleProjectManagedScanRequest [" + "deploymentSlug=" + deploymentSlug
                + ", projectName=" + projectName + ", diffScan=" + diffScan + ", fullScan="
                + fullScan + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link ToggleProjectManagedScanRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ToggleProjectManagedScanRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(deploymentSlug, projectName)
                .diffScan(getDiffScan())
                .fullScan(getFullScan());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link ToggleProjectManagedScanRequest}.
     */
    public static class Builder {
        private String deploymentSlug;
        private String projectName;
        private ProtosOpenapiV1DiffScan diffScan;
        private ProtosOpenapiV1FullScan fullScan;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  deploymentSlug  String value for deploymentSlug.
         * @param  projectName  String value for projectName.
         */
        public Builder(String deploymentSlug, String projectName) {
            this.deploymentSlug = deploymentSlug;
            this.projectName = projectName;
        }

        /**
         * Setter for deploymentSlug.
         * @param  deploymentSlug  String value for deploymentSlug.
         * @return Builder
         */
        public Builder deploymentSlug(String deploymentSlug) {
            this.deploymentSlug = deploymentSlug;
            return this;
        }

        /**
         * Setter for projectName.
         * @param  projectName  String value for projectName.
         * @return Builder
         */
        public Builder projectName(String projectName) {
            this.projectName = projectName;
            return this;
        }

        /**
         * Setter for diffScan.
         * @param  diffScan  ProtosOpenapiV1DiffScan value for diffScan.
         * @return Builder
         */
        public Builder diffScan(ProtosOpenapiV1DiffScan diffScan) {
            this.diffScan = diffScan;
            return this;
        }

        /**
         * Setter for fullScan.
         * @param  fullScan  ProtosOpenapiV1FullScan value for fullScan.
         * @return Builder
         */
        public Builder fullScan(ProtosOpenapiV1FullScan fullScan) {
            this.fullScan = fullScan;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link ToggleProjectManagedScanRequest} object using the set fields.
         * @return {@link ToggleProjectManagedScanRequest}
         */
        public ToggleProjectManagedScanRequest build() {
            ToggleProjectManagedScanRequest model =
                    new ToggleProjectManagedScanRequest(deploymentSlug, projectName, diffScan,
                            fullScan);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
