/*
 * SemgrepWebAppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.semgrep.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for UpdatePolicyRequest type.
 */
public class UpdatePolicyRequest {
    private String deploymentId;
    private String policyId;
    private PolicyMode3 policyMode;
    private String rulePath;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public UpdatePolicyRequest() {
    }

    /**
     * Initialization constructor.
     * @param  deploymentId  String value for deploymentId.
     * @param  policyId  String value for policyId.
     * @param  policyMode  PolicyMode3 value for policyMode.
     * @param  rulePath  String value for rulePath.
     */
    public UpdatePolicyRequest(
            String deploymentId,
            String policyId,
            PolicyMode3 policyMode,
            String rulePath) {
        this.deploymentId = deploymentId;
        this.policyId = policyId;
        this.policyMode = policyMode;
        this.rulePath = rulePath;
    }

    /**
     * Getter for DeploymentId.
     * Deployment ID (numeric). Example: `123`. Can be found at `/deployments`, or in your Settings
     * in the web UI.
     * @return Returns the String
     */
    @JsonGetter("deploymentId")
    public String getDeploymentId() {
        return deploymentId;
    }

    /**
     * Setter for DeploymentId.
     * Deployment ID (numeric). Example: `123`. Can be found at `/deployments`, or in your Settings
     * in the web UI.
     * @param deploymentId Value for String
     */
    @JsonSetter("deploymentId")
    public void setDeploymentId(String deploymentId) {
        this.deploymentId = deploymentId;
    }

    /**
     * Getter for PolicyId.
     * Policy ID (numeric). Example: `456`. Can be found at `/deployments/{deploymentId}/policies`.
     * @return Returns the String
     */
    @JsonGetter("policyId")
    public String getPolicyId() {
        return policyId;
    }

    /**
     * Setter for PolicyId.
     * Policy ID (numeric). Example: `456`. Can be found at `/deployments/{deploymentId}/policies`.
     * @param policyId Value for String
     */
    @JsonSetter("policyId")
    public void setPolicyId(String policyId) {
        this.policyId = policyId;
    }

    /**
     * Getter for PolicyMode.
     * New policy mode to set for the Rule. - MODE_MONITOR: Monitor mode, silently report findings -
     * MODE_COMMENT: Comment mode, leaves PR comments but does not block - MODE_BLOCK: Block mode,
     * leaves PR comments and blocks PR - MODE_DISABLED: Disabled mode, not active | value |
     * description | |-------|---------------| | MODE_MONITOR | Monitor mode, silently report
     * findings | | MODE_COMMENT | Comment mode, leaves PR comments but does not block | |
     * MODE_BLOCK | Block mode, leaves PR comments and blocks PR | | MODE_DISABLED | Disabled mode,
     * not active |
     * @return Returns the PolicyMode3
     */
    @JsonGetter("policyMode")
    public PolicyMode3 getPolicyMode() {
        return policyMode;
    }

    /**
     * Setter for PolicyMode.
     * New policy mode to set for the Rule. - MODE_MONITOR: Monitor mode, silently report findings -
     * MODE_COMMENT: Comment mode, leaves PR comments but does not block - MODE_BLOCK: Block mode,
     * leaves PR comments and blocks PR - MODE_DISABLED: Disabled mode, not active | value |
     * description | |-------|---------------| | MODE_MONITOR | Monitor mode, silently report
     * findings | | MODE_COMMENT | Comment mode, leaves PR comments but does not block | |
     * MODE_BLOCK | Block mode, leaves PR comments and blocks PR | | MODE_DISABLED | Disabled mode,
     * not active |
     * @param policyMode Value for PolicyMode3
     */
    @JsonSetter("policyMode")
    public void setPolicyMode(PolicyMode3 policyMode) {
        this.policyMode = policyMode;
    }

    /**
     * Getter for RulePath.
     * Full path of the Rule.
     * @return Returns the String
     */
    @JsonGetter("rulePath")
    public String getRulePath() {
        return rulePath;
    }

    /**
     * Setter for RulePath.
     * Full path of the Rule.
     * @param rulePath Value for String
     */
    @JsonSetter("rulePath")
    public void setRulePath(String rulePath) {
        this.rulePath = rulePath;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this UpdatePolicyRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "UpdatePolicyRequest [" + "deploymentId=" + deploymentId + ", policyId=" + policyId
                + ", policyMode=" + policyMode + ", rulePath=" + rulePath
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link UpdatePolicyRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link UpdatePolicyRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(deploymentId, policyId, policyMode, rulePath);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link UpdatePolicyRequest}.
     */
    public static class Builder {
        private String deploymentId;
        private String policyId;
        private PolicyMode3 policyMode;
        private String rulePath;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  deploymentId  String value for deploymentId.
         * @param  policyId  String value for policyId.
         * @param  policyMode  PolicyMode3 value for policyMode.
         * @param  rulePath  String value for rulePath.
         */
        public Builder(String deploymentId, String policyId, PolicyMode3 policyMode,
                String rulePath) {
            this.deploymentId = deploymentId;
            this.policyId = policyId;
            this.policyMode = policyMode;
            this.rulePath = rulePath;
        }

        /**
         * Setter for deploymentId.
         * @param  deploymentId  String value for deploymentId.
         * @return Builder
         */
        public Builder deploymentId(String deploymentId) {
            this.deploymentId = deploymentId;
            return this;
        }

        /**
         * Setter for policyId.
         * @param  policyId  String value for policyId.
         * @return Builder
         */
        public Builder policyId(String policyId) {
            this.policyId = policyId;
            return this;
        }

        /**
         * Setter for policyMode.
         * @param  policyMode  PolicyMode3 value for policyMode.
         * @return Builder
         */
        public Builder policyMode(PolicyMode3 policyMode) {
            this.policyMode = policyMode;
            return this;
        }

        /**
         * Setter for rulePath.
         * @param  rulePath  String value for rulePath.
         * @return Builder
         */
        public Builder rulePath(String rulePath) {
            this.rulePath = rulePath;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link UpdatePolicyRequest} object using the set fields.
         * @return {@link UpdatePolicyRequest}
         */
        public UpdatePolicyRequest build() {
            UpdatePolicyRequest model =
                    new UpdatePolicyRequest(deploymentId, policyId, policyMode, rulePath);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
