/*
 * SemgrepWebAppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.semgrep.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for UpdateProjectResponse type.
 */
public class UpdateProjectResponse {
    private Project project;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public UpdateProjectResponse() {
    }

    /**
     * Initialization constructor.
     * @param  project  Project value for project.
     */
    public UpdateProjectResponse(
            Project project) {
        this.project = project;
    }

    /**
     * Getter for Project.
     * A project in your organization that uses Semgrep.
     * @return Returns the Project
     */
    @JsonGetter("project")
    public Project getProject() {
        return project;
    }

    /**
     * Setter for Project.
     * A project in your organization that uses Semgrep.
     * @param project Value for Project
     */
    @JsonSetter("project")
    public void setProject(Project project) {
        this.project = project;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this UpdateProjectResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "UpdateProjectResponse [" + "project=" + project + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link UpdateProjectResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link UpdateProjectResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(project);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link UpdateProjectResponse}.
     */
    public static class Builder {
        private Project project;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  project  Project value for project.
         */
        public Builder(Project project) {
            this.project = project;
        }

        /**
         * Setter for project.
         * @param  project  Project value for project.
         * @return Builder
         */
        public Builder project(Project project) {
            this.project = project;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link UpdateProjectResponse} object using the set fields.
         * @return {@link UpdateProjectResponse}
         */
        public UpdateProjectResponse build() {
            UpdateProjectResponse model =
                    new UpdateProjectResponse(project);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
