/*
 * SemgrepWebAppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.semgrep.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for Usage type.
 */
public class Usage {
    private ExternalTicket externalTicket;
    private FindingLocation location;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public Usage() {
    }

    /**
     * Initialization constructor.
     * @param  externalTicket  ExternalTicket value for externalTicket.
     * @param  location  FindingLocation value for location.
     */
    public Usage(
            ExternalTicket externalTicket,
            FindingLocation location) {
        this.externalTicket = externalTicket;
        this.location = location;
    }

    /**
     * Getter for ExternalTicket.
     * External ticket associated with finding
     * @return Returns the ExternalTicket
     */
    @JsonGetter("external_ticket")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ExternalTicket getExternalTicket() {
        return externalTicket;
    }

    /**
     * Setter for ExternalTicket.
     * External ticket associated with finding
     * @param externalTicket Value for ExternalTicket
     */
    @JsonSetter("external_ticket")
    public void setExternalTicket(ExternalTicket externalTicket) {
        this.externalTicket = externalTicket;
    }

    /**
     * Getter for Location.
     * Location of the record in a file, as reported by Semgrep. If null, then the information does
     * not exist or lacks integrity (older or broken scans)
     * @return Returns the FindingLocation
     */
    @JsonGetter("location")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public FindingLocation getLocation() {
        return location;
    }

    /**
     * Setter for Location.
     * Location of the record in a file, as reported by Semgrep. If null, then the information does
     * not exist or lacks integrity (older or broken scans)
     * @param location Value for FindingLocation
     */
    @JsonSetter("location")
    public void setLocation(FindingLocation location) {
        this.location = location;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this Usage into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Usage [" + "externalTicket=" + externalTicket + ", location=" + location
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link Usage.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Usage.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .externalTicket(getExternalTicket())
                .location(getLocation());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link Usage}.
     */
    public static class Builder {
        private ExternalTicket externalTicket;
        private FindingLocation location;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for externalTicket.
         * @param  externalTicket  ExternalTicket value for externalTicket.
         * @return Builder
         */
        public Builder externalTicket(ExternalTicket externalTicket) {
            this.externalTicket = externalTicket;
            return this;
        }

        /**
         * Setter for location.
         * @param  location  FindingLocation value for location.
         * @return Builder
         */
        public Builder location(FindingLocation location) {
            this.location = location;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link Usage} object using the set fields.
         * @return {@link Usage}
         */
        public Usage build() {
            Usage model =
                    new Usage(externalTicket, location);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
