/*
 * SemgrepWebAppLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package dev.semgrep.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * Verdict1 to be used.
 */
public enum Verdict1 {
    FALSE_POSITIVE,

    TRUE_POSITIVE;

    private static TreeMap<String, Verdict1> valueMap = new TreeMap<>();
    private String value;

    static {
        FALSE_POSITIVE.value = "false_positive";
        TRUE_POSITIVE.value = "true_positive";

        valueMap.put("false_positive", FALSE_POSITIVE);
        valueMap.put("true_positive", TRUE_POSITIVE);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static Verdict1 constructFromString(String toConvert) throws IOException {
        Verdict1 enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static Verdict1 fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of Verdict1 values to list of string values.
     * @param toConvert The list of Verdict1 values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<Verdict1> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (Verdict1 enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 